In [ ]:
import pandas as pd
import re
import os
import json
from datetime import datetime
from google.colab import drive
drive.mount('/content/drive')
from nltk.tokenize import sent_tokenize, word_tokenize

Mounted at /content/drive

# Load Data

In [ ]:
directory = "/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Wikipedia/populated/"

In [ ]:
%cd '/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Wikipedia/populated/'
%rm *:*

/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Wikipedia/populated

In [ ]:
%cd '/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Wikipedia/populated/'
%ls | grep .json | wc -l
# %ls | grep :

/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Wikipedia/populated
28046

In [ ]:
df = pd.DataFrame()
for file in os.listdir(directory):
  name, extension = os.path.splitext(file)
  print(name, extension)
  if extension == '.json':
    newData = pd.read_json(open(directory+file), typ='index', orient='records')
    # print(newData)
    df = df.append(newData, ignore_index=True)
df

Ingles-(paglilinaw) .json
Araling-pangkapaligiran .json
Panggagamot .json
Arkitektura .json
Transportasyon .json
Inhenyeriya .json
Politika .json
Isotope .json
Teknolohiya .json
Enero-11 .json
Enero-12 .json
Enero-13 .json
Enero-14 .json
Sopwer-Inhenyeriya .json
Batas .json
Tatlong-Kaharian-ng-Korea .json
Enero-17 .json
Kategorya:Kasaysayan-ng-Korea .json
Enero-15 .json
Enero-16 .json
Enero-18 .json
Enero-19 .json
Enero-20 .json
Enero-21 .json
Enero-23 .json
Enero-24 .json
Enero-26 .json
Enero-25 .json
Enero-22 .json
Enero-27 .json
Enero-28 .json
Enero-29 .json
Enero-30 .json
Enero-31 .json
Kategorya:Araw .json
Padron:StatusEndangered .json
Padron:Phylum .json
Padron:Ordo .json
Kategorya:Agham .json
Padron:Genus .json
Padron:Familia .json
Manati .json
Patintero .json
Harang-taga .json
Teorya-ng-natatanging-relatibidad .json
Ugnayang-pampubliko .json
Wikipedia:Patungkol .json
Kalakal .json
Antropolohiya .json
Negosyo .json
Wikipedia:Help .json
Agham-pampolitika .json
Digmaang-Pilipino–Amerikano .json
1878 .json
1944 .json
Gobyerno .json
Arkeolohiya .json
Lingguwistika .json
Europa .json
Pohjola .json
Richard-Stallman .json
Wikang-Pranses .json
Free-Software-Foundation .json
Ekonomika .json
Sikolohiya .json
Sosyolohiya .json
Mitolohiya .json
Telekomunikasyon .json
Kasaysayan .json
Panghimagsikang-Hukbong-Katihan-ng-Pilipinas .json
Katipunan .json
Kasaysayan-ng-agham-at-teknolohiya .json
Kabite .json
Tejeros .json
Sarangani .json
Paglilibang .json
Kawit .json
Luzon .json
Mga-probinsya-ng-Pilipinas .json
Espanya .json
Spain .json
Kapisanan-ni-Hesus .json
España .json
Klasikos .json
Jesuit .json
Sining .json
Rizal-(paglilinaw) .json
Sayaw .json
Pinagmamasdang-sining .json
Panlililok .json
Pinta .json
Palakasan .json
Pagbabasa .json
Pelikula .json
Pagbabasa-(teknikal) .json
Pagbabasa-(gawain) .json
Pag-aaliw .json
Panulaan .json
Turismo .json
Tanghalan .json
Handicraft .json
Sining-ng-mga-gawaing-kamay .json
Opera-(paglilinaw) .json
Opera .json
Paghahalaman .json
Pista .json
Eben-Moglen .json
Hulyo-1 .json
Hulyo-2 .json
Lungsod-ng-Klaipėda .json
Hulyo-3 .json
Pamilya .json
EDSA .json
Internet .json
Kategorya:Internet .json
Padron:Cat-more .json
Tugtugin .json
Maganak .json
Angkan .json
Paglalakbay .json
Pagkain-at-inumin .json
Pagkain .json
Kalusugan .json
Rafael-del-Riego .json
Kagalingan .json
Tahanan .json
Bahay .json
Pakikipagtalastasan .json
Karera .json
Mga-tao .json
Taong-bayan .json
Mga-Tao .json
Pipol .json
Persona .json
Katauhan .json
Oradea .json
Pakikipagkapwa-tao .json
Muixeranga .json
Panaginip .json
Agham-pangmundo .json
Pebrero-2 .json
Pebrero-3 .json
Pebrero-4 .json
Pebrero-5 .json
Pebrero-1 .json
Pebrero-6 .json
Pebrero-7 .json
Pebrero-9 .json
Pebrero-8 .json
Pebrero-10 .json
Balangkas-ng-Pilipinas .json
1935 .json
Marso-23 .json
Pebrero-11 .json
Pebrero-12 .json
Pebrero-14 .json
Pebrero-13 .json
Pebrero-15 .json
Pebrero-16 .json
Pebrero-17 .json
MediaWiki:Monobook.css .json
Pebrero-18 .json
Mayo-1 .json
Pebrero-19 .json
MediaWiki:Allarticles .json
MediaWiki:Allpagesnext .json
MediaWiki:Allpagesprev .json
MediaWiki:Categoryarticlecount1 .json
MediaWiki:Editingcomment .json
MediaWiki:Currentevents-url .json
MediaWiki:Newwindow .json
MediaWiki:Sharedupload .json
MediaWiki:Nosuchusershort .json
MediaWiki:Templatesused .json
MediaWiki:Tagline .json
Software .json
Talaan-ng-mga-Pilipino .json
Tala-ng-mga-organisasyon,-kompanya,-at-institusyon-sa-Pilipinas .json
Listahan-ng-mga-wika-sa-Pilipinas .json
Wikipedia:Mga-wika,-dialektiko,-at-iba-pang-lingguwistikang-artikulo-na-may-kaugnayan-sa-Pilipinas .json
Wikipedia:Mga-iskima-ng-kategorya .json
Wikipedia:Category-schemes .json
Araw-(astronomiya) .json
Padron:Ibanggamit .json
Malayang-nilalaman .json
Pebrero-20 .json
Pebrero-21 .json
Pebrero-23 .json
Pebrero-24 .json
Pebrero-26 .json
Pebrero-27 .json
Pebrero-28 .json
Pebrero-29 .json
Hulyo-5 .json
Hulyo-6 .json
Himagsikang-Heorhiyano-sa-Texel .json
Kategorya:Kalendaryo .json
Tala-ng-mga-dekada,-dantaon,-at-milenyo .json
Virgilio-S.-Almario .json
Banna,-Ilocos-Norte .json
Virgilio-Almario .json
Banna .json
Joseph-Estrada .json
Unibersidad-ng-Pilipinas .json
Wikang-pamprograma .json
Programming-language .json
Hilagang-Samar .json
Bulacan .json
Kompyuter .json
Wikipedia:Maghanap-o-magkumpuni-ng-stub .json
Pampublikong-dominyo .json
Meycauayan .json
Padron:Infobox-Philippine-province .json
Kategorya:Stub .json
Pilipinong-Amerikano .json
Computer-language .json
De-La-Salle-University,-Manila .json
Yuropa .json
Logika .json
Talaan-ng-mga-disiplinang-pang-akademiya .json
Lohika .json
Sandara-Park .json
Mga-Ilokano .json
Iloko .json
Araling-Pilipino .json
Gloria-Macapagal-Arroyo .json
Komunikasyong-gamit-ang-kompyuter .json
MTV-Philippines .json
Pagpapalaglag .json
Hulyo-7 .json
Hulyo-8 .json
Tsina .json
Karagatang-Pasipiko .json
Wikang-Kastila .json
Batanes .json
Wikang-Filipino .json
Talaksan:Ph-seal-batanes.png .json
True-Audio .json
Arturo-R.-Luz .json
Eurodistrito .json
Vevey .json
Bekennende-Kirche .json
Writer's-block .json
Deklarasyon-ng-Barmen .json
Writer’s-block .json
Eurodistrict .json
Confessing-Church .json
DLSZ .json
Paaralang-De-La-Salle-Santiago-Zóbel .json
Wikang-Inggles .json
Djindjic .json
Estados-Unidos .json
Katolisismo .json
Nagkakaisang-Estados .json
Thom-Filicia .json
Carson-Kressley .json
Ussuriysk .json
Kastila-sa-Pilipinas .json
Wikang-Kastila-sa-Pilipinas .json
DLSU .json
Ewropa .json
Unibersidad-ng-De-La-Salle .json
Länder-ng-Alemanya .json
Länder .json
Laender .json
Bundesland .json
Bundeslaender .json
Bundesländer .json
Tropiko .json
Watawat-ng-Pilipinas .json
Sagisag-ng-Republika-ng-Pilipinas .json
Opisyal-na-wika .json
Mindanao .json
Kabisayaan .json
Alemanya .json
Pransiya .json
Timor-Leste .json
Italya .json
Palau .json
Taiwan .json
Kapuluang-Mariana .json
Pakikiramdam .json
Dagat-Pilipinas .json
Pacific-Ocean .json
Padron:Infobox-Bansa .json
Pacific .json
Pasipiko .json
Samar-(pulo) .json
Linux .json
Samar-(island) .json
Karagatan .json
Pag-aasawa .json
Silangang-Timor .json
Triskelion .json
Elementaryang-Alhebra .json
Algebra .json
Pagbabawas .json
Pagdaragdag .json
Kategorya:Matematika .json
Multiplication .json
Pagpaparami-(matematika) .json
Paghahati .json
Division .json
Eksponente .json
Miriam-Defensor–Santiago .json
Exponent .json
Esponente .json
TTA .json
Addition .json
Subtraction .json
Tta .json
Kategorya:Astronomiya .json
Kategorya:Agham-pangkompyuter .json
Kategorya:Ekolohiya .json
Kategorya:Pisika .json
Kategorya:Agrikultura .json
Kategorya:Estadistika .json
Kategorya:Arkitektura .json
Kategorya:Komunikasyon .json
Kategorya:Edukasyon .json
Kategorya:Inhinyeriya .json
Kategorya:Batas .json
Kategorya:Pamahalaan .json
Kategorya:Panggagamot .json
Kategorya:Politika .json
Kategorya:Ugnayang-pampubliko .json
Kategorya:Software-engineering .json
Kategorya:Teknolohiya .json
Kategorya:Transportasyon .json
Kategorya:Antropolohiya .json
Kategorya:Agham-panlipunan-at-pilosopiya .json
Kategorya:Arkeolohiya .json
Kategorya:Ekonomiya .json
Kategorya:Heograpiya .json
Kategorya:Kasaysayan .json
Marso-1 .json
Geology .json
Kategorya:Wika .json
Heolohiya .json
All-Hail,-Liberia,-Hail! .json
Poligong-bituin .json
Altair .json
Kalesa .json
Kristalograpiya .json
Johann-Sebastian-Bach .json
Bach .json
Kategorya:Musika .json
Kategorya:Kultura-at-sining .json
Kategorya:Kultura .json
Kategorya:Unang-pahina .json
Kategorya:Laro .json
Mga-libangan .json
Mga-pista .json
Kategorya:Radyo .json
Kategorya:Telebisyon .json
Kategorya:Pansariling-buhay .json
Kategorya:Kalusugan .json
Anatomiya .json
Kategorya:Wikipedia .json
Kategorya:Anatomiya .json
Kategorya:Biyolohiya .json
Kategorya:Pilosopiya .json
Buwan-(panahon) .json
Kategorya:Sikolohiya .json
Kategorya:Sayaw .json
Kategorya:Awit .json
Wikang-Opisyal .json
Dagat .json
Kategorya:Dagat .json
Kategorya:Taon .json
Dagat-ng-Pilipinas .json
Aklatan .json
Kontinente .json
Dahomey .json
Kategorya:Kimika .json
Romania .json
Kategorya:Mitolohiya .json
Sustansiya .json
Digmaan-ng-Lapland .json
Pinlándiya .json
Kategorya:Ikalawang-Digmaang-Pandaigdig .json
Kategorya:Alemanya .json
Kategorya:Dahomey .json
Kategorya:Asya .json
Marso-21 .json
Benin .json
Kategorya:Benin .json
1685 .json
Hulyo-28 .json
1750 .json
Ludwig-van-Beethoven .json
Beethoven .json
Marso-26 .json
1827 .json
Wolfgang-Amadeus-Mozart .json
1791 .json
1756 .json
Mozart .json
Richard-Wagner .json
Linus-Torvalds .json
Mayo-22 .json
Ponema .json
Buto-(anatomiya) .json
Ponemang-Di-Malayang-Nagpapalitan .json
Tayutay .json
Oktubre .json
Pisyolohiya .json
San-Francisco .json
EBay .json
Frisco .json
Marso-3 .json
Karapatang-Ari .json
Marso-2 .json
Marso-4 .json
Marso-5 .json
Marso-6 .json
Marso-7 .json
Marso-8 .json
Marso-10 .json
Marso-9 .json
Marso-11 .json
Marso-13 .json
Marso-12 .json
Marso-14 .json
Marso-15 .json
Marso-16 .json
Marso-17 .json
Marso-18 .json
Marso-19 .json
Marso-20 .json
Marso-22 .json
Marso-24 .json
Pasko-ng-Muling-Pagkabuhay .json
Pasko .json
Araw-ng-mga-Puso .json
Zuma .json
Darna .json
Balikbayan .json
Saranggola .json
Talaan-ng-mga-unibersidad-at-kolehiyo-sa-Pilipinas .json
Google .json
Saligang-Batas-ng-Pilipinas .json
Pasko-Ng-Pagkabuhay .json
Pag-ibig .json
Araw-Ng-Mga-Puso .json
Pamantasan .json
Abril .json
Agosto .json
Mayo-2005 .json
Kevin-Carter .json
Linggo-ng-Pagkabuhay .json
Hesus .json
Talaarawan .json
Jesus .json
Papa-Juan-Pablo-II .json
Beatipikasyon .json
Pedro-Calungsod .json
Mapalad-na-Pedro-Calungsod .json
Talaksan:PedroCalungsod.jpg .json
Pangulong-Gloria-Macapagal-Arroyo .json
IOANNES-PAULUS-PP.-II .json
Tala-ng-mga-pariralang-Latin .json
Diyos .json
Ab-imo-pectore .json
Ab-incunabulis .json
Absente-reo .json
Absit-invidia .json
Ab-initio .json
A-capite-ad-calcem .json
A-cruce-salus .json
Acte-est-fabula .json
Anno-Domini .json
Ad-absurdum .json
Ad-hominem .json
Addendum .json
Ad-infinitum .json
Ad-interim .json
Advocatus-diaboli .json
Agnus-Dei .json
Ad-lib .json
Adsum .json
Kordero-ng-Diyos-(awit) .json
Alyas .json
Alibi .json
Palayaw .json
Alma-mater .json
Alter-ego .json
Ante-meridiem .json
A-posteriori .json
A-posse-ad-esse .json
Amicus-curiae .json
A-priori .json
Ars-gratia-artis .json
Aba-Ginoong-Maria .json
Artium-magister .json
Ave-atque-vale .json
Artium-baccalaureus .json
Ave-Maria .json
Lucas-ang-Ebanghelista .json
Ama-Namin .json
Katoliko .json
Kongreso .json
Kagawarang-Panghukuman-(Pilipinas) .json
Komisyon-sa-Wikang-Filipino .json
Yehey! .json
ABS-CBN-Corporation .json
Talaksan:Yeheylogo-RGB.gif .json
Talaksan:Logosall.jpg .json
INQ7-Interactive-Inc .json
Xoom .json
Talaksan:Xoom.gif .json
PayPal .json
Leksikograpiya .json
Triglyceride .json
Trayglisirayd .json
Molikyula .json
Bayolohiya .json
Pulitika .json
Talaksan:Logo-friendster-small.gif .json
Huling-Paalam .json
Pope-John-Paul-II .json
Karol-Wojtyla .json
Friendster .json
University-of-the-Philippines .json
Ab-aeterno .json
Cambodia .json
Vox-populi,-vox-dei .json
Wikipedia:Istab .json
Pater-Noster .json
Vox-populi .json
Kategorya:Ensiklopedya .json
Yahoo! .json
Kaluban .json
Titi .json
Tamod-(pluido) .json
Pagsasalsal .json
Hentai .json
Pagtutuli-kay-Hesus .json
Fulgencio-ng-Ruspe .json
Giuseppe-Maria-Tomasi .json
Unang-Digmaang-Pandaigdig .json
Pagkalasing .json
Pagjajakol .json
Talaksan:Enric-Valor-i-Vives.jpg .json
Enric-Valor-i-Vives .json
Ponemang-Malayang-Nagpapalitan .json
Kategorya:Espanya .json
Abril-19 .json
Papuri .json
HTML .json
HTTP .json
Tatak .json
Bakla .json
Talaan-ng-mga-institusyong-pang-edukasyon-na-Heswita-sa-Pilipinas .json
Talaksan:Logo200407.gif .json
Technorati .json
Isda .json
Zamboanga-Sibugay .json
Wikipedia:Tala-ng-mga-paksa-sa-anatomiya .json
Radyo-Veritas .json
Puson .json
Puwang-sa-puson .json
Abdominal-thrust-manuever .json
Puwang-sa-puson-at-balakang .json
Abduksiyon .json
Absorpsiyon .json
Abseso .json
Katayuan-ng-pagiging-higop .json
Asetabulum .json
Asetilkolina .json
Achalasia .json
Asidosis .json
Asido .json
Acidemia .json
Akustik .json
Acini .json
AIDS .json
Acrosome .json
Actin .json
Gitara .json
Uhog .json
Talaan-ng-mga-santo-ng-Simbahang-Katoliko .json
Agham-pang-aklatan-at-pang-impormasyon .json
Aklatan-at-agham-pang-impormasyon .json
Agham-Pang-aklatan-at-Pang-Impormasyon .json
Vic-Zhou .json
Kautusang-Tagapagpaganap-Blg.-343 .json
Kategorya:Agham-pang-aklatan-at-pang-impormasyon .json
Panunumpa-sa-Watawat .json
Blogger .json
TCP .json
Padron:Ilipat-sa-Wikisource .json
Kategorya:Ilipat-sa-Wikisource .json
B .json
A .json
C .json
D .json
E .json
F .json
G .json
Sustansiyang-kimikal .json
Abríl .json
Linggo .json
Padron:Abríl .json
Linggo-(panahon) .json
Linggo-(araw) .json
Kategorya:Araw-(panahon) .json
Kategorya:Panahon .json
Araw .json
Sabado .json
Padron:Araw-ng-linggo .json
Araw-(panahon) .json
Miyerkules .json
Martes .json
Austria .json
Brunei .json
Swisa .json
Andorra .json
Republikang-Tseko .json
Holland .json
Bosnia-at-Herzegovina .json
Afghanistan .json
Kyrgyzstan .json
Kazakhstan .json
Tajikistan .json
Lithuania .json
Kategorya:Korea .json
Kategorya:Palau .json
Kategorya:Taiwan .json
Padron:CIS .json
Biyernes .json
2005 .json
Huwebes .json
Disyembre .json
Pebrero-30 .json
Kategorya:Lithuania .json
Australia .json
Bahamas .json
Antigua .json
Ireland .json
Hong-Kong .json
Noruwega .json
Israel .json
Argentina .json
Bolivia .json
Chile .json
Paraguay .json
Uruguay .json
Aruba .json
Republika-ng-Ireland .json
Tala-ng-mga-papa-ng-Simbahang-Katoliko-Romano .json
Brunei-Darussalam .json
Wika-sa-Pilipinas .json
Albanya .json
Wikang-pampanitikan .json
Balbal .json
Lalawiganin .json
Wikang-pambansa .json
Rehistro-(sosyolingguwistika) .json
Kalamnan .json
Senepa .json
Perimysium .json
Setyembre .json
Marso-31 .json
Marso-25 .json
Talaan-ng-mga-anime .json
Lahat-ng-mga-Anime .json
Sistemang-nerbiyos .json
Botanika .json
Open-Source .json
Electronic-mail .json
FTP .json
Elektronikong-liham .json
Susing-salita .json
Entomolohiya .json
File-Transfer-Protocol .json
Unibersidad-ng-Pilipinas,-Diliman .json
Etolohiya .json
Anatomy .json
Embriyolohiya .json
Ecology .json
Anthropology .json
Embryology .json
Entomology .json
Physiology .json
Maneobrang-Heimlich .json
Santiago-de-Compostela .json
Nana .json
Operating-system .json
Aksesoring-litid .json
Database .json
GNU .json
Datos .json
Papa-Benedicto-XVI .json
Padron:Interwikiconflict .json
Wikipedia:Template:Interwikiconflict .json
Karol-Józef-Wojtyła .json
Karol-Wojtyła .json
Joseph-Ratzinger .json
Joseph-Alois-Ratzinger .json
Ratzinger .json
Luteranismo .json
Aba-Ginoong-María .json
Jesús .json
San-Lucas .json
Lutuing-Italyano .json
Estado-ng-Lungsod-ng-Batikano .json
Paglagari .json
Kategorya:Parusang-kamatayan .json
Kategorya:Pangunahing-paksa-sa-etika .json
Kategorya:Etika .json
Kategorya:Tortura .json
United-Kingdom .json
Gran-Bretanya .json
Gran-Bretaña .json
Filipinas-(paglilinaw) .json
Gran-Britanya .json
UK .json
Britanya .json
Bretaña .json
Dakilang-Bretanya .json
Arhentina .json
Brazil .json
Kemistri .json
Paragway .json
Kategorya:Rusya .json
Aborsyon .json
Palabaybayan-ng-Filipino .json
Rusya .json
Wikang-Yidis .json
San-Miguel-Corporation .json
James-Ingram .json
Bideoke .json
Senti .json
Kategorya:Musikang-soul .json
Calabarzon .json
DeBarge .json
MIMAROPA .json
Wikang-French .json
Ariel-Sharon .json
Kategorya:Israel .json
Kirguizstan .json
Republika-Tseka .json
Czech-Republic .json
Litwanya .json
Latvya .json
Latbiya .json
Singgapor .json
Irlanda-(pulo) .json
Republika-ng-Irlanda .json
Ayrland-(pulo) .json
Ayrland .json
Slovakia .json
Vatikan .json
Jose-Mario-Tomasi .json
Rick-Astley .json
Serbiya-at-Montenegro .json
Kategorya:Hilagang-Amerika .json
Kategorya:Estados-Unidos .json
San-Francisco,-California .json
Kategorya:Timog-Amerika .json
CcTLD .json
Bossa-nova .json
Kawalan-ng-maisusulat .json
Liechtenstein .json
Makamundong-pagsasarili .json
Kategorya:Masturbasyon .json
Kategorya:Pamilya-ng-mga-wikang-Slavonic .json
Wikang-Eslabo .json
Kategorya:Pambansang-awit .json
Kategorya:Pambansang-sagisag .json
Kategorya:Montenegro .json
Padron:Wikipedia's-sister-projects .json
Kategorya:Republika-Srpska .json
Cctld .json
Pambansang-domeyn-sa-pinakamataas-na-antas .json
Country-code-top-level-domain .json
Country-code-top-level-domains .json
Kategorya:Pamilya-ng-mga-wikang-Gitnang-Filipino .json
Kategorya:Pamilya-ng-mga-wikang-Awstronesyo .json
Kategorya:Pamilya-ng-mga-wikang-Malayopolinesyo .json
Kategorya:Pamilya-ng-mga-wikang-Kanlurang-Malayopolinesyo .json
Habemvs-papam .json
Aliterasyon .json
Anadiplosis .json
Anaphora .json
Kategorya:Wikang-Filipino .json
Anastrophe .json
Antimetabole .json
Antithesis .json
Aposiopesis .json
Aposisyon .json
Germany .json
Antigua-at-Barbuda .json
Metro-Manila .json
Kategorya:Antigua-at-Barbuda .json
Netherlands .json
Antigua-and-Barbuda .json
DLSU-M .json
De-La-Salle-University---Manila .json
Pamantasang-De-La-Salle .json
Inghenyeriya .json
Juan-Bautista-de-la-Salle .json
Juan-Bautista-ng-La-Salle .json
Wikipedia:Listahan-ng-mga-pahinang-kailangan-ilipat .json
Moto .json
De-La-Salle-Philippines .json
Brown-dwarf .json
2M1207b .json
Planetang-ekstrasolar .json
Exoplanet .json
Extrasolar-planet .json
Abril-2005 .json
Pag-atake-ng-terorista-sa-Cairo,-Abril-2005 .json
Current-events .json
Padron:Kasalukuyan .json
Kategorya:Kasalukuyang-pangyayari .json
Cairo .json
Iskala-mayor .json
Extrasolar .json
Azerbaijan .json
Armenia .json
Kategorya:Pelikula .json
Web-browser .json
Donald-Knuth .json
Albert-Einstein .json
Random-access-memory .json
Java-(wikang-pamprograma) .json
PHP .json
Naciones-Unidas-(UN) .json
Naciones-Unidas .json
Algoritmo .json
Marso-27 .json
Marso-28 .json
Marso-29 .json
Marso-30 .json
Padron:Europa .json
Birolohiya .json
Unibersidad-ng-Santo-Tomas .json
ACh .json
Pus .json
Abcess .json
Abscess .json
Abdominal-thrust .json
Biyokimika .json
Mikrobiyolohiya .json
Kategorya:Ilipat-sa-Wiktionary .json
Biochemistry .json
Inhinyeriyang-mekanikal .json
Wikipedia:Puntahan-ng-pamayanan .json
Acid .json
Buwan .json
Unang-Pahina .json
Kategorya:Buwan-(panahon) .json
Wikipedia:All-pages-by-title .json
HomePage .json
Wikipedia:Most-wanted-articles .json
Wikipedia .json
Wikipedia:Paano-baguhin-ang-isang-pahina .json
Wiki .json
Wikipedia:Upload-log .json
MediaWiki:Category .json
MediaWiki:Category-header .json
MediaWiki:Aboutpage .json
MediaWiki:Sitesupport .json
MediaWiki:Helppage .json
Padron:Sitesupportpage .json
MediaWiki:Cancel .json
MediaWiki:Qbbrowse .json
MediaWiki:Qbedit .json
MediaWiki:Qbpageinfo .json
MediaWiki:Qbspecialpages .json
MediaWiki:Mypage .json
MediaWiki:Mytalk .json
MediaWiki:Currentevents .json
MediaWiki:Returnto .json
MediaWiki:Disclaimerpage .json
MediaWiki:Whatlinkshere .json
MediaWiki:Fromwikipedia .json
MediaWiki:Search .json
MediaWiki:Editthispage .json
MediaWiki:Go .json
MediaWiki:Deletethispage .json
MediaWiki:Postcomment .json
MediaWiki:Articlepage .json
MediaWiki:Lastmodified .json
MediaWiki:Redirectedfrom .json
Padron:Gnunote .json
MediaWiki:Developertext .json
MediaWiki:Sitesubtitle .json
MediaWiki:Newmessages .json
MediaWiki:Newmessageslink .json
MediaWiki:Badarticleerror .json
MediaWiki:Cannotdelete .json
MediaWiki:Cachederror .json
MediaWiki:Badtitle .json
MediaWiki:Badtitletext .json
MediaWiki:Viewsource .json
MediaWiki:Yourpassword .json
MediaWiki:Yourname .json
MediaWiki:Yourpasswordagain .json
MediaWiki:Newusersonly .json
MediaWiki:Remembermypassword .json
MediaWiki:Alreadyloggedin .json
MediaWiki:Loginprompt .json
MediaWiki:Userlogin .json
MediaWiki:Userlogout .json
MediaWiki:Logout .json
MediaWiki:Youremail .json
MediaWiki:Createaccountmail .json
MediaWiki:Yournick .json
MediaWiki:Emailforlost .json
MediaWiki:Loginsuccess .json
MediaWiki:Nosuchuser .json
MediaWiki:Wrongpassword .json
MediaWiki:Summary .json
MediaWiki:Mailmypassword .json
MediaWiki:Minoredit .json
MediaWiki:Watchthis .json
MediaWiki:Blockedtitle .json
MediaWiki:Accmailtext .json
MediaWiki:Newarticletext .json
MediaWiki:Editing .json
MediaWiki:Currentrev .json
MediaWiki:Difference .json
MediaWiki:Copyrightwarning .json

     author author_id  ...     revision_id                       title
0                2510  ...                         Ingles (paglilinaw)
1                  38  ...                     Araling pangkapaligiran
2              105579  ...                                 Panggagamot
3               32119  ...                                 Arkitektura
4                      ...  49.144.138.181              Transportasyon
...     ...       ...  ...             ...                         ...
1379                   ...  110.54.145.254                 Agrikultura
1380               38  ...                                  Pagbubukid
1381                   ...  101.127.109.23                 Anyong lupa
1382            84769  ...                  Mga lalawigan ng Pilipinas
1383            92076  ...                                Ilocos Norte

[1384 rows x 7 columns]

In [ ]:
df[["full_article"]].head(2).style

# Preprocessing

In [ ]:
#sample = df["full_article"].iloc[0]
#sample

In [ ]:
def clean_wikipedia(text):
  result = str(text)
  result = re.sub(r"<ref>.*</ref>","",result)
  result = re.sub(r"[A-z]+=\".+\"", "", result)
  result = re.sub(r"<small>.*</small>","",result)
  result = re.sub(r"<.+?>", "", result)
  result = re.sub(r"{{.*}}", "", result)
  result = re.sub(r"{{[\S\s]*}}", "", result)
  result = re.sub(r"\[.*\]", "", result)
  result = re.sub(r"\(.*\)", "", result)
  result = re.sub(r"'+","",result)
  result = re.sub(r"=|\*|\(|\)","",result)
  result = re.sub(r"^#REDIRECT(\s)*","",result)
  # result = re.sub(r"\*","",result)
  return result

In [ ]:
def clean_text_general(text):
    result = str(text)
    result = re.sub(r"([^\s\.,?!]*(\d+,+)*(\d+\.+)?\d+[^\s\.,?!]*)", "", result)
    result = re.sub(r"(\S*_\S*)+", "", result)
    result = re.sub(r"#\S+", "", result)
    result = re.sub(r"https?:\/\/\S*", "", result)
    result = re.sub(r"(\w*\.)+(com|net|org|co|us|ph)(\/\w*)*", "", result)
    result = re.sub(r"-(?!\w)|(?<!\w)-", "", result)
    result = re.sub(r"([.]+)+", ".", result)
    result = re.sub(r"\s+\.\s+", ". ", result)
    result = re.sub(r"\s\s+", " ", result)
    result = re.sub(r"(\[(.*?)\])|(\{(.*?)\})|(\((.*?)\))", "", result)   
    result = re.sub(r"[^a-zA-Z0-9\-\s\.!,?\[\]\(\)Ññ]", "", result)
    result = re.sub(r"\((.*?)\)", "", result)
    result = re.sub(r"\[(.*?)\]", "", result)
    result = re.sub(r"", "", result)
    result = re.sub(r"", "", result)

    return result.strip()

In [ ]:
res = clean_text_general(clean_wikipedia("#REDIRECT [[ekolohiya]]"))
print(res)

In [ ]:
df["new_article"] = df["full_article"].apply(lambda text: clean_text_general(clean_wikipedia(text)))

In [ ]:
df.head(5)

  author  ...                                        new_article
0         ...  Ang Ingles ay maaaring tumukoy sa mga sumusuno...
1         ...
2         ...  Ang panggagamot o medisina ay sangay ng. ng mg...
3         ...  Ang arkitektura ay ang pamamaraan at produkto ...
4         ...  Ang transportasyon na trans, na nangangahuluga...

[5 rows x 8 columns]

In [ ]:
df.drop(["author", "author_id", "author_ip", "revision_id", "full_article"], axis='columns', inplace=True)

In [ ]:
df.rename(columns={'new_article': 'text'}, inplace=True)
df

                      date  ...                                               text
0     2013-05-21T12:56:32Z  ...  Ang Ingles ay maaaring tumukoy sa mga sumusuno...
1     2004-11-02T04:12:52Z  ...
2     2020-07-29T10:03:20Z  ...  Ang panggagamot o medisina ay sangay ng. ng mg...
3     2019-02-18T15:14:55Z  ...  Ang arkitektura ay ang pamamaraan at produkto ...
4     2021-03-17T13:28:20Z  ...  Ang transportasyon na trans, na nangangahuluga...
...                    ...  ...                                                ...
1379  2021-04-24T05:10:46Z  ...  Ang agrikultura ay ang paglinang at pagpaparam...
1380  2017-02-21T10:02:04Z  ...
1381  2020-05-29T06:57:30Z  ...  Sa at iba pa, kabilang ang mga kalupaang nasa ...
1382  2021-04-09T05:50:35Z  ...  Ang , pati ang mga malayang nakapaloob na lung...
1383  2018-09-16T09:14:45Z  ...  Ang Ilocos Norte. Kilala ang lalawigan bilang ...

[1384 rows x 3 columns]

In [ ]:
df.head(5)

                   date  ...                                               text
0  2013-05-21T12:56:32Z  ...  Ang Ingles ay maaaring tumukoy sa mga sumusuno...
1  2004-11-02T04:12:52Z  ...
2  2020-07-29T10:03:20Z  ...  Ang panggagamot o medisina ay sangay ng. ng mg...
3  2019-02-18T15:14:55Z  ...  Ang arkitektura ay ang pamamaraan at produkto ...
4  2021-03-17T13:28:20Z  ...  Ang transportasyon na trans, na nangangahuluga...

[5 rows x 3 columns]

In [ ]:
# df['date'] = df['date'].apply(lambda date: datetime.fromisoformat(date)
# df['date'] = df['date'].apply(lambda date: date.to_pydatetime())
df['date'] = df['date'].apply(lambda date: datetime.fromisoformat(date[:-1]).strftime('%Y-%m-%d %H:%M:%S'))

In [ ]:
df.head(5)

                  date  ...                                               text
0  2013-05-21 12:56:32  ...  Ang Ingles ay maaaring tumukoy sa mga sumusuno...
1  2004-11-02 04:12:52  ...
2  2020-07-29 10:03:20  ...  Ang panggagamot o medisina ay sangay ng. ng mg...
3  2019-02-18 15:14:55  ...  Ang arkitektura ay ang pamamaraan at produkto ...
4  2021-03-17 13:28:20  ...  Ang transportasyon na trans, na nangangahuluga...

[5 rows x 3 columns]

In [ ]:
df.sort_values(by="date", inplace=True)

In [ ]:
df.head(5)

                     date  ...                                               text
856   2004-01-25 16:56:06  ...
887   2004-01-29 11:59:53  ...  All text is available under the terms of the G...
866   2004-01-29 11:59:53  ...                                ltsitesupportpagegt
1084  2004-03-21 09:51:09  ...  Ang pulo o isla ay isang bahagi ng lupa na hig...
863   2004-03-22 15:11:18  ...                                 WikipediaPatungkol

[5 rows x 3 columns]

In [ ]:
# remove empty articles?
df = df.loc[df['text'] != ""]

In [ ]:
colons = df[df['title'].str.contains('[A-za-z]*:', na=False)]
df = df.drop(colons.index)
df

                     date  ...                                               text
1084  2004-03-21 09:51:09  ...  Ang pulo o isla ay isang bahagi ng lupa na hig...
1308  2004-09-08 14:43:24  ...  Si Zoran ini   sa. Ipinanganak si ini sa. Bila...
1307  2004-09-08 14:44:01  ...  Si Zoran ini   sa. Ipinanganak si ini sa. Bila...
1318  2004-09-10 20:12:25  ...                Para sa munisipalidad, silipin ang.
1319  2004-09-10 20:13:08  ...                Para sa munisipalidad, silipin ang.
...                   ...  ...                                                ...
251   2021-05-29 07:09:22  ...  Isang ang natitirang apatnaput walo. Pareho di...
686   2021-05-29 09:49:55  ...     Ang Santiago de Compostela ang kabisera ng ng.
732   2021-05-30 05:37:41  ...  Ang bideoke , minsan kasama ng pag-iiba-iba ng...
958   2021-05-30 21:22:10  ...  Ang makina ay isang mekanikal o de-kuryenteng ...
8     2021-05-31 17:01:02  ...  Ang teknolohiya o aghimuan. Kadalasang iniuugn...

[901 rows x 3 columns]

# Save Data

In [ ]:
target_directory = "/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/"

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [ ]:
df['year_month'] = df["date"].apply(lambda date: str(date.year) + "-" + str('%02d' % date.month))
df

                    date  ... year_month
1084 2004-03-21 09:51:09  ...    2004-03
1308 2004-09-08 14:43:24  ...    2004-09
1307 2004-09-08 14:44:01  ...    2004-09
1318 2004-09-10 20:12:25  ...    2004-09
1319 2004-09-10 20:13:08  ...    2004-09
...                  ...  ...        ...
251  2021-05-29 07:09:22  ...    2021-05
686  2021-05-29 09:49:55  ...    2021-05
732  2021-05-30 05:37:41  ...    2021-05
958  2021-05-30 21:22:10  ...    2021-05
8    2021-05-31 17:01:02  ...    2021-05

[901 rows x 4 columns]

In [ ]:
dates = df.groupby(by='year_month')

In [ ]:
for date in dates:
  print(date)

('2004-03',                     date  ... year_month
1084 2004-03-21 09:51:09  ...    2004-03

[1 rows x 4 columns])
('2004-09',                     date  ... year_month
1308 2004-09-08 14:43:24  ...    2004-09
1307 2004-09-08 14:44:01  ...    2004-09
1318 2004-09-10 20:12:25  ...    2004-09
1319 2004-09-10 20:13:08  ...    2004-09

[4 rows x 4 columns])
('2004-11',                     date  ... year_month
43   2004-11-09 13:39:33  ...    2004-11
1101 2004-11-13 10:54:49  ...    2004-11
80   2004-11-20 14:56:44  ...    2004-11

[3 rows x 4 columns])
('2004-12',                    date  ... year_month
131 2004-12-07 05:59:11  ...    2004-12

[1 rows x 4 columns])
('2005-01',                    date  ... year_month
201 2005-01-13 05:05:23  ...    2005-01

[1 rows x 4 columns])
('2005-02',                    date  ... year_month
246 2005-02-12 17:48:03  ...    2005-02
250 2005-02-12 18:33:28  ...    2005-02
249 2005-02-12 18:40:45  ...    2005-02
260 2005-02-13 14:53:25  ...    2005-02
283 2005-02-15 09:46:08  ...    2005-02
286 2005-02-15 09:49:00  ...    2005-02
285 2005-02-15 09:49:41  ...    2005-02
289 2005-02-17 02:12:06  ...    2005-02
305 2005-02-19 20:13:35  ...    2005-02
306 2005-02-19 20:14:31  ...    2005-02
307 2005-02-21 02:37:27  ...    2005-02
309 2005-02-21 03:59:57  ...    2005-02
310 2005-02-21 04:50:22  ...    2005-02
336 2005-02-26 17:33:04  ...    2005-02

[14 rows x 4 columns])
('2005-03',                    date  ... year_month
345 2005-03-06 10:51:48  ...    2005-03
352 2005-03-06 11:31:50  ...    2005-03
391 2005-03-07 12:07:22  ...    2005-03
397 2005-03-07 13:04:51  ...    2005-03
444 2005-03-11 16:15:41  ...    2005-03
528 2005-03-13 10:12:14  ...    2005-03
545 2005-03-13 11:57:42  ...    2005-03
403 2005-03-13 12:12:39  ...    2005-03
583 2005-03-27 08:51:23  ...    2005-03
584 2005-03-27 08:52:37  ...    2005-03
601 2005-03-31 15:53:42  ...    2005-03

[11 rows x 4 columns])
('2005-04',                    date  ... year_month
680 2005-04-16 07:42:36  ...    2005-04
682 2005-04-16 07:45:32  ...    2005-04
683 2005-04-16 07:51:49  ...    2005-04
684 2005-04-16 08:05:39  ...    2005-04
792 2005-04-29 08:22:49  ...    2005-04
797 2005-04-29 10:30:20  ...    2005-04

[6 rows x 4 columns])
('2005-05',                    date  ... year_month
841 2005-05-20 15:02:54  ...    2005-05
840 2005-05-20 15:09:12  ...    2005-05
850 2005-05-21 07:39:53  ...    2005-05

[3 rows x 4 columns])
('2005-07',                    date  ... year_month
276 2005-07-16 16:24:18  ...    2005-07
245 2005-07-22 14:09:43  ...    2005-07
366 2005-07-22 14:23:59  ...    2005-07

[3 rows x 4 columns])
('2005-08',                     date  ... year_month
1359 2005-08-16 01:21:59  ...    2005-08
139  2005-08-16 01:22:31  ...    2005-08
675  2005-08-16 01:23:55  ...    2005-08

[3 rows x 4 columns])
('2006-03',                    date  ... year_month
726 2006-03-07 09:59:12  ...    2006-03

[1 rows x 4 columns])
('2006-08',                    date  ... year_month
754 2006-08-05 07:06:15  ...    2006-08
463 2006-08-05 07:39:46  ...    2006-08
464 2006-08-05 07:39:53  ...    2006-08
467 2006-08-05 07:39:59  ...    2006-08
465 2006-08-05 07:40:06  ...    2006-08
466 2006-08-05 07:40:12  ...    2006-08
468 2006-08-05 07:40:18  ...    2006-08
469 2006-08-05 07:40:24  ...    2006-08
470 2006-08-05 07:40:35  ...    2006-08
471 2006-08-05 07:40:42  ...    2006-08
472 2006-08-05 07:40:48  ...    2006-08
474 2006-08-05 07:40:55  ...    2006-08
475 2006-08-05 07:41:06  ...    2006-08
476 2006-08-05 07:41:12  ...    2006-08
479 2006-08-05 07:41:19  ...    2006-08
480 2006-08-05 07:41:25  ...    2006-08
477 2006-08-05 07:41:30  ...    2006-08
483 2006-08-05 07:41:37  ...    2006-08
486 2006-08-05 07:41:48  ...    2006-08
487 2006-08-05 07:41:55  ...    2006-08
490 2006-08-05 07:42:03  ...    2006-08
489 2006-08-05 07:42:08  ...    2006-08
492 2006-08-05 07:42:17  ...    2006-08
496 2006-08-05 07:42:28  ...    2006-08
494 2006-08-05 07:42:45  ...    2006-08
495 2006-08-05 07:42:56  ...    2006-08
524 2006-08-05 07:43:04  ...    2006-08

[27 rows x 4 columns])
('2006-12',                    date  ... year_month
497 2006-12-28 08:24:36  ...    2006-12

[1 rows x 4 columns])
('2008-05',                    date  ... year_month
966 2008-05-09 09:20:02  ...    2008-05
198 2008-05-23 22:23:47  ...    2008-05

[2 rows x 4 columns])
('2008-07',                     date  ... year_month
1310 2008-07-27 21:58:26  ...    2008-07
256  2008-07-28 00:21:16  ...    2008-07
542  2008-07-28 00:28:16  ...    2008-07
765  2008-07-28 00:28:48  ...    2008-07
84   2008-07-28 01:19:50  ...    2008-07
666  2008-07-28 01:23:32  ...    2008-07
215  2008-07-28 01:31:21  ...    2008-07

[7 rows x 4 columns])
('2008-09',                    date  ... year_month
839 2008-09-16 19:52:14  ...    2008-09
302 2008-09-22 00:31:58  ...    2008-09
843 2008-09-26 21:48:26  ...    2008-09

[3 rows x 4 columns])
('2008-11',                    date  ... year_month
802 2008-11-28 03:28:36  ...    2008-11

[1 rows x 4 columns])
('2009-01',                    date  ... year_month
247 2009-01-09 22:31:44  ...    2009-01

[1 rows x 4 columns])
('2009-03',                    date  ... year_month
253 2009-03-17 06:50:40  ...    2009-03

[1 rows x 4 columns])
('2009-04',                    date  ... year_month
523 2009-04-03 18:07:57  ...    2009-04

[1 rows x 4 columns])
('2010-02',                    date  ... year_month
750 2010-02-25 08:08:59  ...    2010-02

[1 rows x 4 columns])
('2011-02',                    date  ... year_month
263 2011-02-02 04:09:20  ...    2011-02
264 2011-02-02 04:09:30  ...    2011-02
267 2011-02-02 04:09:37  ...    2011-02
265 2011-02-02 04:09:45  ...    2011-02
266 2011-02-02 04:09:53  ...    2011-02

[5 rows x 4 columns])
('2012-02',                    date  ... year_month
244 2012-02-07 09:51:56  ...    2012-02
242 2012-02-07 09:52:06  ...    2012-02

[2 rows x 4 columns])
('2012-07',                    date  ... year_month
665 2012-07-02 17:35:54  ...    2012-07

[1 rows x 4 columns])
('2012-08',                    date  ... year_month
768 2012-08-11 07:35:19  ...    2012-08

[1 rows x 4 columns])
('2012-09',                    date  ... year_month
516 2012-09-01 11:58:08  ...    2012-09
723 2012-09-05 01:51:48  ...    2012-09

[2 rows x 4 columns])
('2013-01',                    date  ... year_month
699 2013-01-14 07:03:28  ...    2013-01
698 2013-01-14 07:03:38  ...    2013-01
460 2013-01-14 14:19:44  ...    2013-01
521 2013-01-14 14:20:54  ...    2013-01
697 2013-01-14 14:21:04  ...    2013-01
696 2013-01-14 14:21:14  ...    2013-01
520 2013-01-14 14:24:18  ...    2013-01

[7 rows x 4 columns])
('2013-03',                     date  ... year_month
1155 2013-03-07 18:05:40  ...    2013-03
1159 2013-03-07 18:06:53  ...    2013-03
1160 2013-03-07 18:08:02  ...    2013-03
1164 2013-03-07 18:08:58  ...    2013-03
1167 2013-03-07 18:10:07  ...    2013-03
...                  ...  ...        ...
447  2013-03-11 10:46:47  ...    2013-03
553  2013-03-11 10:50:49  ...    2013-03
803  2013-03-11 10:51:10  ...    2013-03
538  2013-03-28 10:30:42  ...    2013-03
515  2013-03-30 03:44:40  ...    2013-03

[84 rows x 4 columns])
('2013-04',                     date  ... year_month
473  2013-04-16 17:30:39  ...    2013-04
685  2013-04-21 22:31:19  ...    2013-04
13   2013-04-22 11:32:10  ...    2013-04
1080 2013-04-25 20:26:24  ...    2013-04
763  2013-04-30 01:01:09  ...    2013-04
687  2013-04-30 04:42:33  ...    2013-04
689  2013-04-30 07:26:55  ...    2013-04
679  2013-04-30 07:31:01  ...    2013-04
661  2013-04-30 07:39:32  ...    2013-04

[9 rows x 4 columns])
('2013-05',                    date  ... year_month
608 2013-05-21 12:54:53  ...    2013-05
0   2013-05-21 12:56:32  ...    2013-05
851 2013-05-21 13:03:03  ...    2013-05

[3 rows x 4 columns])
('2013-06',                     date  ... year_month
1279 2013-06-01 23:39:59  ...    2013-06
548  2013-06-02 18:50:48  ...    2013-06
1082 2013-06-15 07:25:23  ...    2013-06

[3 rows x 4 columns])
('2013-07',                    date  ... year_month
78  2013-07-05 05:35:58  ...    2013-07
257 2013-07-05 06:04:54  ...    2013-07
370 2013-07-08 12:27:07  ...    2013-07

[3 rows x 4 columns])
('2013-08',                     date  ... year_month
1343 2013-08-17 21:21:22  ...    2013-08
1357 2013-08-18 08:46:07  ...    2013-08
1251 2013-08-22 10:51:06  ...    2013-08
1249 2013-08-22 12:22:34  ...    2013-08
1247 2013-08-22 12:28:10  ...    2013-08
504  2013-08-24 09:19:19  ...    2013-08
805  2013-08-25 14:14:15  ...    2013-08

[7 rows x 4 columns])
('2013-09',                   date  ... year_month
15 2013-09-23 09:28:24  ...    2013-09

[1 rows x 4 columns])
('2013-10',                    date  ... year_month
602 2013-10-17 15:26:47  ...    2013-10

[1 rows x 4 columns])
('2013-11',                     date  ... year_month
1287 2013-11-02 00:45:05  ...    2013-11
720  2013-11-10 18:41:45  ...    2013-11
714  2013-11-10 18:42:59  ...    2013-11
713  2013-11-10 18:43:39  ...    2013-11
1223 2013-11-16 04:55:40  ...    2013-11

[5 rows x 4 columns])
('2013-12',                     date  ... year_month
59   2013-12-10 15:11:43  ...    2013-12
237  2013-12-11 16:52:52  ...    2013-12
1358 2013-12-13 17:32:14  ...    2013-12
990  2013-12-17 08:34:18  ...    2013-12
991  2013-12-17 08:34:50  ...    2013-12
1239 2013-12-17 08:36:02  ...    2013-12
1228 2013-12-18 09:37:11  ...    2013-12
982  2013-12-18 09:37:18  ...    2013-12
978  2013-12-18 09:37:25  ...    2013-12
1183 2013-12-24 17:47:00  ...    2013-12
128  2013-12-24 18:48:45  ...    2013-12
1253 2013-12-25 09:50:29  ...    2013-12
491  2013-12-25 15:12:55  ...    2013-12
567  2013-12-25 17:02:22  ...    2013-12
593  2013-12-25 18:54:16  ...    2013-12
29   2013-12-28 13:43:47  ...    2013-12
1275 2013-12-30 15:48:31  ...    2013-12
343  2013-12-30 16:55:00  ...    2013-12
281  2013-12-30 17:13:38  ...    2013-12

[19 rows x 4 columns])
('2014-01',                     date  ... year_month
1295 2014-01-18 16:25:24  ...    2014-01
1234 2014-01-18 18:04:52  ...    2014-01
188  2014-01-18 19:02:43  ...    2014-01
1317 2014-01-19 04:40:31  ...    2014-01

[4 rows x 4 columns])
('2014-02',                    date  ... year_month
742 2014-02-15 06:13:24  ...    2014-02
743 2014-02-15 06:13:31  ...    2014-02

[2 rows x 4 columns])
('2014-03',                    date  ... year_month
832 2014-03-26 02:01:45  ...    2014-03

[1 rows x 4 columns])
('2014-04',                   date  ... year_month
96 2014-04-25 02:19:09  ...    2014-04

[1 rows x 4 columns])
('2014-06',                    date  ... year_month
580 2014-06-06 11:01:22  ...    2014-06
529 2014-06-06 11:35:29  ...    2014-06
813 2014-06-06 12:41:25  ...    2014-06

[3 rows x 4 columns])
('2014-07',                    date  ... year_month
512 2014-07-04 17:11:52  ...    2014-07

[1 rows x 4 columns])
('2014-08',                     date  ... year_month
557  2014-08-04 13:06:38  ...    2014-08
1254 2014-08-11 10:04:17  ...    2014-08
1245 2014-08-11 13:04:13  ...    2014-08
565  2014-08-17 22:25:46  ...    2014-08
651  2014-08-22 13:32:49  ...    2014-08
571  2014-08-23 22:06:54  ...    2014-08
561  2014-08-30 03:46:14  ...    2014-08
1246 2014-08-31 16:14:12  ...    2014-08

[8 rows x 4 columns])
('2014-09',                     date  ... year_month
501  2014-09-05 05:04:44  ...    2014-09
206  2014-09-20 02:44:33  ...    2014-09
963  2014-09-21 09:58:39  ...    2014-09
1375 2014-09-21 10:03:23  ...    2014-09
1376 2014-09-21 10:03:36  ...    2014-09
94   2014-09-21 10:07:51  ...    2014-09
184  2014-09-21 10:10:15  ...    2014-09
239  2014-09-21 10:11:12  ...    2014-09
241  2014-09-21 10:11:24  ...    2014-09
243  2014-09-21 10:11:36  ...    2014-09
707  2014-09-21 10:17:28  ...    2014-09
86   2014-09-23 03:05:31  ...    2014-09
409  2014-09-27 00:28:53  ...    2014-09

[13 rows x 4 columns])
('2014-10',                     date  ... year_month
560  2014-10-02 13:45:55  ...    2014-10
1189 2014-10-06 00:34:50  ...    2014-10
568  2014-10-22 15:43:15  ...    2014-10

[3 rows x 4 columns])
('2014-11',                     date  ... year_month
1299 2014-11-09 05:14:11  ...    2014-11

[1 rows x 4 columns])
('2015-01',                    date  ... year_month
733 2015-01-24 04:27:13  ...    2015-01
741 2015-01-30 12:57:00  ...    2015-01

[2 rows x 4 columns])
('2015-02',                     date  ... year_month
1191 2015-02-07 18:04:21  ...    2015-02
158  2015-02-17 01:55:10  ...    2015-02
744  2015-02-19 18:27:38  ...    2015-02

[3 rows x 4 columns])
('2015-03',                     date  ... year_month
989  2015-03-16 03:51:17  ...    2015-03
103  2015-03-27 08:16:53  ...    2015-03
109  2015-03-27 08:17:05  ...    2015-03
137  2015-03-27 08:17:18  ...    2015-03
303  2015-03-27 08:21:14  ...    2015-03
404  2015-03-27 08:23:27  ...    2015-03
604  2015-03-27 08:26:59  ...    2015-03
668  2015-03-27 08:31:00  ...    2015-03
809  2015-03-27 08:34:45  ...    2015-03
845  2015-03-27 08:36:13  ...    2015-03
1178 2015-03-30 04:51:09  ...    2015-03
83   2015-03-31 02:21:35  ...    2015-03
341  2015-03-31 02:22:02  ...    2015-03
828  2015-03-31 02:23:51  ...    2015-03
663  2015-03-31 16:31:31  ...    2015-03

[15 rows x 4 columns])
('2015-07',                     date  ... year_month
498  2015-07-12 05:27:17  ...    2015-07
1268 2015-07-14 04:02:01  ...    2015-07
1283 2015-07-15 08:07:42  ...    2015-07
974  2015-07-15 08:08:40  ...    2015-07

[4 rows x 4 columns])
('2015-08',                    date  ... year_month
823 2015-08-04 05:18:40  ...    2015-08

[1 rows x 4 columns])
('2015-09',                     date  ... year_month
1199 2015-09-15 13:30:36  ...    2015-09

[1 rows x 4 columns])
('2015-10',                     date  ... year_month
718  2015-10-02 03:23:05  ...    2015-10
1202 2015-10-04 07:18:47  ...    2015-10
135  2015-10-20 06:58:48  ...    2015-10
1266 2015-10-21 02:38:11  ...    2015-10
701  2015-10-21 03:00:35  ...    2015-10

[5 rows x 4 columns])
('2015-11',                    date  ... year_month
339 2015-11-29 03:05:21  ...    2015-11

[1 rows x 4 columns])
('2015-12',                     date  ... year_month
844  2015-12-22 15:46:34  ...    2015-12
1222 2015-12-23 13:00:44  ...    2015-12

[2 rows x 4 columns])
('2016-02',                     date  ... year_month
1081 2016-02-06 13:43:55  ...    2016-02
438  2016-02-06 23:35:39  ...    2016-02
151  2016-02-24 08:43:18  ...    2016-02

[3 rows x 4 columns])
('2016-03',                    date  ... year_month
149 2016-03-04 13:38:00  ...    2016-03
508 2016-03-07 05:17:34  ...    2016-03

[2 rows x 4 columns])
('2016-04',                    date  ... year_month
101 2016-04-03 12:57:13  ...    2016-04
751 2016-04-18 12:50:02  ...    2016-04

[2 rows x 4 columns])
('2016-05',                     date  ... year_month
633  2016-05-06 15:49:46  ...    2016-05
446  2016-05-06 15:49:57  ...    2016-05
959  2016-05-06 15:50:10  ...    2016-05
1273 2016-05-06 15:51:29  ...    2016-05
157  2016-05-06 15:51:54  ...    2016-05
539  2016-05-06 15:52:21  ...    2016-05
10   2016-05-06 15:52:34  ...    2016-05
25   2016-05-06 15:52:37  ...    2016-05
19   2016-05-06 15:52:50  ...    2016-05
405  2016-05-06 15:53:33  ...    2016-05
18   2016-05-06 15:54:20  ...    2016-05
32   2016-05-06 15:54:53  ...    2016-05
9    2016-05-06 15:54:56  ...    2016-05
1297 2016-05-06 15:54:59  ...    2016-05
144  2016-05-06 15:55:07  ...    2016-05
1198 2016-05-06 15:55:49  ...    2016-05
1226 2016-05-06 15:56:36  ...    2016-05
1284 2016-05-06 15:57:35  ...    2016-05
1340 2016-05-06 15:59:13  ...    2016-05
400  2016-05-06 16:00:07  ...    2016-05
190  2016-05-06 16:00:25  ...    2016-05
186  2016-05-06 16:01:49  ...    2016-05
156  2016-05-06 16:01:56  ...    2016-05
192  2016-05-06 16:01:58  ...    2016-05
1161 2016-05-19 21:29:40  ...    2016-05
75   2016-05-22 03:49:11  ...    2016-05
351  2016-05-22 06:09:38  ...    2016-05
482  2016-05-25 08:22:06  ...    2016-05
987  2016-05-26 09:12:13  ...    2016-05

[29 rows x 4 columns])
('2016-06',                     date  ... year_month
71   2016-06-08 05:37:36  ...    2016-06
308  2016-06-10 10:41:58  ...    2016-06
1311 2016-06-19 12:16:09  ...    2016-06
62   2016-06-28 01:28:19  ...    2016-06

[4 rows x 4 columns])
('2016-07',                    date  ... year_month
146 2016-07-27 05:26:30  ...    2016-07
155 2016-07-27 05:30:07  ...    2016-07
189 2016-07-27 05:52:26  ...    2016-07
420 2016-07-27 06:39:10  ...    2016-07
421 2016-07-27 06:43:45  ...    2016-07
424 2016-07-27 09:12:15  ...    2016-07
427 2016-07-27 10:16:07  ...    2016-07
430 2016-07-27 11:04:50  ...    2016-07

[8 rows x 4 columns])
('2016-08',                     date  ... year_month
537  2016-08-07 07:55:14  ...    2016-08
1097 2016-08-24 08:05:09  ...    2016-08

[2 rows x 4 columns])
('2016-09',                     date  ... year_month
1370 2016-09-14 09:25:45  ...    2016-09

[1 rows x 4 columns])
('2016-10',                     date  ... year_month
431  2016-10-01 07:52:41  ...    2016-10
1271 2016-10-01 08:28:32  ...    2016-10
388  2016-10-01 09:47:04  ...    2016-10
674  2016-10-03 16:06:28  ...    2016-10
691  2016-10-04 05:53:02  ...    2016-10

[5 rows x 4 columns])
('2016-11',                    date  ... year_month
818 2016-11-05 11:48:26  ...    2016-11
425 2016-11-28 23:45:55  ...    2016-11

[2 rows x 4 columns])
('2016-12',                    date  ... year_month
423 2016-12-19 15:47:33  ...    2016-12

[1 rows x 4 columns])
('2017-01',                    date  ... year_month
408 2017-01-23 14:54:37  ...    2017-01
95  2017-01-31 08:55:48  ...    2017-01

[2 rows x 4 columns])
('2017-02',                    date  ... year_month
569 2017-02-17 09:38:42  ...    2017-02
654 2017-02-24 07:52:35  ...    2017-02

[2 rows x 4 columns])
('2017-03',                     date  ... year_month
1166 2017-03-06 16:07:39  ...    2017-03
1060 2017-03-24 10:26:37  ...    2017-03

[2 rows x 4 columns])
('2017-04',                     date  ... year_month
1218 2017-04-01 00:33:56  ...    2017-04
262  2017-04-03 13:51:00  ...    2017-04
175  2017-04-03 14:31:38  ...    2017-04
148  2017-04-06 20:18:33  ...    2017-04
23   2017-04-10 01:32:46  ...    2017-04
27   2017-04-10 02:06:22  ...    2017-04
22   2017-04-16 16:48:57  ...    2017-04
419  2017-04-18 06:07:16  ...    2017-04
1158 2017-04-30 13:13:24  ...    2017-04
1157 2017-04-30 13:16:30  ...    2017-04

[10 rows x 4 columns])
('2017-05',                     date  ... year_month
132  2017-05-02 11:00:16  ...    2017-05
1165 2017-05-03 12:57:29  ...    2017-05

[2 rows x 4 columns])
('2017-06',                     date  ... year_month
582  2017-06-23 16:50:42  ...    2017-06
1372 2017-06-23 17:06:08  ...    2017-06
808  2017-06-29 10:52:59  ...    2017-06
570  2017-06-29 10:58:43  ...    2017-06
578  2017-06-29 10:59:27  ...    2017-06
783  2017-06-29 11:06:41  ...    2017-06
544  2017-06-29 12:18:25  ...    2017-06
590  2017-06-29 14:30:45  ...    2017-06
784  2017-06-29 16:16:46  ...    2017-06
787  2017-06-29 16:17:02  ...    2017-06
788  2017-06-29 16:17:59  ...    2017-06
789  2017-06-29 16:18:07  ...    2017-06
790  2017-06-29 16:18:14  ...    2017-06
210  2017-06-29 16:46:18  ...    2017-06
511  2017-06-29 16:46:57  ...    2017-06
563  2017-06-29 16:49:40  ...    2017-06
45   2017-06-29 16:55:45  ...    2017-06

[17 rows x 4 columns])
('2017-07',                    date  ... year_month
488 2017-07-06 02:13:00  ...    2017-07
609 2017-07-22 17:32:03  ...    2017-07
605 2017-07-22 17:33:30  ...    2017-07
406 2017-07-30 02:31:36  ...    2017-07

[4 rows x 4 columns])
('2017-08',                     date  ... year_month
42   2017-08-04 15:31:15  ...    2017-08
1250 2017-08-08 11:13:44  ...    2017-08
499  2017-08-09 15:14:32  ...    2017-08
92   2017-08-29 06:46:25  ...    2017-08

[4 rows x 4 columns])
('2017-09',                    date  ... year_month

In [ ]:
for group in dates:
  year, month = group[0].split("-")
  path = target_directory + year + "/" + str(int(month)) + "/"
  print(path)
  if not os.path.exists(path):
    print("Does not exist!")
    os.makedirs(path)

  group[1].drop(["year_month"], axis='columns').to_json(path + str(int(month)) + ".json", orient="records")
  print("Done")
  # break #remove

/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2004/3/
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2004/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2004/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2004/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2005/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2006/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2006/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2006/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2008/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2008/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2008/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2008/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2009/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2009/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2009/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2010/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2011/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2012/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2012/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2012/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2012/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2013/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2014/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2015/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2016/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2017/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2018/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2019/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/5/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/6/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/7/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/8/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/9/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/10/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/11/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2020/12/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2021/1/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2021/2/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2021/3/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2021/4/
Does not exist!
Done
/content/drive/Shared drives/DOST FilWordNet x WordSense/Thesis/Data Collection/RAW_COHFIE/wikipedia/wikipedia/2021/5/
Does not exist!
Done