In [ ]:
!pip install google-api-python-client

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.7/dist-packages (1.12.8)
Requirement already satisfied: google-api-core<2dev,>=1.21.0 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (1.26.3)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (0.0.4)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (0.17.4)
Requirement already satisfied: google-auth>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (1.35.0)
Requirement already satisfied: six<2dev,>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from google-api-python-client) (1.15.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (1.53.0)
Requirement already satisfied: packaging>=14.3 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (21.3)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (2.23.0)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (3.17.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (2018.9)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client) (57.4.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.16.0->google-api-python-client) (4.2.4)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.16.0->google-api-python-client) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth>=1.16.0->google-api-python-client) (0.2.8)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=14.3->google-api-core<2dev,>=1.21.0->google-api-python-client) (3.0.6)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.16.0->google-api-python-client) (0.4.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.21.0->google-api-python-client) (1.24.3)

In [ ]:
# Put your API key here
#API_KEY = input('Enter API key: ')
API_KEY = 'AIzaSyBO81_7IykA9UrZjw3uSQcAv6F9_yXneHU'

In [ ]:
from googleapiclient.discovery import build
import json
import pandas as pd
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
script_link = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Youtube/scripts"
save_link = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/Data Collection/Raw Data/Youtube/data"
files = os.listdir(script_link)
files

['initiate_channels.ipynb',
 'RogerRaker.csv',
 'ranz_kyle.csv',
 'channels.csv',
 'Cong_TV.csv',
 'video_comments.ipynb',
 'add_channel.ipynb',
 'update_channels.ipynb']

In [ ]:
youtube = build('youtube','v3',developerKey=API_KEY)
max_videos = 50

#### 1.) Search the channel ID of the Channel & Get Uploads ID
- search here: https://commentpicker.com/youtube-channel-id.php#youtube-channel-id
- upload to channels.csv

revision: Iterate every channel title and ID to get Upload ID and corresponding videos.

In [ ]:
channels = pd.read_csv(script_link+'/channels.csv')
channels

                    channel_title  ...                 upload_id
0                         cong_tv  ...  UU73zqrs0Th_a9dFUivEmv2A
1                    slater_young  ...                       NaN
2                        kryzzzie  ...                       NaN
3              alodia_gosiengfiao  ...                       NaN
4                      rei_germar  ...                       NaN
..                            ...  ...                       ...
139       i_can_see_your_voice_ph  ...                       NaN
140   the_boy_abunda_talk_channel  ...                       NaN
141             pinoy_big_brother  ...                       NaN
142                 unbox_diaries  ...                       NaN
143  the_voice_of_the_philippines  ...                       NaN

[144 rows x 3 columns]

In [ ]:
channels.iloc[:50]

             channel_title                channel_id                 upload_id
0                  cong_tv  UC73zqrs0Th_a9dFUivEmv2A  UU73zqrs0Th_a9dFUivEmv2A
1             slater_young  UCbwa4A6i0elG4WZGY7HRnKw                       NaN
2                 kryzzzie  UCyzvjriEiCVgLieY5Aesw1g                       NaN
3       alodia_gosiengfiao  UC66eoP3j29OuCIM0-K9RnsA                       NaN
4               rei_germar  UCMBfVjLDAebugEphxl9m_Eg                       NaN
5               ry_velasco  UCYCcIV0fYbg_tduACSWD_tQ                       NaN
6                 anna_cay  UCmre3CPYmzcMlVCaFUzkaag                       NaN
7               anne_clutz  UCDGdRHdLtV7VS_nWg9C2RVA                       NaN
8           anneclutzvlogs  UCiM0PLvHvQNWMLZd3ewo3Yg                       NaN
9            itsclaudineco  UCylA3YhDqkmvD_RNJWMJw9w                       NaN
10            abs_cbn_news  UCE2606prvXQc_noEqKxVJXA                       NaN
11   abs_cbn_entertainment  UCstEtN0pgOmCf02EdXsGChw                       NaN
12          alliana_dolina  UCW_pGzpPJjLM9S_6A8d2pEg                       NaN
13      donnalyn_bartolome  UCVwvPcaag7ubJPn1gOClDvQ                       NaN
14             akosi_dogie  UC2LB3AyQ4q2rAk5x1HDDT0g                       NaN
15              carlo_ople  UCcHRUtEO1xAuhGFoaorY8pA                       NaN
16          oliver_austria  UCHHYB05slIGQR5NT92EPr5g                       NaN
17           kenny_manalad  UCUfSt4SOmHr2h-sJrjh3jNw                       NaN
18          doc_willie_ong  UCR6n79EOdY406JlZD8FEgyg                       NaN
19          rendon_labador  UCEeNakY3REgET4iyvilkKrw                       NaN
20              kiko_matos  UCj5RwDivLksanrNvkW0FB4w                       NaN
21          mika_salamanca  UCvBZCUDKjwuUb7mHOucfxMQ                       NaN
22                presello  UCxyLwHwz15uVeXpZjsV1Y2A                       NaN
23   alex_gonzaga_official  UC6N-9Wh0DYhDI8sQS7jwjVA                       NaN
24                    h2wo  UCrkRZBY5gbzQikJy3ny93Qw                       NaN
25         shinejonzoief2p  UCIDrkxe4tIbnOO3fnxod2QA                       NaN
26              junnie_boy  UCqK69ICpVVyghYDvKew0MGg                       NaN
27            benedict_cua  UCamgTpaqgAo1Pt0-xzKwNiQ                       NaN
28     toni_gonzaga_studio  UCgTar4TrvIBvrlMdPUgbFfg                       NaN
29         tryke_gutierrez  UCaaafI2Dg3nVthVR8NO9cSA                       NaN
30               reccreate  UCpZdK-V4x1b2TFzFBKwGztw                       NaN
31                  bermor  UCZnLPVBE7_IHxLU1kMStEkg                       NaN
32              rj_jacinto  UCDy816y_jEQvCoZI8St7zUw                       NaN
33                 xtian_c  UCZnt8Eo6_NehRA0d1DxMV4g                       NaN
34          fliptopbattles  UCBdHwFIE4AJWSa3Wxdu7bAQ                       NaN
35         panlasang_pinoy  UCIjw46txjW6oD4NU6FHaj_w                       NaN
36              bea_alonzo  UC1ebx44DwOCzCSePqJIdC_g                       NaN
37          karl_jolice_tv  UC6GJqZUpIYvMlShyCS93Ymg                       NaN
38                 dubstep  UC_vDF8pbCIR8gaAxXAAH7Og                       NaN
39      front_seat_foodies  UCMlMOnas_-nkOZEE7lXcl9w                       NaN
40                   nisky  UCFBZpT14W2Ze5BcUiaCjpTw                       NaN
41               ninong_ry  UCvQrjgLj841wiQAKDgtKFOw                       NaN
42      gma_public_affairs  UCj5RwDivLksanrNvkW0FB4w                       NaN
43   raffy_tulfo_in_action  UCxhygwqQ1ZMoBGQM2yEcNug                       NaN
44     bonoy_pinty_gonzaga  UCgPhgn8BkNYG0dNyyIlYvGg                       NaN
45                leti_sha  UCWkVgfMFZkJLQ6uB113Xq1A                       NaN
46               wish_1075  UCdfq8-581QVUtVsa8ChVnDQ                       NaN
47  homesearch_philippines  UCImDJsVokH_ubtj8KyXV_XA                       NaN
48                    kiyo  UCav0nXblupOoPZ9H1aczGvA                       NaN
49                 ben&ben  UCD2HT__OY6xzj-YbnAXJhfA                       NaN

In [ ]:
for index, row in channels.iterrows():
    print(row['channel_title'])
    # get the upload ID from the channel ID
    request = youtube.channels().list(
        part="contentDetails",
        id=row['channel_id'],
        maxResults = 1 # first channel only (most relative)
    )
    response = request.execute()
    # can sometimes be the same with channelID
    channels.loc[index, 'upload_id'] = response['items'][0]['contentDetails']['relatedPlaylists']['uploads']

channels.to_csv(script_link+"/channels.csv", index=False)

cong_tv
slater_young
kryzzzie
alodia_gosiengfiao
rei_germar
ry_velasco
anna_cay
anne_clutz
anneclutzvlogs
itsclaudineco
abs_cbn_news
abs_cbn_entertainment
alliana_dolina
donnalyn_bartolome
akosi_dogie
carlo_ople
oliver_austria
kenny_manalad
doc_willie_ong
rendon_labador
kiko_matos
mika_salamanca
presello
alex_gonzaga_official
h2wo
shinejonzoief2p
junnie_boy
benedict_cua
toni_gonzaga_studio
tryke_gutierrez
reccreate
bermor
rj_jacinto
xtian_c
fliptopbattles
panlasang_pinoy
bea_alonzo
karl_jolice_tv
dubstep
front_seat_foodies
nisky
ninong_ry
gma_public_affairs
raffy_tulfo_in_action
bonoy_pinty_gonzaga
leti_sha
wish_1075
homesearch_philippines
kiyo
ben&ben
vice_ganda
jah_de_dios
araw_na_itim_tagalog_animated_horror
paolul
mavs_phenomenal_basketball
jonahrenz_jacob
sb19_official
karla_cayabyab
mocha_uson_official
leni_robredo
jinkee_pacquiao
team_pacquiao
bongbong_marcos
karen_davila
rappler
isko_moreno_domagoso
kuya_kim_atienza
euphoniaco_tv
kathryn_bernardo
viva_records
dr._vicki_belo
schizo_pelma_tv
joyce_pring
nicole_alba
juancho_trivino
yow
latest_scoop
mimiyuuuh
marjorie_barretto
tiktok_pinas
tiktok_philippines
erwin_tulfo
luis_azcona_sharlene_menu
pinoy_knows_tech
eat_bulaga
kusina_ni_lola
beebuyog
alvin_tries_tech
unbox_ph
sulit_tech_reviews
choox_tv
pepesan_tv
olip_tv
khent_bernardo
the_juans
clr
richard_gomez
pinoy_mystery_channel
tinagalog
historya_channel
hazel_quing
ivana_alawa
niana_guerrero
zeinab_harake
jelai_andres
ramon_bautista
empoy_official
kuya_jobert_tv
gretchen_ho
tv5_philippines
luis_manzano
ogie_diaz
love_marie_escudero
master_long_mejia
viy_cortez
mentot
kevin_hermosada
datwo
boss_keng
vien
pat_velasquez
beks_battalion
youlol
jamill
chad_kinis
riva_quenery
wilbert_tolentino
rana_harake
daisy_lopez
tita_krissy_achino
jamichtv
lloyd_cafe_cadena
limuel_huet
mary_bautista
michelle_dy
kathsepaganvlogs
mikhaela_cruz
peachytwice
john_ryan_santos
i_can_see_your_voice_ph
the_boy_abunda_talk_channel
pinoy_big_brother
unbox_diaries
the_voice_of_the_philippines

In [ ]:
channels

                    channel_title  ...                 upload_id
0                         cong_tv  ...  UU73zqrs0Th_a9dFUivEmv2A
1                    slater_young  ...  UUbwa4A6i0elG4WZGY7HRnKw
2                        kryzzzie  ...  UUyzvjriEiCVgLieY5Aesw1g
3              alodia_gosiengfiao  ...  UU66eoP3j29OuCIM0-K9RnsA
4                      rei_germar  ...  UUMBfVjLDAebugEphxl9m_Eg
..                            ...  ...                       ...
139       i_can_see_your_voice_ph  ...  UUQ2HM1jLRY8tpfib1zUjuNQ
140   the_boy_abunda_talk_channel  ...  UUKcX1SFIblkiYg8augik8_w
141             pinoy_big_brother  ...  UUsumo4lY8cd4v8Xt5zG3eSg
142                 unbox_diaries  ...  UU4hQDT1yzyH0KeSKAPJqeMg
143  the_voice_of_the_philippines  ...  UUuXGRLLomiSeJKHw7HnrtDg

[144 rows x 3 columns]

#### 2.) Get Videos of Channel and save to CSV File

In [ ]:
for index, row in channels.iterrows():
    '''
    Saves a CSV file containing video_id and video_title of all videos uploads playlist of a channel.
    Run if you want to get all videos from a channel.
    '''
    # variables
    video_id = []
    video_title = []
    video_description = []
    published_date = []

    # first run, get list of videos of uploads playlist
    request = youtube.playlistItems().list(
        part="snippet, contentDetails",
        maxResults=max_videos,
        playlistId=row['upload_id']
    )

    response_videoIDs = request.execute()

    # store relevant details from the response to list
    for video in response_videoIDs['items']:
        video_id.append(video['contentDetails']['videoId'])
        video_title.append(video['snippet']['title'])
        video_description.append(video['snippet']['description'])
        published_date.append(video['snippet']['publishedAt'])

    # # exhaust all videos of uploads playlist
    while 'nextPageToken' in response_videoIDs:
        request = youtube.playlistItems().list(
            part="snippet, contentDetails",
            maxResults=max_videos,
            playlistId=row['upload_id'],
            pageToken=response_videoIDs['nextPageToken']
        )

        response_videoIDs = request.execute()

        # store relevant details from the response to list
        for video in response_videoIDs['items']:
            video_id.append(video['contentDetails']['videoId'])
            video_title.append(video['snippet']['title'])
            video_description.append(video['snippet']['description'])
            published_date.append(video['snippet']['publishedAt'])

    # combine lists to DataFrame
    data = {'published_date': published_date,
            'video_id': video_id,
            'video_title': video_title,
            'description': video_description,
            'status': 'not_started',
            'nextPageToken': ''}

    # create and sort DataFrame
    df_results = pd.DataFrame(data=data)
    df_results.sort_values(by=['published_date'], ascending=True, ignore_index=True, inplace=True)

    # save to CSV
    df_results.to_csv(script_link + '/channels/' + row['channel_title']+".csv", index=False)