# Corpus Coverage Assement

To asssess the coverage of COHFIE, we will take the intersection of the lexicon/vocabulary of COHFIE and existing filipino/tagalog dictionaries.

Language resources used to compare COHFIE:
* https://tagalog.pinoydictionary.com/
* https://diksiyonaryo.ph/

Decisions:
* lowercased
* deduplicated
* symbols removed
* hyphens are retained

## Load dependencies

In [4]:
import pandas as pd
import regex as re
from tqdm import tqdm
from nltk.probability import FreqDist

## Load FWN

In [5]:
FWN = pd.read_csv("filwordnet_same_paper_no_embeddings.csv")
FWN

,word,sense_id,example_sentences,contextual_info,pos,synset_id
0,matino,matino_0,"['halatang wala ka ng gagawing matino HAHAHA',...",{'twitter': {'2021': 10}},FW,126
1,matino,matino_1,['May mga magulang na matino ang isip at kataw...,"{'google_books': {'2018': 2}, 'twitter': {'202...",FW,207
2,matino,matino_2,"['ng pelikula. Maganda at matino.', 'kasama sa...","{'bandera': {'2014': 2, '2018': 2, '2021': 1, ...",VB,343
3,matino,matino_3,"['akong sinabing matino.', 'Duda ako sa matino...","{'twitter': {'2021': 7}, 'bandera': {'2020': 1...",NN,850
4,maayos,maayos_0,"['di ako makapag isip ng maayos?', 'buti nalan...",{'twitter': {'2021': 10}},JJ,26
...,...,...,...,...,...,...
7078,tuod,tuod_1,"['sabihin ay parang tuod.', 'Ano ko tuod walan...","{'balita': {'2017': 2}, 'twitter': {'2021': 6}...",FW,914
7079,bumaling,bumaling_0,['tingin sakin tas nung bumaling kay joms ay n...,"{'twitter': {'2021': 7}, 'google_books': {'202...",VB,1596
7080,bumaling,bumaling_1,"['puso ay ganap nang bumaling sa Diyos, ipinak...","{'google_books': {'2019': 6, '2021': 4}}",NN,136
7081,anas,anas_0,['Ni graduate nadaw kog laag anas mama HAHAAHA...,{'twitter': {'2021': 10}},NN,387
7082,anas,anas_1,"['Ka anas ga sarapan', 'ko, garu ko gurumuson ...",{'twitter': {'2021': 4}},NN,1012

In [6]:
# Get vocab set
FWN_VOCAB = set(FWN['word'].dropna().unique())
FWN_VOCAB = set([x.lower() for x in FWN_VOCAB])
len(FWN_VOCAB), FWN_VOCAB

(2598,
 {'serbisyo',
  'crawford',
  'infant',
  'umpisa',
  'hita',
  'canadian',
  'homer',
  'lakad',
  'bigas',
  'supot',
  'pagpapaliban',
  'mabasa',
  'kapansanan',
  'bihira',
  'paghihintay',
  'som',
  'ilalim',
  'silid',
  'sedan',
  'lupaypay',
  'saligan',
  'guwardiya',
  'kapalpakan',
  'malik',
  'balita',
  'tiyan',
  'inom',
  'makinang',
  'nobya',
  'iskor',
  'tuwalya',
  'kanto',
  'mangampanya',
  'yakap',
  'drumstick',
  'pukyutan',
  'elise',
  'taba',
  'pagmamasid',
  'basag',
  'sablay',
  'okasyon',
  'listahan',
  'sumang-ayon',
  'burat',
  'inam',
  'shin',
  'gamit',
  'abdominal',
  'ilong',
  'pagtatapos',
  'bangka',
  'kapitolyo',
  'tatak',
  'sambitin',
  'xavier',
  'soda',
  'maasim',
  'gamot',
  'kompetisyon',
  'tubigan',
  'menor',
  'muli',
  'green',
  'ferry',
  'kakaunti',
  'kalye',
  'labing-apat',
  'siko',
  'bumper',
  'pagpapakamatay',
  'oras',
  'pako',
  'sugod',
  'ward',
  'malinaw',
  'ibigay',
  'kape',
  'sandali',
  'palayo',
  'kabisera',
  'tela',
  'tilaok',
  'alagad',
  'manghinayang',
  'bruha',
  'taksil',
  'piraso',
  'langka',
  'baguhan',
  'bilis',
  'cooler',
  'mundo',
  'tagahanga',
  'tili',
  'labing-isa',
  'irog',
  'cap',
  'magsara',
  'paninindigan',
  'talon',
  'kaso',
  'puntod',
  'paglalaban',
  'unawa',
  'abuloy',
  'kapareho',
  'magbilang',
  'batas',
  'kalsada',
  'jinx',
  'pagtalakay',
  'bagon',
  'dumaong',
  'labi',
  'simula',
  'apat',
  'ginto',
  'blend',
  'tuod',
  'dilaw',
  'lena',
  'lewis',
  'bell',
  'magnakaw',
  'kina',
  'tree',
  'kinatawan',
  'pambihira',
  'isaalang-alang',
  'unos',
  'ford',
  'magkakamukha',
  'bahala',
  'buntot',
  'damot',
  'doktrina',
  'singaw',
  'bilasa',
  'katayin',
  'palakasan',
  'lorenz',
  'ligaw',
  'lamok',
  'cracker',
  'beso',
  'sako',
  'gi',
  'simulan',
  'converse',
  'baterya',
  'kuro-kuro',
  'bilang',
  'mabait',
  'ubas',
  'ibasura',
  'abalahin',
  'gb',
  'imbakan',
  'istilo',
  'arogante',
  'ginaw',
  'tawa',
  'dahon',
  'nakatalo',
  'kain',
  'shah',
  'akademya',
  'bangis',
  'marahas',
  'eksakto',
  'iron',
  'altar',
  'lalagyan',
  'oo',
  'jenner',
  'pahina',
  'kalawakan',
  'panganib',
  'relos',
  'uhaw',
  'payong',
  'tinola',
  'tungkol',
  'silicon',
  'ima',
  'hilaga',
  'bumbilya',
  'tiyak',
  'binibini',
  'debate',
  'datos',
  'dalawampu',
  'kalkal',
  'amor',
  'sampol',
  'sabik',
  'ipinatong',
  'litro',
  'bahaw',
  'salita',
  'iwasan',
  'vega',
  'bayuhin',
  'kaharian',
  'sugo',
  'veteran',
  'tsaka',
  'halakhak',
  'traction',
  'upuan',
  'ama',
  'dati',
  'alisin',
  'kalungkutan',
  'dike',
  'kota',
  'bura',
  'pugon',
  'raketa',
  'pagdiriwang',
  'ibaba',
  'payagan',
  'manloko',
  'acquaintance',
  'bayan',
  'stapler',
  'don',
  'binata',
  'sinisinta',
  'init',
  'rebolusyonaryo',
  'tugisin',
  'ngisi',
  'ulam',
  'kent',
  'masugid',
  'pasukan',
  'okey',
  'alinlangan',
  'maganda',
  'kiki',
  'itago',
  'cider',
  'kompanya',
  'udyok',
  'muning',
  'watawat',
  'ob',
  'arkitekto',
  'dolyar',
  'istorbo',
  'saya',
  'buto',
  'isyu',
  'sumakit',
  'sigaw',
  'kuya',
  'uli',
  'sahog',
  'paalis',
  'rehistro',
  'sustento',
  'sentinel',
  'anim',
  'magalit',
  'kabiguan',
  'devil',
  'pelikula',
  'sumpong',
  'imposible',
  'bida',
  'haplos',
  'halalan',
  'alaala',
  'bilangin',
  'drift',
  'bahura',
  'pusit',
  'alinsunod',
  'mantsa',
  'isalin',
  'makata',
  'asa',
  'papeles',
  'asawa',
  'takilya',
  'bus',
  'pakuluan',
  'bethe',
  'mate',
  'mu',
  'gurang',
  'malambot',
  'timbangan',
  'hintay',
  'mayabang',
  'panukala',
  'base',
  'mababaw',
  'nile',
  'click',
  'itsura',
  'ilusyon',
  'mare',
  'xian',
  'merkado',
  'sabog',
  'bumuo',
  'una',
  'pabuya',
  'yuta',
  'klee',
  'loob',
  'bakla',
  'pagkatao',
  'pakwan',
  'tuldok',
  'pound',
  'panday',
  'kaskasero',
  'pakikipagsapalaran',
  'pipi',
  'sangkalan',
  'hinto',
  'ika-anim',
  'tatlo',
  'gandahan',
  'kasintahan',
  'taft',
  'milne',
  'lalamunan',
  'palayaw',
  'coward',
  'kuneho',
  'pagkakahirang',
  'opinyon',
  'ilagay',
  'alindog',
  'neon',
  'maiksi',
  'makalampas',
  'embodiment',
  'sikreto',
  'gutumin',
  'pagtitiis',
  'bigla',
  'tinig',
  'black',
  'sakop',
  'diaz',
  'maghanap',
  'mamatay',
  'bumili',
  'puday',
  'takbo',
  'kaugnayan',
  'alkalde',
  'katabaan',
  'pilas',
  'kamandag',
  'tangayin',
  'taong-bayan',
  'lango',
  'meryenda',
  'puso',
  'mb',
  'misteryo',
  'magsulat',
  'suntukin',
  'lagusan',
  'rivera',
  'mason',
  'nakalipas',
  'kagalit',
  'ecstasy',
  'humupa',
  'dalampasigan',
  'napakahirap',
  'kabit',
  'dalandan',
  'hari',
  'hale',
  'talipapa',
  'mangasiwa',
  'sinangag',
  'makinis',
  'sugat',
  'iba',
  'mapagmataas',
  'matatag',
  'ambulansya',
  'liham',
  'madre',
  'nakabukas',
  'hayag',
  'suot',
  'inahin',
  'leon',
  'garapon',
  'dis',
  'magbalak',
  'paliguan',
  'kataka-taka',
  'lek',
  'batik',
  'hapag-kainan',
  'mapalad',
  'impormasyon',
  'halaga',
  'takot',
  'bula',
  'magtipon',
  'piloto',
  'likha',
  'sining',
  'kapalit',
  'katumbas',
  'bernard',
  'ugong',
  'panaghoy',
  'tren',
  'accuracy',
  'magpatala',
  'pasyente',
  'armas',
  'ganap',
  'bansot',
  'mosyon',
  'limitado',
  'isulat',
  'zombie',
  'misa',
  'balakubak',
  'leksyon',
  'bilyon',
  'adam',
  'basehan',
  'umani',
  'buhok',
  'tenge',
  'lakas',
  'pataba',
  'kakilala',
  'rekado',
  'mukmok',
  'reputasyon',
  'kawikaan',
  'tomboy',
  'sausage',
  'duwende',
  'platinum',
  'omega',
  'pagkagusto',
  'sandata',
  'kalansay',
  'pag-aalis',
  'lasa',
  'putulin',
  'kaawa-awa',
  'roar',
  'kura',
  'hagupit',
  'tunog',
  'won',
  'modelo',
  'palad',
  'pagtingin',
  'nakakapagod',
  'scott',
  'pugo',
  'asikaso',
  'magmay-ari',
  'trooper',
  'parol',
  'mataba',
  'magtulak',
  'oso',
  'ebak',
  'ani',
  'pop',
  'apaw',
  'mapapunta',
  'panandalian',
  'pang-amoy',
  'lantad',
  'buhangin',
  'karakter',
  'pirmahan',
  'dagdag',
  'delta',
  'clover',
  'maagap',
  'silver',
  'lagnat',
  'sagabal',
  'ninenerbiyos',
  'tulad',
  'ika-apat',
  'ibenta',
  'panatilihin',
  'halakhakan',
  'khi',
  'kabibe',
  'birhen',
  'hotel',
  'mahalin',
  'lumiit',
  'ibigin',
  'tapos',
  'dali',
  'musika',
  'sulyap',
  'numerong',
  'suliranin',
  'pagtatayo',
  'kamukha',
  'grabe',
  'tawanan',
  'pagkakaibigan',
  'tumakbo',
  'pangangati',
  'gunita',
  'ilathala',
  'rurok',
  'matalas',
  'heart',
  'baril',
  'sinaing',
  'tindahan',
  'kumpiyansa',
  'predator',
  'tahimik',
  'layo',
  'apura',
  'pulutan',
  'pang-unawa',
  'avon',
  'maliit',
  'dila',
  'sinigang',
  'boses',
  'magmaneho',
  'pokpok',
  'makati',
  'bukas',
  'halimaw',
  'kasawian',
  'likod',
  'emu',
  'tapat',
  'utos',
  'bimpo',
  'balang',
  'crow',
  'imahen',
  'hayaan',
  'karapatan',
  'riel',
  'masid',
  'gabay',
  'sopas',
  'karate',
  'pagtitimpi',
  'dayuhan',
  'yaya',
  'maya',
  'palagi',
  'ibunyag',
  'tumuntong',
  'submarine',
  'galitin',
  'satsat',
  'kahon',
  'kwanza',
  'lumbay',
  'handa',
  'nipa',
  'nakamamatay',
  'umurong',
  'nanay',
  'mabibigay',
  'suko',
  'panggagamot',
  'madaldal',
  'flora',
  'gasgas',
  'sobra',
  'cam',
  'ngawngaw',
  'tamad',
  'dilis',
  'bigkasin',
  'hangarin',
  'ipagkaloob',
  'rebyu',
  'tsuper',
  'eksperto',
  'wala',
  'epidemiologist',
  'milyon',
  'kulog',
  'tambangan',
  'materyales',
  'tuklas',
  'madali',
  'magpatiwakal',
  'bilyar',
  'diskarte',
  'buod',
  'shake',
  'pagdami',
  'respetado',
  'bading',
  'pinggan',
  'kitilin',
  'pamaypay',
  'panda',
  'contrary',
  'pulbo',
  'kanta',
  'retrato',
  'meteorologist',
  'noah',
  'napkin',
  'dangal',
  'sikmura',
  'pato',
  'tanggapin',
  'naira',
  'sipsipin',
  'libog',
  'lagdaan',
  'chess',
  'kamao',
  'kaguluhan',
  'kusa',
  'linis',
  'bahing',
  'grass',
  'mabango',
  'tracy',
  'bansa',
  'lumihis',
  'dapithapon',
  'libag',
  'malayo',
  'baga',
  'pagpapaputok',
  'katapangan',
  'tanim',
  'gobyerno',
  'gunggong',
  'halaman',
  'payaso',
  'sinturon',
  'tesla',
  'disturbance',
  'dilim',
  'kasangkapan',
  'unano',
  'service',
  'tau',
  'matindi',
  'kaalyado',
  'pagsasanay',
  'mahigpit',
  'ulyanin',
  'kilos',
  'shampoo',
  'pagsisiyasat',
  'kondisyon',
  'ac',
  'bulbol',
  'lamb',
  'balabal',
  'lakaran',
  'kubyertos',
  'sariwa',
  'basurahan',
  'mamaya',
  'kutsilyo',
  'pogi',
  'exec',
  'sinabi',
  'pagbabati',
  'hunt',
  'basket',
  'saklaw',
  'ibahin',
  'tanggalin',
  'pait',
  'mabuti',
  'pasimuno',
  'lindol',
  'galos',
  'salaysay',
  'himukin',
  'bangko',
  'hilera',
  'palo',
  'obserbasyon',
  'mansanas',
  'magsaya',
  'pagpapatiwakal',
  'warren',
  'impyerno',
  'magkasundo',
  'ngawa',
  'payo',
  'para',
  'rebolusyon',
  'talino',
  'kapkapan',
  'zion',
  'halimuyak',
  'mumo',
  'sombrero',
  'isahan',
  'naiinom',
  'medyas',
  'repolyo',
  'bilangguan',
  'pakay',
  'pakahulugan',
  'palit',
  'bibe',
  'constable',
  'noo',
  'kalapati',
  'kampanya',
  'parada',
  'pulbos',
  'wasak',
  'pingpong',
  'pula',
  'pilitin',
  'gong',
  'tiyanak',
  'thompson',
  'umutot',
  'samantalahin',
  'spencer',
  'igos',
  'instrumento',
  'bitag',
  'pangingisda',
  'panatiko',
  'mata',
  'anibersaryo',
  'maleta',
  'maluwag',
  'isama',
  'pukpok',
  'anas',
  'espasyo',
  'punan',
  'ayusin',
  'magsumbong',
  'tusukin',
  'noong',
  'tumanggap',
  'umisip',
  'pagsusuri',
  'wood',
  'pedestal',
  'po',
  'kinakailangan',
  'kilo',
  'lotion',
  'mangatwiran',
  'moreno',
  'ipagbili',
  'tagapagtanggol',
  'itampok',
  'mabilis',
  'lister',
  'artikulo',
  'stanley',
  'pintuan',
  'pilosopo',
  'disipulo',
  'langis',
  'agila',
  'lason',
  'duwelo',
  'dumating',
  'unggoy',
  'lobo',
  'sugapa',
  'tambutso',
  'rehiyon',
  'saksak',
  'kalasag',
  'bunso',
  'andar',
  'hapag',
  'karamdaman',
  'takas',
  'okupado',
  'bowling',
  'kakahuyan',
  'nalilito',
  'pagkakaalis',
  'batasan',
  'disyerto',
  'naliliyo',
  'giliw',
  'pentagon',
  'obaryo',
  'nun',
  'buwaya',
  'drone',
  'martilyo',
  'dam',
  'sagutin',
  'swag',
  'bayag',
  'himala',
  'windang',
  'driver',
  'harina',
  'lloyd',
  'agam-agam',
  'pagkontra',
  'magtaka',
  'sermon',
  'lahat',
  'maalat',
  'kinse',
  'balat',
  'talisman',
  'rugby',
  'jet',
  'tamod',
  'ere',
  'tusok',
  'importante',
  'bolero',
  'pananabik',
  'produkto',
  'moo',
  'limos',
  'awayin',
  'game',
  'tabi',
  'gib',
  'bakod',
  'dumplings',
  'abiso',
  'kinabukasan',
  'potassium',
  'nawala',
  'slaughterhouse',
  'bachelor',
  'gabinete',
  'paumanhin',
  'pagbawalan',
  'nickel',
  'gapang',
  'bisig',
  'gamitin',
  'sumipsip',
  'beth',
  'gisingin',
  'timba',
  'dalagita',
  'nguso',
  'magyabang',
  'relihiyon',
  'rambutan',
  'wasto',
  'trak',
  'lalaki',
  'drake',
  'patibayan',
  'saglit',
  'trunk',
  'masigasig',
  'kasunduan',
  'laglag',
  'akto',
  'layuan',
  'karo',
  'sine',
  'ordinaryo',
  'pahintulutan',
  'stephen',
  'hiwaga',
  'pangkat',
  'pagnanais',
  'kean',
  'planeta',
  'kami',
  'minsan',
  'kinakabahan',
  'kasiyahan',
  'kama',
  'paputok',
  'malaman',
  'danyos',
  'titi',
  'basketbol',
  'higante',
  'bol',
  'petsa',
  'subok',
  'durugin',
  'lawin',
  'kapit',
  'agahan',
  'peklat',
  'paghihirap',
  'tipaklong',
  'sakali',
  'panggastos',
  'nagtapos',
  'bangaw',
  'darling',
  'ilaw',
  'matalino',
  'kapote',
  'paninda',
  'impeksiyon',
  'hintuturo',
  'kabaliwan',
  'pader',
  'palamuti',
  'lead',
  'tanglaw',
  'motorista',
  'umanib',
  'nag-iisa',
  'tema',
  'klaro',
  'agos',
  'sinumpa',
  'nitso',
  'ganda',
  'bumagsak',
  'dama',
  'bahaghari',
  'putik',
  'mais',
  'yosi',
  'punda',
  'tagasubaybay',
  'dosena',
  'patnubay',
  'payag',
  'kulay',
  'torotot',
  'hangin',
  'kainggitan',
  'balisong',
  'burahin',
  'itusok',
  'basketball',
  'makulit',
  'reaksyon',
  'dalaga',
  'ipagpalagay',
  'dibisyon',
  'hall',
  'av',
  'pababa',
  'batak',
  'himagsikan',
  'pahabain',
  'katulad',
  'patalsikin',
  'acronym',
  'harvey',
  'ara',
  'sabon',
  'galamay',
  'sari-sari',
  'dvd',
  'hayop',
  'yen',
  'mamon',
  'poot',
  'land',
  'mars',
  'ari-arian',
  'dikya',
  'napakalalim',
  'ball',
  'leigh',
  'mapa',
  'nahihilo',
  'panangga',
  'pasiya',
  'landas',
  'okra',
  'bugtong',
  'sustansya',
  'maaga',
  'binti',
  'gyera',
  ...})

## Load Borra

In [7]:
BORRA = pd.read_csv("borrawordnet.csv")
BORRA

,wordid,lemma,synsetid,senseid,pos,lexdomainid,definition,lastmodifier,sumo
0,51421,matino,302262136,50225,a,0,nasa tamang pagiisip,1,None
1,49082,maayos,302262136,50226,a,0,nasa tamang pagiisip,1,None
2,51420,hanapbuhay,100553013,50224,n,0,paraan ng pamumuhay,1,None
3,51419,trabaho,100553013,50223,n,0,paraan ng pamumuhay,1,None
4,51419,trabaho,100584367,52818,n,0,propesyon na kung saan ikaw ay kumikita,1,Position
...,...,...,...,...,...,...,...,...,...
15924,61635,baak,202467662,62444,v,0,hatiin sa dalawa,19,Separating
15925,61636,kayamutan,300113818,62445,v,0,magalit sa isang tao,19,Anger
15926,61637,antala,101066163,62446,n,0,ginagawa ng pagkatapos ng takdang oras,19,Process[
15927,61638,anas,200915830,62447,n,0,mahinang sinabi,19,Speaking
15928,61639,busisi,301586342,62448,a,0,masyadong mabait,19,SubjectiveAssessmentAttribute

In [8]:
# Get vocab set
BORRA_VOCAB = BORRA['lemma'].dropna().unique()
BORRA_VOCAB = set([x.lower() for x in BORRA_VOCAB])
len(BORRA_VOCAB), BORRA_VOCAB

(13538,
 {'amaterasu',
  'kriminologist',
  'infant',
  'atmospera',
  'regiomontanus',
  'carrere',
  'antropolohista',
  'apatnaput-siyam',
  'victoria land',
  'harrison',
  'cellini',
  'cristobal colon',
  'saone ilog',
  'linnaeus',
  'mark wayne clark',
  'homer',
  'eysenck',
  'pitt',
  'ika-labing-anim',
  'pukol sa bola',
  'cervantes saavedra',
  'dean gooderham acheson',
  '29',
  'supot',
  'walang kabuluhan',
  'calypso',
  'praga',
  'mabasa',
  'abel',
  'zilyon',
  'alecto',
  'edward jenner',
  '69',
  'august strindberg',
  'kentucky bluegrass',
  'sibelius',
  'manat',
  'pantothenic acid',
  '155',
  'santo dominic',
  'al-hasan ibn al-haytham',
  'hugo junkers',
  'maxwell anderson',
  'apatnapu',
  'malik',
  'xylose',
  'contraction',
  'tiyan',
  'william henry pratt',
  'thetis',
  'bath asparagus',
  'rabis',
  'sessions',
  'pamilyang xenopodidae',
  'hertz',
  'fighting joe hooker',
  'sitwell',
  'boulez',
  'babe ruth',
  'natural siyensiya',
  'repormer',
  'sumang-ayon',
  'inam',
  'jefferson',
  '89',
  'sojourner truth',
  'cyrillic',
  'ashtoreth',
  'bangka',
  'giosue carducci',
  'zakat',
  'xerophyllum',
  'fire_and_brimstone',
  'guangzhou',
  'djibouti franc',
  'tatak',
  'xavier',
  'loire',
  'maasim',
  'kompetisyon',
  'pamamana',
  'tubigan',
  'tetragrammaton',
  'edward morley',
  'muli',
  'punung-kahoy',
  'nalaho',
  'asa gray',
  'inang-binyag',
  'crossbeam',
  'dalawamput-dalawa',
  'tungsten',
  'i thessalonians',
  'leo xiii',
  'tagapaghatid',
  'grappelli',
  'sugod',
  'willebrand',
  'araw ng kalayaan ng texas',
  'crouse',
  'aten',
  'ika-dalawapu',
  'aleksandr i. solzhenitsyn',
  'pasteur',
  'willard frank libby',
  'klotho',
  'daniel chester french',
  'iceland',
  'dorothy leigh sayers',
  'el salvador',
  'air terminal',
  'greta louisa gustafsson',
  'laurence sterne',
  'belleau wood',
  'okupasyon',
  'bantu',
  'angus frank johnstone wilson',
  'carbon paper/ papel na karbon',
  'bruha',
  'taksil',
  'piraso',
  'langka',
  'baguhan',
  'bilis',
  'utug',
  'pagdugo',
  'walter reed',
  'mundo',
  'theodore roosevelt',
  'cooler',
  '11',
  'tagahanga',
  'judah',
  'fuentes',
  'charles franklin peirce',
  'ichthyologists',
  'isaac',
  'prince fumimaro konoye',
  '73',
  'doric order',
  'george edward moore',
  'unawa',
  'arthur symons',
  'magbilang',
  'friedrich anton mesmer',
  'p. p. von mauser',
  'pagkaing aso',
  'typhoid fever',
  'timog kanlurang namibia',
  'somme',
  'jinx',
  'johann christoph friedrich von schiller',
  'belgian franc',
  'osaka bay',
  'simula',
  'apat',
  'darnan',
  'dame myra hess',
  'daniel ortega saavedra',
  'tenyente',
  'benjamin jonson',
  'kola',
  'tuod',
  'andrea mantegna',
  'saint baeda',
  'vargas',
  'pambihira',
  'ian wilmut',
  'glee club',
  'theta',
  'saint john',
  'emmett kelly',
  'magkakamukha',
  'taga-obserba',
  'damot',
  'stairwell',
  'drip coffee',
  'katayin',
  'eos',
  'ika-dalawandaan',
  'lorenz',
  'maurice chevalier',
  'jane fonda',
  'robert adam',
  'kuro-kuro',
  'mel gibson',
  'vidal',
  'hugo alvar henrik aalto',
  'de bakey',
  'apatnaput-walo',
  'nergal',
  'antilope',
  'gb',
  'ilog allegheny',
  'xnthophyceae',
  'don ilog',
  'earl warren',
  'borges',
  'indian chief',
  '16th',
  'arab chief',
  'second earl of guilford',
  'walton',
  'dahon',
  'genus xiphias',
  'tagamanman',
  'spark lever',
  'sosyo',
  'bahai',
  'niger ilog',
  'bangis',
  'zane grey',
  'menepos',
  'adi granth',
  'altar',
  'frank philip stella',
  'irving',
  'borgia',
  'type a',
  'francisco jose de goya y lucientes',
  'jimenez',
  'lachesis',
  'kalawakan',
  'ika-siyamnapo',
  'benton',
  'selene',
  'lozier',
  'natalie wood',
  'dogcart',
  'rhein',
  'santo john',
  'hilaga',
  'ezra pound',
  'allen tate',
  'page',
  'dalawampu',
  "democratic people's republic of korea",
  'hamilton',
  'sampol',
  'james whitcomb riley',
  'benjamin peirce',
  'xiphiidae',
  'tarawa',
  'iwasan',
  'seaborgium',
  'ninkhursag',
  'vega',
  'kaharian',
  'grieg',
  'airdock',
  'bismuth',
  'north platte ilog',
  'ohio',
  'niger',
  'dean acheson',
  'chari',
  'punong-papaya',
  'thomas j. hanks',
  'dyirap',
  'aleksandr prokhorov',
  'traction',
  'aristotle',
  'condorcet',
  'sinuoan',
  'st. andrew',
  'peirce',
  'alisin',
  'kanser sa pantog',
  'sir john gielgud',
  'aglalarawan',
  'w. somerset maugham',
  'golpo ng california',
  'austral',
  'jacobi',
  'uli-uli',
  'ethel waters',
  'kota',
  'makina ng kotse',
  'hungarian',
  'pagdiriwang',
  'ibaba',
  'william wycherley',
  'charles i',
  'acquaintance',
  '55th',
  'edward lee thorndike',
  'van de graaff',
  'stapler',
  '65',
  'sami',
  'john reed',
  'binata',
  'sinisinta',
  "o'connor",
  'julius erving',
  'fat waller',
  'fernand leger',
  'benvenuto cellini',
  'vladimir kosma zworykin',
  'marso 2',
  'droning',
  'bartok',
  'ulam',
  'princess of wales',
  'masugid',
  'jordanian dinar',
  'bourdon',
  'tucana',
  'kiki',
  'udyok',
  'astrolyabya',
  'dolyar',
  'buto',
  'kipot ng georgia',
  'sigaw',
  'nintu',
  'uli',
  'maxim',
  'stockton',
  'sahog',
  'mebibyte',
  'paalis',
  'siyamnaput-siyam',
  'chuck berry',
  'zionism',
  'elmore john leonard',
  'donne',
  'balaton',
  'cerium',
  'rankin',
  'sir henry rider haggard',
  'putin',
  'thoms huxley',
  'anim',
  'algernon charles swinburne',
  'isla ng bahrain',
  'kabiguan',
  'burbage',
  'mohammed',
  'systemic lupus erythematosus',
  'r. j. mitchell',
  'edwin powell hubble',
  'test driver',
  'iris pallida',
  'bida',
  'bogota',
  'ilulan',
  'r',
  'conakry',
  'bilangin',
  'ika-isandaan at limampu',
  'y-kromosom',
  'bulgarian',
  'pusit',
  'rio de la plata',
  'jean anouilh',
  'alinsunod',
  'leibnitz',
  'katuyutan',
  'makata',
  'asa',
  "pandora's box",
  'genus cyclops',
  '26th',
  'mate',
  'pakuluan',
  'wilder',
  'richard_upjohn',
  'wolf',
  'book_of_joshua',
  'henry valentine miller',
  'terence',
  'jimmy doolittle',
  'haeckel',
  'earl of warwick',
  'putlain',
  'japanese angelica tree',
  'richard phillips feynman',
  'howard hughes',
  'opurtunismo',
  'wisonsin river',
  'deforestation',
  'baak',
  'wapiti',
  'interyor',
  'bobby jones',
  'ramman',
  'honduras',
  'genus xerobates',
  'yuta',
  'poseidon',
  'johann muller',
  'bakla',
  'pakwan',
  'pamamaluktot',
  'ira gershwin',
  'ika-20 siglo',
  'pipi',
  'hinto',
  'ika-anim',
  'robert ranke graves',
  'frisbee',
  'ieoh_ming_pei',
  'taft',
  'milne',
  'astarte',
  'erik satie',
  'punong-limon',
  'gorki',
  'ernest rutherford',
  'kuneho',
  'crepe paper',
  'john thomas scopes',
  'taga-mongolia',
  'lamun',
  'mandarin',
  'king crab',
  'montez',
  'tiga-araro',
  'maiksi',
  'maupassant',
  'pangmaramihan',
  'villon',
  'microbiologist',
  'mosander',
  'bill mauldin',
  'sir edward william elgar',
  'bigla',
  'henrik johan ibsen',
  'tinig',
  'indian rupee',
  'richard john roberts',
  'tanzania',
  'kandinsky',
  'old high german',
  'czech',
  'nellie ross',
  'timothy francis leary',
  'pan american union',
  'maghanap',
  'kentucky yellowwood',
  'mamatay',
  'bromine',
  'romberg',
  'hyperborean',
  'chamaeleon',
  'lugosi',
  'surboard',
  'pilas',
  'hess',
  'zsigmondy',
  'william tecumseh sherman',
  'general charles de gaulle',
  'john smith',
  'james henry leigh hunt',
  'tangayin',
  'taong-bayan',
  'jan amos komensky',
  'rekorder',
  'ruth st. denis',
  'smetana',
  'magdingas',
  'carl nielsen',
  'brahmaputra',
  'kolkata',
  'oenomel',
  'bulkan st. helens',
  'kordofan',
  'mb',
  'thespis',
  'magsulat',
  'pamukpok',
  'tate',
  'suntukin',
  'goncourt',
  'fyodor mikhailovich dostoyevsky',
  'stephanie graf',
  'gloria may josephine svensson',
  'rivera',
  'pierre curie',
  'mason',
  'ika-labing-apat',
  'emile zola',
  'toulouse-lautrec',
  'fermi',
  'karanasa',
  '88',
  'ecstasy',
  'nixon',
  'first earl wavell',
  'dalampasigan',
  'dorothy dix',
  'napakahirap',
  'kabit',
  'isang daan',
  'jeroboam_i',
  '22',
  'hari',
  'hero of alexandria',
  'euler',
  'arindante',
  'jack frost',
  'marian anderson',
  '44',
  'kyrgyzstan',
  'sugat',
  'james hargreaves',
  'satie',
  'lee yuen kam',
  'sinclair',
  'asamiya',
  'president van buren',
  'nakabukas',
  'tsampan',
  'hayag',
  'algerian monetary unit',
  'guwantes',
  'suot',
  'peter pan collar',
  'komandante',
  'paris',
  'garapon',
  'chester alan arthur',
  'book_of_nahum',
  'dumhan',
  'gallaudet',
  'tekstuwal',
  'rheumatoid arthritis (ra)',
  'magbalak',
  'opereytor',
  'kataka-taka',
  'helen of troy',
  'oktosilabik',
  'helium',
  'lithuanian',
  'turki',
  'elinor morton hoyt wylie',
  'neapolitan na surbetes',
  'platte ilog',
  'bula',
  'mari',
  'zambezi',
  'genus xyphophorus',
  'antonym',
  'hobbs',
  'whittier',
  'gustav mahler',
  'henrik ibsen',
  'bernard',
  'cervantes',
  'socratic',
  'pepsi',
  'accuracy',
  'whitney',
  'willem de sitter',
  'dwight filley davis',
  'gabriel lippmann',
  'bansot',
  'tashmitum',
  'balarila',
  'boy orator of the platte',
  'balakubak',
  'monrovian',
  'judges',
  'adam',
  'barena',
  'flory',
  'deng xiaoping',
  'obra-maestro',
  'white house',
  'pataba',
  'artsibo',
  'barbados',
  'machiavelli',
  '11th',
  'kawikaan',
  'roseau',
  'leptospirosis',
  'president john quincy adams',
  'platinum',
  'dalmatian iris',
  'baron karl wilhelm humboldt',
  'xerography',
  'statistiko',
  'sandata',
  'hippolyte jean giraudoux',
  'blair',
  'eks-ray film',
  'burundi franc',
  'po ilog',
  'kutsarita',
  'sergei sergeyevich prokofiev',
  '55',
  'coolidge',
  'hank williams',
  'oersted',
  'edouard vuillard',
  'wyat',
  'anu',
  'julia evelina smith',
  'oxford english dictionary',
  'won',
  'payakang pangungusap',
  'sir thomas wyatt',
  'pediculosis',
  'modelo',
  'idaho',
  'steller',
  'upsilon',
  'joseph mccarthy',
  'middle low german',
  'alakdan',
  'kuzets',
  'scott',
  'leger',
  'ouse ilog',
  'trooper',
  'gordie howe',
  'clara josephine schumann',
  'alpabetong armenyo',
  'inuming tubig',
  'varese',
  'allegheny',
  'donizetti',
  'pag-andar',
  'magtulak',
  'hilaw na gatas',
  'ithunn',
  'pop',
  'serdica',
  'arthur edwin kennelly',
  'pedro calderon de la barca',
  'enesco',
  'drinking water',
  'gugo',
  'douglas macarthur',
  'boltzmann',
  'buhangin',
  'munro',
  'innocent xi',
  'katakutan sa mga bading',
  'h',
  'delta',
  'captain john smith',
  'lennox robinson',
  'vernier',
  'augustine',
  'kenzo_tange',
  'isaac newton',
  'takong manok',
  'kabibe',
  'hotel',
  'first marquess cornwallis',
  'dame edit sitwell',
  'taga-syria',
  'erving',
  'mark anthony',
  'dali',
  'molech',
  'pag-uukol',
  'john donald budge',
  'thomas carlyle',
  'benin',
  'grigori potyokin',
  'grabe',
  'meuse-argonne operation',
  'book of mormon',
  'tumakbo',
  'pangangati',
  'origami',
  'steinmetz',
  'grub street',
  'kapeng irish',
  'byelorussian',
  'hellman',
  'louis_henry_sullivan',
  'emerson',
  'richard kuhn',
  'book_of_exodus',
  'katakutan sa mga pusa',
  'argonne',
  'auto accessory',
  'tagasapatos ng kabayo',
  'radhakrishnan',
  'tahimik',
  'umibis',
  'marvin neil simon',
  'avon',
  'sinulok',
  'charles schulz',
  'harold nicolson',
  'stanley baldwin',
  'scopes',
  'bengali',
  'sir robert walpole',
  'magmaneho',
  'geryon',
  'jeroboam',
  'pang-uri',
  'pokpok',
  'stephen butler leacock',
  'justinian the great',
  'makati',
  'trevino',
  'halimaw',
  'italo calvino',
  'bessie smith',
  'yasser arafat',
  'thomas moore',
  'utos',
  'balik-aral',
  'balang',
  'liberia',
  'joseph ben matthias',
  'hawaii',
  'william mckinley',
  'angolan monetary unit',
  'sir william gilbert',
  'ouguiya',
  'metis',
  'tsinong parol',
  'jomo kenyata',
  'ivan sergeevich turgenev',
  'parte ng katawan',
  'kyoto',
  'gentleman johnny',
  'palagi',
  'mohammed_ali',
  'ibunyag',
  'mt',
  'carlos chavez',
  'alfred damon runyon',
  'americium',
  'heilong',
  'washington irving',
  'albers',
  'liryo ng michigan',
  'metical',
  'bundok tacoma',
  'john barth',
  'buslo',
  'de la mare',
  'pira-piraso',
  'daglat',
  'samoyed',
  'kanal na hinggil sa sustansya',
  'ornamento',
  '29th',
  'ereshkigel',
  'kapatid na babae',
  'okteyn',
  'mark clark',
  'nakamamatay',
  'malay peninsula',
  'bermuda',
  'maputing russian',
  'augustus',
  'adapa',
  'benedict',
  'nepal',
  'belgium',
  'baudelaire',
  'zizz',
  'basil',
  'laney',
  'suko',
  'chu kiang',
  'taga-orissa',
  'obstetrisyan',
  'micheas',
  'lyman frank brown',
  'poitier',
  'diyos ng mga semitiko',
  'charles franklin kettering',
  'gurkha',
  'gasgas',
  'haiti',
  'wac',
  'boddhisatva',
  'tamad',
  'x-linked dominant inheritance',
  'genus xylocopa',
  'okultismo',
  'folie',
  'rebyu',
  'george orwell',
  'nikaragua',
  'eksperto',
  'wala',
  'oates',
  'pagtakinin',
  'irlanda',
  'mangangaso',
  'cystic fibrosis',
  'epidemiologist',
  'tambangan',
  'mandelshtam',
  'magpatiwakal',
  'wodehouse',
  'diskarte',
  'styron',
  '83',
  'shake',
  'pagdami',
  'aire',
  'respetado',
  'chickenfeed',
  'bernd heinrich wilhelm von kleist',
  'great sandy desert',
  'genus euterpe',
  'lari',
  'bading',
  'excrescence',
  'pamaypay',
  'prankisiya',
  'sidonie-gabrielle claudine colette',
  'pumpyang',
  'augusta',
  'retrato',
  'john kenneth galbraith',
  'john steinbeck',
  'dubya',
  'ununpentium',
  'napkin',
  'scolopax rusticola',
  'en-lil',
  'ares',
  'pato',
  'carl gustaf mossander',
  'heinrich hertz',
  'cabot',
  'naira',
  'romanian monetary unit',
  'russel crouse',
  'sunburn',
  'lagdaan',
  'bernard law montgomery',
  'theodore samuel williams',
  'berg',
  'mary wollstonecraft',
  'bertrand russell',
  'calypso bulbosa',
  'kamao',
  'roger sessions',
  'mocha coffee',
  'kontinente ng antarctic',
  'oswald veblen',
  'beauvoir',
  'bansa',
  'lumihis',
  'manikin',
  'david roland smith',
  'malayo',
  'langmuir',
  'waglit',
  'katapangan',
  'thomas kid',
  'incomplete fracture',
  'dostoyevsky',
  'bedrich smetana',
  'anne sexton',
  '100',
  'silangang germany',
  'halden',
  'aleksandr nikolayevich scriabin',
  'bellerophon',
  'taga-akay',
  'kasangkapan',
  'azerbaijan',
  'xanthelasma',
  'ben sira',
  'kaalyado',
  'racine',
  'jerome kern',
  'e. t. a. hoffmann',
  'grover cleveland',
  'spillane',
  'kilos',
  'pagsisiyasat',
  'george washington goethals',
  'mendeleev',
  'kasai ilog',
  'ac',
  'pambukas ng lata',
  'francis scott key fitzgerald',
  '46th',
  'eating disorder',
  'fridtjof nansen',
  'niagara',
  'st. george',
  'william sydney porter',
  'van der waals',
  'santo jude',
  'tagadisenyo',
  'kutsilyo',
  'xanax',
  'exec',
  'abattoir',
  'morrigan',
  'bootes',
  'modigliani',
  'richard j. roberts',
  'seaborg',
  'adenosis',
  'rheumatoid arthritis',
  'gambia',
  'santo tomas',
  'infertility',
  'pait',
  'mark antony',
  'ambrogio damiano achille ratti',
  'pasimuno',
  'lindol',
  'percival lowell',
  'rebolusyong tsino',
  'cordon bleu manok',
  'balikuko',
  'engkantada',
  'william dudley haywood',
  'druid',
  'himukin',
  'bangko',
  'helen',
  'cassiopeia',
  'palo',
  'panchayet',
  'hilera',
  'saxe',
  'forseti',
  'dixie cup',
  'punong-tseri',
  'rodin',
  'vinegar joe stilwell',
  'helen hunt jackson',
  'punong-duhat',
  'port louis',
  'ngawa',
  'rebolusyon',
  'litre',
  'joe clark',
  'avogadro',
  'eastman',
  'oregon',
  'bray',
  'biskuwit',
  'repolyo',
  'richard lovelace',
  'pagbilog',
  'mubarak',
  'arthur neville chamberlain',
  'synge',
  'hothr',
  'charles de gaulle',
  'tombigbee ilog',
  'bohemian',
  'gitlapi',
  'belgian shepherd',
  '66',
  'pagpapalahi',
  'kalapati',
  'disyerto ng gibson',
  'w. b. yeats',
  'tandang pamangha',
  'a. noam chomsky',
  'sir tom stoppard',
  'eurasian woodcock',
  'washington',
  'gatas na evaporada',
  'japanese crab',
  'edouard manet',
  'taipei',
  'republika ng italya',
  'ike',
  'sitsang',
  'harris',
  'ika-labinwalo',
  'helleri',
  'pindar',
  'thompson',
  'tupa',
  'spencer',
  'tyne ilog',
  'pagkakaboto',
  'pliny the younger',
  'scottish lowlander',
  "duc d'elchingen",
  'jack nicklaus',
  'amon-ra',
  'g-force',
  'punan',
  'aire ilog',
  'magsumbong',
  'ponche',
  'viktor vasarely',
  'zironia',
  'wood',
  'cousteau',
  'general franco',
  'panganim na nota',
  'baron clive of plassey',
  ...})

## Load dictionaries

In [9]:
PATH_PINOYDICTIONARY = r"D:\thesis\dictionaries\pinoydictionary.json"
PATH_DIKSIYONARYOPH = r"D:\thesis\dictionaries\diksiyonaryoph.json"
PINOYDICTIONARY = pd.read_json(f"{PATH_PINOYDICTIONARY}", orient="index").index.tolist()
DIKSIYONARYOPH = pd.read_json(f"{PATH_DIKSIYONARYOPH}", orient="index").index.tolist()
PINOYDICTIONARY[:5], DIKSIYONARYOPH[:5]

(['aroskaldo', 'Aroy', 'arpa', 'Arsenic', 'arsobispado'],
 ['-a', 'A', 'A!', 'aa', 'aab'])

In [10]:
DICTIONARY_VOCAB = set(DIKSIYONARYOPH + PINOYDICTIONARY)

In [11]:
len(DICTIONARY_VOCAB)

89566

In [12]:
a = [x.lower() for x in DICTIONARY_VOCAB]
b = set(a)
len(a), len(b)

(89566, 89042)

In [13]:
len(a) - len(b)

524

In [14]:
# Ito yung mga duplicates na natanggal after lowercasing
A = pd.Series(a)
A.loc[A.duplicated()].values

array(['ta', 'in', 'senyorita', 'cr', 'metro', 'tandayag', 'bandalo',
       'ira', 'pet', 'arayat', 'tiboli', 'us', 'ayan', 'korte suprema',
       'misa', 'id', 'naga', 'holocaust', 'eta', 'pt', 'katipunan', 'pa',
       'hana', 'sm', 'hapon', 'si', 'ati', 'nasyonalista', 'lagda',
       'mama', 'merkuryo', 'musa', 'anti-cristo', 'olympian', 'bugan',
       'platon', 'dan', 'simbang-gabi', 'sinyor', 'silay', 'batute',
       'rhea', 'artiko', 'he', 'ga', 'be', 'sulod', 'halina', 'mg',
       'italyana', 'plato', 'miss', 'siyanga', 'maasin', 'isis', 'ala',
       'diyos', 'da', 'arsenic', 'pa', 'gothic', 'hintay', 'asap',
       'sambali', 'l', 'hudyo', 'kumpisal', 'ka', 'oleo', 'march', 'itay',
       'po', 'tagum', 'karaw', 'luneta', 'balagtas', 'hukluban',
       'indiyan', 'gat', 'balayan', 'panay', 'oho', 'bohol', 'nemesis',
       'sara', 'darangan', 'kastilaloy', 'siya', 'q', 'mesyas', 'lego',
       'tabi', 'nene', 'am', 'amalam', 'r', 'dagit', 'maykapal', 'ibabaw',
       'la', 'limited', 'tuloy', 'plamengko', 'senyor', 'sol', 'mag',
       'todos los santos', 'java', 'arabe', 'sim', 'adat', 'hala',
       'malay', 'balanga', 'pugutan', 'ingkong', 'china', 'karawagan',
       'atlas', 'pt', 'bugkalot', 'tagabili', 'o', 'luba', 'calvary',
       'sa kinauukulan', 'ginang', 'intramuros', 'tindig', 'abel',
       'ulandes', 'eukaristiya', 'hinto', 'mexican', 'tsinita', 'bikol',
       'pulahan', 'tabon', 'kataas-taasang hukuman', 'aluminum',
       'platino', 'no', 'pugu', 'iloilo', 'left', 'nanang', 'kumpil',
       'md', 'rom', 'n', 'pandakaki', 'manobo', 'balintawak', 'earth',
       'mo', 'saligang-batas', 'tartar', 'amen', 'boron', 'palawan',
       'labas', 'homo', 'me', 'istasyon', 'may', 'lipong', 'taan',
       'tubod', 'pm', 'antimony', 'lapulapo', 'lumikha', 'silang',
       'eskritura', 'bataan', 'g', 'nut', 'ba', 'gambong', 'asupre',
       'aro', 'tagaytay', 'who', 'balangaw', 'lot', 'ayun', 'at', 'sob',
       'nawa', 'catholicism', 'es', 'nasaan', 'sungsong', 'tungsten',
       'sugbo', 'tantalum', 'kalinga', 'mt', 'dip', 'rf', 'kalibo',
       'panginoon', 'lupa', 'ponce', 'iba', 'itu', 'kamahalan',
       'mesyaniko', 'leghorn', 'dolorosa', 'bakal', 'hayon', 'moloch',
       'radon', 'yama', 'australiano', 'pasipiko', 'plutonium',
       'walang-anuman', 'ilud', 'hali', 'silid', 'burma', 'misis',
       'albay', 'pahiyas', 'kurukya', 'cod', 'obo', 'mandarin', 'gabon',
       'estasyon', 'm', 'bathala', 'anunsiyasyon', 'hilat', 'abba', 'ca',
       'kang', 'mercury', 'ester', 'iwak', 'daphne', 'lapas', 'pingkian',
       'epiphany', 'korea', 'busaw', 'ilo', 'banaw', 'layo', 'kayumanggi',
       'y', 'bangan', 'morocco', 'oktubre', 'rusa', 'binyagan', 'ito',
       'mister', 'sb', 'tigilan', 'senyora', 'pahingi', 'eto', 'padre',
       'vandal', 'salubong', 'haba', 'holland', 'mabini', 'maano', 'alim',
       'batak', 'bisaya', 'talaga', 'uno', 'mago', 'pu', 'pontipise',
       'hudas', 'zonk', 'katalan', 'butuan', 'ilagan', 'eskosesa',
       'hindi', 'komulgatoryo', 'titanic', 'ali', 'hayan', 'katipunero',
       'apokalipsis', 'veronica', 'arab', 'hentil', 'siva', 'lipa',
       'kredo', 'nb', 'molibdenum', 'siya nawa', 'baluga', 'hayun',
       'notaryo publiko', 'karbon', 'yakan', 'kadaklan', 'san pablo',
       'malayo', 'metropolis', 'kano', 'kilat', 'kw', 'cd', 'tingga',
       'eksodo', 'fm', 'kalagan', 'bulan', 'am', 'makailan', 'dominiko',
       'alta', 'ayaba', 'car', 'ita', 'taal', 'kumintang', 'ma',
       'arktiko', 'ti', 'bungaw', 'ar', 'kahimanawari', 'amboy',
       'mamumugot', 'mananakop', 'olandes', 'balitok', 'malaya', 'ho',
       'op', 'luna', 'damolag', 'senyorito', 'ginto', 'usa', 'nanay',
       'duta', 'g-string', 'atm', 'cd', 'kalbaryo', 'c', 'presbyterian',
       'malyari', 'ms', 'simba', 'ostya', 'kabunyian', 'son', 'ba',
       'galaxy', 'litaw', 'eu', 'aleluya', 'mandaya', 'laon', 'kamatayan',
       'pm', 'digos', 'pasil', 'lapulapu', 'toto', 'palayan', 'penitente',
       'na', 'hitana', 'h', 'balatok', 'hudhud', 'ni', 'k', 'kama',
       'libra', 'nino', 'bagumbayan', 'batangan', 'ole', 'sm', 'moro',
       'fr', 'oo', 'turin', 'kaliwa', 'pr', 'antay', 'alpino', 'negro',
       'sugat', 'platinum', 'gotiko', 'red', 'kanser', 'akwaryo',
       'italic', 'as', 'ti', 'ko', 'tibag', 'round table', 'v', 'abulog',
       'halap', 'prolog', 'abayan', 'halo', 'pasyon', 'tiyera',
       'amerikana', 'castor', 'maganda', 'huli', 'narcissus', 'antipolo',
       'corregidor', 'manila', 'maya', 'ad', 'asoge', 'aroy',
       'lutong-makaw', 'aurora', 'tao', 'tahan', 'x-ray', 'poon', 'san',
       'laguna', 'p', 'tanso', 'haway', 'birhen', 'kawi', 'arya', 'eve',
       'ginoo', 're', 'palanan', 'turkey', 'kalookan', 'tb',
       'hukumang-militar', 'iraya', 'scripture', 'agyu', 'salt', 'tuwali',
       'belen', 'mati', 'adiyos', 'mataas na kapulungan', 'lu', 'nini',
       'dumagat', 'mam', 'neneng', 'nato', 'ola', 'bi', 'ng', 'balatik',
       'ipa', 'iris', 'nereid', 'bontok', 'huwag', 'bihang', 'hantay',
       'lumawig', 'ostia', 'opo', 'komunyon', 'tamsi', 'abra', 'trinidad',
       'x', 'ha', 'e', 'diana', 'alangan', 'balud', 'i', 'b', 'argon',
       'catholic', 'mugna', 'abaka', 'opertoryo', 'ida', 'habi', 'po',
       'araw ng paghuhukom', 'pasig', 'senakulo', 'pilar', 'dos',
       'hantik', 'th', 'sunday', 'larga', 'eden', 'gaddang', 'katoliko',
       'kb', 'linggo', 'mason', 's', 'itoy', 't', 'papa', 'sita', 'job'],
      dtype=object)

In [15]:
# Let's keep the deduplicated lowercased vocab
DICTIONARY_VOCAB = set([x.lower() for x in DICTIONARY_VOCAB])
len(DICTIONARY_VOCAB), DICTIONARY_VOCAB

(89042,
 {'gumasgas',
  'multimilyon',
  'mimyograp',
  'siga',
  'magpahula',
  'orthography',
  'pag-uulag',
  'mujeres publicas',
  'ugnayin',
  'disilusyon',
  'pamamandaw',
  'pagngasab',
  'pikhik',
  'calypso',
  'fundamentalism',
  'mabaghan',
  'kataleptiko',
  'makawili',
  'pagkasiphayo',
  'sirigelas',
  'snipe',
  'templo',
  'tickle',
  'nakatibong',
  'ngilag',
  'magkalmin',
  'katikya',
  'ipagbigay-sulit',
  'ulos',
  'humiging',
  'wala sa ugali',
  'likumin',
  'toilet',
  'auditin',
  'lazaret',
  'basuhan',
  'makalasap',
  'batong-sorlan',
  'iras',
  'lagwas',
  'panunaw',
  'palimbagan',
  'sarabsaban',
  'international court of justice',
  'bagnus',
  'paumbukin',
  'eksplorahin',
  'dayagdag',
  'buntunghininga',
  'uwiduhin',
  'beterana',
  'puket',
  'kabalyeriya',
  'split',
  'philippine pygmy woodpecker',
  'asean',
  'redeem',
  'pamamana',
  'magpasimula',
  'ayan',
  'lasong',
  'patangu-tango',
  'tweed',
  'klawsula',
  'funggus',
  'bakood',
  'tagbak',
  'arimuhan',
  'kotilyon',
  'ekspektorante',
  'pagkaudlot',
  'bigyang-hapis',
  'aripungsan',
  'loading',
  'vihud',
  'ekilibriyo',
  'sansala',
  'asado',
  'pagkatulig',
  'makapilit',
  'ulila',
  'paghusga',
  'kabron',
  'pungkay',
  'panunuklas',
  'horos',
  'filipinas',
  'napapaiba',
  'satchel',
  'talay',
  'kapisanan',
  'puol',
  'palawan hornbill',
  'mamukadkad',
  'aing. aing',
  'may mukhang tapat',
  'basalto',
  'paktaal',
  'tinali',
  'ulumbubong',
  'magbilang',
  'ay-ak',
  'adagio',
  'vessel',
  'gawiin',
  'hinuka',
  'marco',
  'magwaswas',
  'arag-arag',
  'kapanitulot',
  'palabigasan',
  'manlililok',
  'amperimetro',
  'mangumbida',
  'benepaktor',
  'aploramiyento',
  'pamighatiin',
  'sinturunan',
  'kukuam',
  'pagkamayamutin',
  'kisay',
  'ikanal',
  'laring',
  'magkakamukha',
  'tuwarik',
  'chat',
  'bogoy',
  'papag-',
  'manood',
  'papanumpain',
  'katayin',
  'sutea',
  'malay gooseberry',
  'tagaugit',
  'ngayon',
  'munga',
  'platonism',
  'adenitis',
  'pahaba',
  'nanak',
  'galauran',
  'isukbit',
  'pamumudbod',
  'barobankay',
  'pagpapadikit',
  'lamuyutin',
  'dress',
  'katre',
  'decor',
  'topcoat',
  'sihang magkapuno',
  'agogo',
  'balidbid',
  'prognosticate',
  'amotan',
  'umuka',
  'bumuli',
  'mahinain',
  'mountain province',
  'manlito',
  'osmiyum',
  'lelang',
  'umibag',
  'loko-loko',
  'contrition',
  'majorette',
  'lumublob',
  'kahimay',
  'sukong',
  'patalaan',
  'sidetrack',
  'hypotaxis',
  'ugaling mapagpatawa',
  'heir',
  'knapsack',
  'nagpapatunay',
  'kalaw-ay',
  'reorganisado',
  'sumapi',
  'honorable',
  'talatinigan',
  'magtsokolate',
  'neyurologis',
  'redentorist',
  'kontestant',
  'sebilyana',
  'kurus-kurus',
  'pakikidalamhati',
  'nagsusustento sa sarili',
  'butong',
  'kitse',
  'epistola',
  'kababata',
  'tumindi',
  'immediately',
  'amamayong',
  'bagayan',
  'kaumagahan',
  'naparool',
  'sab-it',
  'makaw',
  'atak',
  'talulung',
  'mauso',
  'liang',
  'kimey',
  'himunot',
  'rekisito',
  'krusyal',
  'masan',
  'lisbot',
  'karabana',
  'panghir',
  'pumugay ng dangal',
  'kota',
  'alocasia',
  'panlilisik',
  'balakiran',
  'pagdiriwang',
  'expansion',
  'special',
  'pleges',
  'tornilyuhan',
  'subhetibismo',
  'soul music',
  'kathambuhay',
  'sukot',
  'delikada',
  'pampropesyonal',
  'tungi',
  'bingo',
  'pagkakasal',
  'panibulusan',
  'magblangket',
  'agaas',
  'paalaman',
  'resibe',
  'tugunan',
  'pagpunit',
  'magpatagal',
  'buto',
  'ribal',
  'tilapon',
  'ulasiman',
  'subpoena',
  'bahay at paligid',
  'mabakas',
  'osyosera',
  'bulaon',
  'seleri',
  'rattle',
  'pagkamasumpungin',
  'fairyland',
  'lambayan',
  'piingin',
  'magpakawala',
  'motor',
  'kognisyon',
  'paghubli',
  'sense of hearing',
  'sestet',
  'kabiguan',
  'kilyawan',
  'mohammed',
  'hibla',
  'palingkuran',
  'pangalandakan',
  'tarima',
  'paumaga',
  'tulot',
  'paharapin',
  'lambak',
  'magtarato',
  'gelding',
  'alip-ip',
  'pangangayupapa',
  'komprometido',
  'gitang',
  'huyahoy',
  'pagsipot',
  'puyait',
  'sangkayaw',
  'ontologist',
  'banghik',
  'tagalsik',
  'dibidendo',
  'ama ng tahanan',
  'sariya',
  'pandiwaring pangalan',
  'lepes',
  'indulhente',
  'lisok',
  'bilang na likas',
  'grabedad',
  'lobas',
  'siyatika',
  'patakan',
  'bawal ang pumasok',
  'ekinoksiyo',
  'ipahilot',
  'limahir',
  'tangkas',
  'tagsip',
  'uliranin',
  'biniwang',
  'pakid',
  'mistle toe',
  'pembaba',
  'espedyente',
  'tugot',
  'kasapuwego',
  'lainer',
  'gasul',
  'ex officio',
  'pagbagayin',
  'bel canto',
  'accredit',
  'magkadamdamin',
  'gawa ng katandaan',
  'bakla',
  'maturuan',
  'informant',
  'pakwan',
  'palitek',
  'sais',
  'pandaras',
  'glycerol',
  'butterfly tree',
  'pagkabuwal',
  'inuming pampagana',
  'kagaya',
  'intau',
  'ninya',
  'statute',
  'lintang-kati',
  'ulcer',
  'kamot-pusa',
  'makarag',
  'water mill',
  'panloloko',
  'kiyam',
  'magdeklama',
  'di-masyado',
  'salicin',
  'papagtipirin',
  'golpe de estado',
  'namomot-an',
  'ectopic',
  'antrasita',
  'biraddali',
  'simplihan',
  'mag-iikmo',
  'autonomous region in muslim mindanao',
  'araucaria',
  'dagaldal',
  'eksplotasyon',
  'mesolithic',
  'kulaing',
  'functionalism',
  'magaw',
  'bromine',
  'nagsa-',
  'saligawsaw',
  'sibukaw',
  'gaano',
  'apnit',
  'malic acid',
  'pamagay',
  'basikaw',
  'resistance',
  'tungod',
  'pamumugto',
  'barna',
  'labutaw',
  'tagabang',
  'makalungkot',
  'kagiginawa',
  'gladyador',
  'xanthippe',
  'pagpatay',
  'kapantay',
  'hampol',
  'kapoy',
  'tupig',
  'kiyew',
  'nakagiginhawa',
  'spell',
  'mamuka',
  'paluin',
  'pagpapalaya',
  'dumala',
  'pakikipagtalo',
  'bunton',
  'mabarahan',
  'amerikana',
  'dilema',
  'mangagsipagpaka-',
  'talob',
  'daoy',
  'medyano',
  'obscurant',
  'gangkuling',
  'sawaan',
  'samyo',
  'gadgaran',
  'patrol',
  'komemorasyon',
  'pangahas',
  'kayetana',
  'binudyaan',
  'great',
  'santaon',
  'kinsol',
  'corset',
  'awanging tubo',
  'ban',
  'disability',
  'stepfather',
  'subscriber',
  'treasurer',
  'karis-karis',
  'bulid',
  'depdep',
  'hagyo',
  'stoup',
  'opsiyon',
  'makinang pantaas',
  'tongue',
  'walang-kaba',
  'komandante',
  'garapon',
  'inept',
  'huragok',
  'paris',
  'kolon',
  'salambay',
  'kaiihi',
  'tolan',
  'katabing-katabi',
  'ilahok',
  'pagpapantig',
  'zebulun',
  'pamatid-uhaw',
  'acknowledgement',
  'pagsuri',
  'singkat',
  'tobiyar',
  'antonym',
  'baysak',
  'pangangamkam',
  'naaaninaw',
  'etsetera',
  'pananangis',
  'matabang',
  'patalim',
  'windang ang puso',
  'hatid-dumapit',
  'monk',
  'vunnay',
  'pamudbod',
  'magremedyo',
  'diyatomea',
  'grosero',
  'andiyan',
  'slash',
  'barena',
  'dalopana',
  'fill',
  'lalakinin',
  'probation',
  'delusibo',
  'mag-aribaybaho',
  'testament',
  'ihiyenista',
  'blilo',
  '-philia',
  'maggraun',
  'ap-ap',
  'alinsangan',
  'kawikaan',
  'outer',
  'paghuwad',
  'kasikismo',
  'pitandaan',
  'tabangan',
  'gute',
  'emorahiya',
  'guluguran',
  'mag-itim',
  'tohol',
  'ipso facto',
  'follicle',
  'ngaringari',
  'barihay',
  'lonaw',
  'second class',
  'matagtag',
  'garahahan',
  'anam',
  'handbag',
  'pundado',
  'kahiyang',
  'ampo',
  'mananahi',
  'pusupuso',
  'panletson',
  'bronchopneumonia',
  'mamburaw',
  'kalahating oras',
  'alakdan',
  'walang-lingon-likod',
  'mag-entra',
  'sintas ng sapatos',
  'trooper',
  'sabunganay',
  'mekapan',
  'makapasa',
  'magkahawig',
  'kopkopeyes',
  'monogram',
  'zooplankton',
  'employment',
  'bitling',
  'necessity',
  'sagkod',
  'agnan',
  'maglabulabo',
  'nakahahalina',
  'kulalangaw',
  'mangawud',
  'buhangin',
  'mayapis',
  'papaitan',
  'mamukto',
  'nip',
  'kargahan',
  'burlap',
  'parrot leaf',
  'kalahan',
  'habag',
  'trahiko',
  'tumigil',
  'mailawan',
  'tabubok',
  'tastas',
  'magpasinga',
  'bilang monumento',
  'hilabos',
  'kalumniyador',
  'pakilatisan',
  'sarikaya',
  'bentrikulo',
  'ipoteka',
  'hotel',
  'iwagwag',
  'sustansiya',
  'lukuhin',
  'pilduras',
  'miyel',
  'ekstrahudisyal',
  'langkoban',
  'table cloth',
  'epaulette',
  'mandaraya',
  'alupayi',
  'prop',
  'kagaanan ng loob',
  'depositong inang-bato',
  'duwa-duwa',
  'intersesor',
  'kamaoo',
  'ipul',
  'lukluk',
  'karbonipero',
  'pumagba',
  'blockhouse',
  'bugbugan',
  'baringkuwas',
  'harm',
  'notaryo',
  'giti',
  'naos',
  'rebel',
  'lunaw',
  'alan',
  'libingan ng santo',
  'tiranya',
  'itutop',
  'libidinous',
  'alak-alakan',
  'lukob',
  'balu',
  'waterproof',
  'paglalagis',
  'kwekkwek',
  'maramdaman',
  'pormularyo',
  'mapaos',
  'laspag',
  'ganting-loob',
  'kabusugan',
  'lumikot',
  'transmitter',
  'nameplate',
  'tibagan ng bato',
  'lebadura',
  'ipasiya',
  'kasubsob',
  'dreamboat',
  'sisiw na pato',
  'forthcoming',
  'kamatisan',
  'mapakinabangan',
  'hawaii',
  'pagkakahanay',
  'kalukati',
  'pangaita',
  'makroekonomiya',
  'takamin',
  'alas-as',
  'united nations institute for training and research',
  'notch',
  'magpati-',
  'mainsultuhan',
  'biretta',
  'tinangkulo',
  'alambike',
  'ginulay',
  'medication',
  'wide-open',
  'lutak',
  'huho',
  'sangsang',
  'wadwad',
  'wholesome',
  'kakwak',
  'pagsisiyam',
  'kasasapitan',
  'magtruck',
  'nuthatch',
  'itaban',
  'kaadelantaduhan',
  'kulasyon',
  'beinte',
  'busoran',
  'pakainin',
  'yabo',
  'panggasi',
  'kagu',
  'pag-engganyo',
  'digmaang sibil',
  'arkabus',
  'rupeke',
  'balanghay',
  'tunggo',
  'akong-tapon',
  'pagbilugan',
  'okultismo',
  'luran',
  'talusok',
  'pag-initan',
  'elektro-',
  'maiiba',
  'water lettuce',
  'amino acid',
  'balukas',
  'markador',
  'bahay-pangaserahan',
  'nationalism',
  'rinoseronte',
  'bumalanya',
  'magpatiwakal',
  'kuping',
  'pagdami',
  'kubiko',
  'absolutismo',
  'maani',
  'mabasag',
  'espiritwalisasyon',
  'langbu',
  'ligway-ligway',
  'voluntary',
  'ditensiyon',
  'para sa akin',
  'telebanking',
  'retrato',
  'benefactor',
  'magalingin',
  'pultigo',
  'useless',
  'walang-kakibu-kibo',
  'lambungan',
  'magsabong',
  'baroto',
  'plaintiff',
  'ternaryo',
  'pangakuan',
  'ayu',
  'thousand',
  'barayung',
  'di-pagkakatugunan',
  'maharot',
  'axil',
  'hagom',
  'paghahalikwat',
  'magpaluto',
  'mabutas',
  'sobresalyente',
  'kasunduin',
  'kakanluranan',
  'presas',
  'tradisyonal na politiko',
  'lusbel',
  'bingki',
  'gapogop',
  'semarang',
  'accelerando',
  'tiil',
  'sapin sa paa',
  'ehong',
  'nido',
  'sidha',
  'tentakulo',
  'salya',
  'kawl',
  'flight',
  'kalimusta',
  'duchess',
  'tanda ng pagdaragdag',
  'kredits',
  'pirata',
  'ipabagahe',
  'fake',
  'hinihingi ng regulasyon',
  'hibay',
  'pinakamalakas',
  'maghalal',
  'realismong sosyalista',
  'gawaran',
  'baile',
  'usisera',
  'sinangayan',
  'nakalulula',
  'pahagkan',
  'tatuwaan',
  'hentil',
  'hilurin',
  'dryad',
  'stockpile',
  'paggaak',
  'paldong',
  'embryologist',
  'pabula',
  'baduya',
  'alman',
  'proxemics',
  'higdulin',
  'empower',
  'paglagubluban',
  'malikmata',
  'bulungol',
  'denas',
  'irarom',
  'pagkabulalas',
  'engkantada',
  'alibadbaran',
  'elektromagnetiko',
  'ikigtel',
  'trompa ng elepante',
  'helen',
  'era',
  'kasubang-aso',
  'kirbas',
  'soberano',
  'gilong',
  'binanlok',
  'luggage',
  'granite',
  'tibog',
  'ipagkasundo',
  'octave',
  'rancher',
  'imbiyerno',
  'mimisam',
  'drachm',
  'tempera',
  'mag-ungot',
  'humarok',
  'publishing',
  'likya',
  'maghirap sa sakit',
  'naladaw',
  'panual',
  'lusay',
  'palampinan',
  'sid-ok',
  'asnuk',
  'makasundo',
  'lingka',
  'prize',
  'mamusa',
  'identipika',
  'pampatapang',
  'yamot',
  'pag-aalangan',
  'potential difference',
  'sakanian',
  'tungkaban',
  'pandagan',
  'sign language',
  'mapanghalata',
  'pantal',
  'foot pound',
  'paguwa',
  'arteriole',
  'pansenado',
  'garapal',
  'dosel',
  'himbubuyog',
  'glassware',
  'sanggir',
  'poach',
  'makayamot',
  'buhid',
  'federal',
  'tagsalat',
  'bantak',
  'bugwak',
  'mataimtim',
  'thyroid gland',
  'magbigay-dahilan',
  'bikariya',
  'wood',
  'gislot',
  'nene',
  'uya',
  'gangat',
  'hating-globo',
  'kaktel',
  'mibi',
  'maniwala',
  'makapitan',
  'pagpatak-patak',
  'tinahero',
  'buong puso',
  'parpala',
  'pasteboard',
  'gimata',
  'deppel',
  'tumigagal',
  'hors concours',
  'biribid',
  'dissection',
  'hayopag',
  'higit na kakaunti',
  'pagtiwalaan',
  'lagukin',
  'mayupi',
  'prostitusyon',
  'magkabi-kabila',
  'arabal',
  'walang-isip',
  'inhenyoso',
  'biska',
  'meil',
  'memorisasyon',
  'kaburukan',
  'sangkaterba',
  'suction',
  'anglikanismo',
  'trochee',
  'niobium',
  'karabaw',
  'pagkamuot',
  'dalabasa',
  'iket',
  'lutong-makaw',
  'progress report',
  'borador',
  'pakalkal',
  'immaculate',
  'pingkaw',
  'gintago',
  'pipit',
  'pag-iskursyunan',
  'kelp',
  'premarital',
  'pangadlit',
  'kamantilis',
  'darayaw',
  'mapakislot',
  'mapangiwi',
  'mapagkunuwa',
  'pampasarap',
  'todohin',
  'alubaybay',
  'matang-bukaw',
  'di-tumpak',
  'ulas',
  'kawalang-ingat',
  'laka',
  'parnuway',
  'napangilakan',
  'intensyon',
  'pa-weng',
  'structural',
  'driver',
  'living',
  'caucasian',
  'alumbre',
  'anthropomorphic',
  'bariya',
  'sinapismo',
  'hibangbang',
  'peggad',
  'mesias',
  'crystalline',
  'pagkalibumbunan',
  'magkanya-kanya',
  'pagngulngol',
  'sub rosa',
  'mangungulot',
  'paugatan',
  'bandiran',
  'sakristan-mayor',
  'pagmura',
  'deltoid',
  'malamang',
  'albo',
  'outside',
  'pulpulin',
  'magyangyang',
  'apiap',
  'kubil',
  'pananabik',
  'ang-ang',
  'supok',
  'kunog-kunog',
  'laob',
  'matumbok',
  'panuya',
  'deduction',
  'mons veneris',
  'game',
  'espuwerso',
  'dungga',
  'palinga-linga',
  'paglilikom',
  'sightseer',
  'printer',
  'inalaman',
  'stutter',
  'balikhay',
  'pagkakatali',
  'debutant',
  'kulugo',
  'ex-',
  'pagkamababang-loob',
  'wikang panturo',
  'kahista',
  'professor',
  'mag-ayuno',
  'panalandak',
  'vorticella',
  'esperiment',
  'sambali',
  'pambutas',
  'pampabata',
  'magsalat',
  'deskribe',
  'heograpiko',
  'relokasyon',
  'kritika',
  'meskita',
  'pang-epekto',
  'bodyguard',
  'lemer',
  'nagsasabula',
  'probation period',
  'delusion',
  'haplit',
  'mangisay',
  'hulihin',
  'inggu',
  'kastelyano',
  'isometrics',
  'elektrisado',
  'pin',
  'irrigation',
  'kalahatiin',
  'salaginto',
  'omnisapient',
  'pahurahin',
  'tuwi-tuwi na',
  'pumadyak',
  'pagnanais',
  'bukaka',
  'perhuwisyo',
  'bayabag',
  'cinnamon',
  ...})

# Experiments

## 1. Get the intersection of BORRA and DICTIONARIES

In [16]:
BORRA_U_DICTIONARY = BORRA_VOCAB.intersection(DICTIONARY_VOCAB)
RATIO = (len(BORRA_U_DICTIONARY) / len(DICTIONARY_VOCAB)) * 100
RATIO, len(BORRA_U_DICTIONARY)

(4.60232249949462, 4098)

In [17]:
BORRA_VOCAB.difference(BORRA_U_DICTIONARY)

{'kriminologist',
 'carrere',
 'antropolohista',
 'regiomontanus',
 'apatnaput-siyam',
 'victoria land',
 'harrison',
 'eysenck',
 'saone ilog',
 'mark wayne clark',
 'cellini',
 'cristobal colon',
 'linnaeus',
 'pitt',
 'ika-labing-anim',
 'pukol sa bola',
 'cervantes saavedra',
 'dean gooderham acheson',
 '29',
 'walang kabuluhan',
 'praga',
 'zilyon',
 'edward jenner',
 '69',
 'august strindberg',
 'kentucky bluegrass',
 'sibelius',
 'manat',
 'pantothenic acid',
 '155',
 'santo dominic',
 'al-hasan ibn al-haytham',
 'hugo junkers',
 'maxwell anderson',
 'malik',
 'xylose',
 'william henry pratt',
 'thetis',
 'rabis',
 'bath asparagus',
 'sessions',
 'pamilyang xenopodidae',
 'fighting joe hooker',
 'sitwell',
 'boulez',
 'babe ruth',
 'natural siyensiya',
 'repormer',
 'jefferson',
 '89',
 'sojourner truth',
 'cyrillic',
 'ashtoreth',
 'fire_and_brimstone',
 'giosue carducci',
 'xerophyllum',
 'guangzhou',
 'djibouti franc',
 'xavier',
 'loire',
 'tetragrammaton',
 'edward morley',
 'punung-kahoy',
 'nalaho',
 'asa gray',
 'crossbeam',
 'dalawamput-dalawa',
 'i thessalonians',
 'leo xiii',
 'grappelli',
 'willebrand',
 'crouse',
 'araw ng kalayaan ng texas',
 'aten',
 'aleksandr i. solzhenitsyn',
 'ika-dalawapu',
 'pasteur',
 'willard frank libby',
 'klotho',
 'daniel chester french',
 'iceland',
 'dorothy leigh sayers',
 'el salvador',
 'air terminal',
 'greta louisa gustafsson',
 'laurence sterne',
 'belleau wood',
 'bantu',
 'angus frank johnstone wilson',
 'carbon paper/ papel na karbon',
 'pagdugo',
 'utug',
 'walter reed',
 'theodore roosevelt',
 '11',
 'fuentes',
 'charles franklin peirce',
 'ichthyologists',
 'prince fumimaro konoye',
 '73',
 'doric order',
 'george edward moore',
 'arthur symons',
 'friedrich anton mesmer',
 'p. p. von mauser',
 'pagkaing aso',
 'typhoid fever',
 'timog kanlurang namibia',
 'somme',
 'jinx',
 'johann christoph friedrich von schiller',
 'belgian franc',
 'osaka bay',
 'darnan',
 'dame myra hess',
 'daniel ortega saavedra',
 'benjamin jonson',
 'andrea mantegna',
 'saint baeda',
 'vargas',
 'ian wilmut',
 'theta',
 'glee club',
 'saint john',
 'emmett kelly',
 'taga-obserba',
 'stairwell',
 'drip coffee',
 'eos',
 'ika-dalawandaan',
 'lorenz',
 'maurice chevalier',
 'jane fonda',
 'robert adam',
 'mel gibson',
 'vidal',
 'hugo alvar henrik aalto',
 'de bakey',
 'apatnaput-walo',
 'nergal',
 'gb',
 'ilog allegheny',
 'xnthophyceae',
 'don ilog',
 'earl warren',
 'borges',
 'indian chief',
 '16th',
 'arab chief',
 'second earl of guilford',
 'walton',
 'genus xiphias',
 'tagamanman',
 'spark lever',
 'bahai',
 'niger ilog',
 'zane grey',
 'menepos',
 'adi granth',
 'frank philip stella',
 'irving',
 'borgia',
 'type a',
 'francisco jose de goya y lucientes',
 'jimenez',
 'lachesis',
 'ika-siyamnapo',
 'benton',
 'selene',
 'lozier',
 'natalie wood',
 'dogcart',
 'rhein',
 'santo john',
 'ezra pound',
 'allen tate',
 "democratic people's republic of korea",
 'hamilton',
 'james whitcomb riley',
 'benjamin peirce',
 'xiphiidae',
 'tarawa',
 'seaborgium',
 'ninkhursag',
 'grieg',
 'airdock',
 'north platte ilog',
 'ohio',
 'niger',
 'dean acheson',
 'chari',
 'punong-papaya',
 'thomas j. hanks',
 'dyirap',
 'aleksandr prokhorov',
 'condorcet',
 'sinuoan',
 'st. andrew',
 'peirce',
 'kanser sa pantog',
 'sir john gielgud',
 'aglalarawan',
 'w. somerset maugham',
 'golpo ng california',
 'austral',
 'jacobi',
 'ethel waters',
 'makina ng kotse',
 'william wycherley',
 'charles i',
 'acquaintance',
 '55th',
 'edward lee thorndike',
 'van de graaff',
 '65',
 'sami',
 'john reed',
 'julius erving',
 'kremang soda',
 "o'connor",
 'fat waller',
 'fernand leger',
 'benvenuto cellini',
 'vladimir kosma zworykin',
 'marso 2',
 'droning',
 'bartok',
 'princess of wales',
 'jordanian dinar',
 'bourdon',
 'tucana',
 'astrolyabya',
 'kipot ng georgia',
 'nintu',
 'stockton',
 'chuck berry',
 'mebibyte',
 'siyamnaput-siyam',
 'elmore john leonard',
 'donne',
 'balaton',
 'rankin',
 'sir henry rider haggard',
 'putin',
 'thoms huxley',
 'algernon charles swinburne',
 'isla ng bahrain',
 'burbage',
 'systemic lupus erythematosus',
 'r. j. mitchell',
 'edwin powell hubble',
 'test driver',
 'iris pallida',
 'bogota',
 'conakry',
 'ika-isandaan at limampu',
 'y-kromosom',
 'bulgarian',
 'rio de la plata',
 'jean anouilh',
 'leibnitz',
 'genus cyclops',
 '26th',
 'wilder',
 'richard_upjohn',
 'book_of_joshua',
 'henry valentine miller',
 'terence',
 'jimmy doolittle',
 'haeckel',
 'earl of warwick',
 'japanese angelica tree',
 'richard phillips feynman',
 'howard hughes',
 'opurtunismo',
 'wisonsin river',
 'bobby jones',
 'ramman',
 'genus xerobates',
 'johann muller',
 'pamamaluktot',
 'ira gershwin',
 'ika-20 siglo',
 'ika-anim',
 'robert ranke graves',
 'ieoh_ming_pei',
 'taft',
 'milne',
 'astarte',
 'erik satie',
 'punong-limon',
 'gorki',
 'ernest rutherford',
 'john thomas scopes',
 'taga-mongolia',
 'lamun',
 'king crab',
 'montez',
 'tiga-araro',
 'maupassant',
 'villon',
 'microbiologist',
 'mosander',
 'bill mauldin',
 'sir edward william elgar',
 'henrik johan ibsen',
 'indian rupee',
 'richard john roberts',
 'tanzania',
 'kandinsky',
 'old high german',
 'czech',
 'nellie ross',
 'timothy francis leary',
 'pan american union',
 'kentucky yellowwood',
 'romberg',
 'chamaeleon',
 'lugosi',
 'surboard',
 'hess',
 'zsigmondy',
 'william tecumseh sherman',
 'general charles de gaulle',
 'john smith',
 'james henry leigh hunt',
 'jan amos komensky',
 'ruth st. denis',
 'smetana',
 'carl nielsen',
 'brahmaputra',
 'kolkata',
 'oenomel',
 'bulkan st. helens',
 'kordofan',
 'thespis',
 'fyodor mikhailovich dostoyevsky',
 'goncourt',
 'tate',
 'stephanie graf',
 'gloria may josephine svensson',
 'rivera',
 'pierre curie',
 'ika-labing-apat',
 'emile zola',
 'toulouse-lautrec',
 'karanasa',
 '88',
 'nixon',
 'first earl wavell',
 'dorothy dix',
 'jeroboam_i',
 '22',
 'euler',
 'jack frost',
 'marian anderson',
 '44',
 'kyrgyzstan',
 'james hargreaves',
 'satie',
 'lee yuen kam',
 'sinclair',
 'asamiya',
 'president van buren',
 'algerian monetary unit',
 'peter pan collar',
 'chester alan arthur',
 'book_of_nahum',
 'gallaudet',
 'tekstuwal',
 'rheumatoid arthritis (ra)',
 'helen of troy',
 'oktosilabik',
 'lithuanian',
 'turki',
 'elinor morton hoyt wylie',
 'neapolitan na surbetes',
 'platte ilog',
 'mari',
 'zambezi',
 'genus xyphophorus',
 'hobbs',
 'whittier',
 'gustav mahler',
 'henrik ibsen',
 'bernard',
 'cervantes',
 'pepsi',
 'accuracy',
 'whitney',
 'willem de sitter',
 'dwight filley davis',
 'gabriel lippmann',
 'tashmitum',
 'boy orator of the platte',
 'monrovian',
 'flory',
 'deng xiaoping',
 'obra-maestro',
 'barbados',
 'machiavelli',
 '11th',
 'roseau',
 'president john quincy adams',
 'dalmatian iris',
 'baron karl wilhelm humboldt',
 'statistiko',
 'hippolyte jean giraudoux',
 'blair',
 'eks-ray film',
 'burundi franc',
 'po ilog',
 'sergei sergeyevich prokofiev',
 '55',
 'coolidge',
 'hank williams',
 'edouard vuillard',
 'wyat',
 'julia evelina smith',
 'oxford english dictionary',
 'won',
 'payakang pangungusap',
 'sir thomas wyatt',
 'pediculosis',
 'idaho',
 'steller',
 'joseph mccarthy',
 'middle low german',
 'kuzets',
 'scott',
 'leger',
 'ouse ilog',
 'gordie howe',
 'clara josephine schumann',
 'alpabetong armenyo',
 'inuming tubig',
 'varese',
 'allegheny',
 'donizetti',
 'hilaw na gatas',
 'ithunn',
 'serdica',
 'arthur edwin kennelly',
 'pedro calderon de la barca',
 'enesco',
 'drinking water',
 'douglas macarthur',
 'boltzmann',
 'munro',
 'innocent xi',
 'katakutan sa mga bading',
 'captain john smith',
 'lennox robinson',
 'vernier',
 'augustine',
 'kenzo_tange',
 'isaac newton',
 'takong manok',
 'first marquess cornwallis',
 'dame edit sitwell',
 'taga-syria',
 'erving',
 'mark anthony',
 'molech',
 'john donald budge',
 'thomas carlyle',
 'benin',
 'grigori potyokin',
 'meuse-argonne operation',
 'book of mormon',
 'steinmetz',
 'grub street',
 'kapeng irish',
 'byelorussian',
 'hellman',
 'louis_henry_sullivan',
 'emerson',
 'richard kuhn',
 'book_of_exodus',
 'katakutan sa mga pusa',
 'argonne',
 'auto accessory',
 'tagasapatos ng kabayo',
 'radhakrishnan',
 'marvin neil simon',
 'avon',
 'sinulok',
 'charles schulz',
 'harold nicolson',
 'stanley baldwin',
 'scopes',
 'bengali',
 'sir robert walpole',
 'geryon',
 'jeroboam',
 'stephen butler leacock',
 'justinian the great',
 'trevino',
 'italo calvino',
 'bessie smith',
 'yasser arafat',
 'thomas moore',
 'liberia',
 'joseph ben matthias',
 'william mckinley',
 'angolan monetary unit',
 'sir william gilbert',
 'tsinong parol',
 'metis',
 'jomo kenyata',
 'ivan sergeevich turgenev',
 'parte ng katawan',
 'kyoto',
 'gentleman johnny',
 'mohammed_ali',
 'carlos chavez',
 'alfred damon runyon',
 'heilong',
 'washington irving',
 'albers',
 'liryo ng michigan',
 'metical',
 'bundok tacoma',
 'john barth',
 'de la mare',
 'samoyed',
 'kanal na hinggil sa sustansya',
 'ornamento',
 '29th',
 'ereshkigel',
 'okteyn',
 'mark clark',
 'malay peninsula',
 'maputing russian',
 'augustus',
 'adapa',
 'benedict',
 'belgium',
 'baudelaire',
 'laney',
 'chu kiang',
 'taga-orissa',
 'micheas',
 'lyman frank brown',
 'poitier',
 'diyos ng mga semitiko',
 'charles franklin kettering',
 'gurkha',
 'wac',
 'haiti',
 'boddhisatva',
 'x-linked dominant inheritance',
 'genus xylocopa',
 'folie',
 'george orwell',
 'nikaragua',
 'oates',
 'pagtakinin',
 'cystic fibrosis',
 'epidemiologist',
 'mandelshtam',
 'wodehouse',
 'diskarte',
 'styron',
 '83',
 'aire',
 'bernd heinrich wilhelm von kleist',
 'respetado',
 'chickenfeed',
 'great sandy desert',
 'genus euterpe',
 'sidonie-gabrielle claudine colette',
 'excrescence',
 'prankisiya',
 'augusta',
 'john kenneth galbraith',
 'john steinbeck',
 'dubya',
 'ununpentium',
 'scolopax rusticola',
 'en-lil',
 'carl gustaf mossander',
 'cabot',
 'heinrich hertz',
 'naira',
 'romanian monetary unit',
 'russel crouse',
 'bernard law montgomery',
 'theodore samuel williams',
 'mary wollstonecraft',
 'bertrand russell',
 'calypso bulbosa',
 'roger sessions',
 'mocha coffee',
 'kontinente ng antarctic',
 'oswald veblen',
 'beauvoir',
 'david roland smith',
 'langmuir',
 'thomas kid',
 'incomplete fracture',
 'dostoyevsky',
 'bedrich smetana',
 'anne sexton',
 '100',
 'silangang germany',
 'halden',
 'aleksandr nikolayevich scriabin',
 'bellerophon',
 'taga-akay',
 'azerbaijan',
 'xanthelasma',
 'ben sira',
 'racine',
 'jerome kern',
 'e. t. a. hoffmann',
 'grover cleveland',
 'spillane',
 'george washington goethals',
 'mendeleev',
 'kasai ilog',
 'francis scott key fitzgerald',
 '46th',
 'eating disorder',
 'fridtjof nansen',
 'niagara',
 'st. george',
 'william sydney porter',
 'van der waals',
 'santo jude',
 'tagadisenyo',
 'exec',
 'xanax',
 'morrigan',
 'modigliani',
 'richard j. roberts',
 'seaborg',
 'adenosis',
 'rheumatoid arthritis',
 'santo tomas',
 'infertility',
 'mark antony',
 'ambrogio damiano achille ratti',
 'percival lowell',
 'rebolusyong tsino',
 'cordon bleu manok',
 'william dudley haywood',
 'druid',
 'cassiopeia',
 'panchayet',
 'saxe',
 'dixie cup',
 'forseti',
 'punong-tseri',
 'rodin',
 'vinegar joe stilwell',
 'helen hunt jackson',
 'punong-duhat',
 'port louis',
 'joe clark',
 'litre',
 'avogadro',
 'eastman',
 'oregon',
 'bray',
 'richard lovelace',
 'mubarak',
 'arthur neville chamberlain',
 'synge',
 'hothr',
 'charles de gaulle',
 'tombigbee ilog',
 'bohemian',
 'belgian shepherd',
 '66',
 'disyerto ng gibson',
 'w. b. yeats',
 'tandang pamangha',
 'a. noam chomsky',
 'sir tom stoppard',
 'eurasian woodcock',
 'washington',
 'gatas na evaporada',
 'japanese crab',
 'edouard manet',
 'taipei',
 'republika ng italya',
 'ike',
 'sitsang',
 'harris',
 'ika-labinwalo',
 'helleri',
 'thompson',
 'spencer',
 'tyne ilog',
 'pagkakaboto',
 'pliny the younger',
 'scottish lowlander',
 "duc d'elchingen",
 'jack nicklaus',
 'amon-ra',
 'g-force',
 'aire ilog',
 'ponche',
 'viktor vasarely',
 'zironia',
 'cousteau',
 'general franco',
 'panganim na nota',
 'baron clive of plassey',
 'william congreve',
 'edgar rice burroughs',
 'william henry harrison',
 'kurt waldheim',
 'malvina hoffman',
 'unibersidad ng texas',
 'hans christian oested',
 'joseph deems taylor',
 'bleat',
 'sigmund freud',
 'maria luigi carlo zenobio cherubini',
 'reykjavik',
 'islamabad',
 'oscar hammerstein ii',
 'charles louis napoleon bonaparte',
 'amy lowell',
 'sumisidhi',
 'cat valium',
 'remote control',
 'magrason',
 'trifoliate',
 'housatonic ilog',
 'bitamina b3',
 'kaspar friedrich',
 'kenneth roberts',
 'kathryn elizabeth smith',
 'santo benedict',
 'dumaan na nota',
 'stanley frank musial',
 'isle of man',
 'i peter',
 'charles lutwidge dodgson',
 'ika-apatnapu siyam',
 'louis eugene felix neel',
 'triangulum australe',
 'frederico garcia lorca',
 'postmark',
 'untermeyer',
 'pecos',
 'nazi party',
 'alpabetong griyego',
 'drone',
 'thiamin',
 'faulkner',
 'pag-aalsang sepoy',
 'john constable',
 'sir herbert beebohm tree',
 'nilagang karne',
 'imperyong byzantine',
 'georges clemenceau',
 'harpy',
 'john simmons barth',
 'weary willie',
 'lloyd',
 'pyxis',
 'voznesenski',
 'isang daan at labing lima',
 'l. s. lowry',
 'euripides',
 'christie',
 'vasco da gamma',
 'john james audubon',
 'celt',
 'john tyler',
 'cherubini',
 'barbary na pirata',
 'h. l. mencken',
 'pengo',
 'paragway',
 'allen ginsberg',
 'karlfeldt',
 'coats land',
 'malamyang hangin',
 'algren',
 'ilog caloosahatchee',
 'regbi',
 'moo',
 '52',
 'william jefferson clinton',
 'nevil shute',
 'thomas bradley',
 'ilog sabine',
 'samnite',
 'darius milhaud',
 'morris chair',
 'fukuoka',
 'jacques anatole francois thibault',
 'genus xylopia',
 'grace kelly',
 '39th',
 'homer a. thompson',
 'pompey',
 'balik-tipon',
 'areopagus',
 'antonio lucio vivaldi',
 'texas longhorn',
 'masikat',
 'heavenly jewel',
 'demitasse',
 'donald barthelme',
 'limpopo',
 'woodward',
 'binet',
 'edward albee',
 'steen',
 'manson',
 'pyotr tchaikovsky',
 'jakob bernoulli',
 'moore',
 'alice paul',
 'sangkapat na nota',
 'indira gandhi',
 'john haldane',
 'pigat',
 'hantingin',
 'seleucus i',
 'torah',
 '57',
 'james_wyatt',
 'dubnium',
 'jan hendrix oort',
 'markova',
 'genus xenicus',
 'australya',
 'baron hermann ludwig ferdinand von helmholtz',
 'jersey lillie',
 'st. nick',
 'ika-isandaan at apatnapu',
 'christine marie evert',
 "ch'in shih huang ti",
 'a. conan doyle',
 'cosine',
 'anton bruckner',
 'chattahoochee ilog',
 'andrea_palladio',
 'rappahannock',
 'zoological siyensya',
 '47th',
 'tormento',
 'wilbur wright',
 'sunami',
 'kettering',
 'dutch leonard',
 'pampagkain',
 'ralph ellison',
 'xerophthalmia',
 'defect of speech',
 'hukbong inhinyero',
 'billy graham',
 'tagadurog',
 'jagganath',
 'president taft',
 'gaius valerius catullus',
 'daniel defoe',
 'hegelian',
 'baging-kiwi',
 'nasyonal librerya na panggagamot ng u.s',
 'hector hugh munro',
 'sir_christopher_wren',
 'paul vernier',
 'mark twain',
 'carnegie',
 'president monroe',
 'baron hugh caswall tremenheere dowding',
 'mag-skate',
 'dawalamput-siyam',
 'burkina faso',
 'siyamnaput-dalawa',
 'bel-merodach',
 'seleucus',
 'mickey finn',
 'ogden',
 'dalmatian pyrethrum',
 'lysenko',
 'st. simon',
 'peleus',
 'ramachandra',
 'count ferdinand von zappelin',
 'sisantihin',
 'riley b king',
 'st. denis',
 'saint john ilog',
 'bernard baruch',
 'sir joshua reynolds',
 'katakutan sa daga',
 'pantothen',
 'pierre boulez',
 'aleksandr mikjailovich prokhorov',
 'bavarian cream',
 'bundok rushmore',
 'schumpeter',
 'mary mcleod bethune',
 'cimarron',
 'robert anson heinlein',
 'potemkin',
 'degree fahrenheit',
 'fizz',
 'andhra pradesh',
 'sir william huggins',
 'borshch',
 'meyerbeer',
 'napoleon iii',
 'rudolf wurlitzer',
 'vinson',
 'daimler',
 'tadeus reichstein',
 'herbert spencer',
 'bishkek',
 'animnaput-walo',
 'avesta',
 'icelander',
 'crookes',
 'kaantasang panukdulan',
 'schulz',
 'patalsikin',
 'wycherley',
 'humphrey gilbert',
 'mt. ranier',
 'aengus',
 'simenon',
 'goodyear',
 'selkup',
 'roy lichtenstein',
 'authorized version',
 'hilagang korea',
 'gertrude lawrence',
 'okinawa',
 'john churchill',
 'montevideo',
 'sabaw na wonton',
 'alexis de tocqueville',
 'baybaying moreton',
 'lucy maud montgomery',
 'kathleen mansfield beauchamp',
 'second earl grey',
 'sir patrick manson',
 'nansen',
 'birr',
 'ulan bator',
 'thomas alva edison',
 'tubong eks-ray',
 'helen laura sumner woodbury',
 'claudius ptolemaeus',
 'alfred north whitehead',
 'debussy',
 'anna eleanor roosevelt',
 'of or relating to northern africa',
 'fomorian',
 'kayro',
 'anwar sadat',
 '175',
 'peter paul rubens',
 'hypatia',
 'baron georges cuvier',
 'mullah omar',
 'alan turing',
 'hogg',
 'ganymede',
 'mauser',
 'abbott lawrence lowell',
 'desimal praksyon',
 'gomorrha',
 'gatas na maasim',
 'nakikipagdiskusyon',
 '63',
 'magdalena',
 'komi',
 'benchley',
 'giles lytton strachey',
 'president garfield',
 '190th',
 'michinomiya hirohito',
 'sholom asch',
 "lorenzo de'medici",
 'papel de liha',
 'baroness thatcher of kesteven',
 'chekhov',
 'hellene',
 'hunger fast',
 'jabalpur',
 'port moresby',
 'baldr',
 'silofono',
 'punong-abukado',
 'jean-paul sartre',
 'sleep disorder',
 'lalagyan ng gas',
 'althea gibson',
 'anderson',
 'dr. seuss',
 ...}

## 2. Get the intersection of FWN and BORRA

In [20]:
FWN_U_BORRA = FWN_VOCAB.intersection(BORRA_VOCAB)
RATIO = (len(FWN_U_BORRA) / len(BORRA_VOCAB)) * 100
RATIO, len(FWN_U_BORRA)

(19.190426946373172, 2598)

## 3. Get the intersection of FWN and DICTIONARIES

In [19]:
FWN_U_BORRA = FWN_VOCAB.intersection(DICTIONARY_VOCAB)
RATIO = (len(FWN_U_BORRA) / len(DICTIONARY_VOCAB)) * 100
RATIO, len(FWN_U_BORRA)

(2.626850250443611, 2339)