In [14]:
%load_ext autoreload
%autoreload 2
from wordnet import *
from translate import *

## Load vocab

In [19]:
DATA_DIR = r"D:\thesis\codes\N-STEP"

In [21]:
sense_inventory = pd.read_pickle(f"{DATA_DIR}/sense_inventory_demo_fullwordnet_split1.pkl")
sense_inventory

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,matino,matino_0,"[0.0058104345, -0.0023813697, 0.04274508, -0.0...","[ng pelikula. Maganda at matino., kasama sa pe...","{'bandera': {'2014': 2, '2018': 2, '2021': 1, ...",VB
1,matino,matino_1,"[0.005492305, 0.02035046, 0.040070195, -0.0215...","[ko yung matino at magaling., lang yung maayos...","{'twitter': {'2021': 8}, 'bandera': {'2017': 1...",FW
2,maayos,maayos_0,"[0.033354558, 0.01896921, 0.027347978, -0.0634...","[maayos naman., sana, maayos pong lahat., maay...","{'bandera': {'2016': 1, '2015': 1}, 'abante': ...",JJ
3,maayos,maayos_1,"[-0.016235784, 0.0042992476, -0.001321828, 0.0...",[Hindi naman pumalag at maayos na sumama ang s...,"{'radyoinquirer': {'2019': 1}, 'gma': {'2015':...",JJ
4,hanapbuhay,hanapbuhay_0,"[0.01610576, 0.029051593, 0.028429884, -0.0208...",[lugar para maipagpatuloy ang kanilang hanapbu...,"{'radyoinquirer': {'2019': 1, '2021': 1}, 'ban...",NN
...,...,...,...,...,...,...
5447,tuod,tuod_1,"[0.0026925937, 0.016984362, 0.050824665, -0.01...","[sabihin ay parang tuod., Ano ko tuod walang p...","{'balita': {'2017': 2}, 'twitter': {'2021': 6}...",FW
5448,bumaling,bumaling_0,"[-0.002633381, 0.05177117, 0.050690066, 0.0117...",[tingin sakin tas nung bumaling kay joms ay ng...,"{'twitter': {'2021': 7}, 'google_books': {'202...",VB
5449,bumaling,bumaling_1,"[0.029594356, 0.004925939, 0.008006528, 0.0289...","[puso ay ganap nang bumaling sa Diyos, ipinaki...","{'google_books': {'2019': 6, '2021': 4}}",NN
5450,anas,anas_0,"[-0.033860113, 0.0042065405, 0.05422906, 0.003...","[Ni graduate nadaw kog laag anas mama HAHAAHA,...",{'twitter': {'2021': 10}},NN
5451,anas,anas_1,"[0.0004388683, 0.017983321, 0.024509717, -0.00...","[Ka anas ga sarapan, ko, garu ko gurumuson ana...",{'twitter': {'2021': 4}},NN

In [24]:
df_fil_words = pd.DataFrame({'fil_text': sense_inventory['word'].unique().tolist()})
df_fil_words

        fil_text
0         matino
1         maayos
2     hanapbuhay
3        trabaho
4           obra
...          ...
2593      bilasa
2594     makipot
2595        tuod
2596    bumaling
2597        anas

[2598 rows x 1 columns]

In [28]:
translated_text = translate_df(df_fil_words, mode="tl_to_en", backtranslate=True)
translated_text

Progress: 0.00
translated_text: sober
backtranslated_text: matino
Progress: 0.00
translated_text: well
backtranslated_text: mabuti
Progress: 0.00
translated_text: occupation
backtranslated_text: hanapbuhay
Progress: 0.00
translated_text: work
backtranslated_text: trabaho
Progress: 0.00
translated_text: work
backtranslated_text: trabaho
Progress: 0.00
translated_text: task
backtranslated_text: gawain
Progress: 0.00
translated_text: durable
backtranslated_text: matibay
Progress: 0.00
translated_text: tensile
backtranslated_text: makunat
Progress: 0.00
translated_text: stable
backtranslated_text: matatag
Progress: 0.00
translated_text: adults
backtranslated_text: matatanda
Progress: 0.00
translated_text: okay
backtranslated_text: Sige
Progress: 0.00
translated_text: oo
backtranslated_text: oo
Progress: 0.01
translated_text: language
backtranslated_text: wika
Progress: 0.01
translated_text: language
backtranslated_text: wika
Progress: 0.01
translated_text: risk
backtranslated_text: panganib
Progress: 0.01
translated_text: delicate
backtranslated_text: maselan
Progress: 0.01
translated_text: rescue
backtranslated_text: iligtas
Progress: 0.01
translated_text: safe
backtranslated_text: ligtas
Progress: 0.01
translated_text: lesbian
backtranslated_text: tomboy
Progress: 0.01
translated_text: sting
backtranslated_text: sumakit
Progress: 0.01
translated_text: gay
backtranslated_text: bakla
Progress: 0.01
translated_text: queer
backtranslated_text: kakaiba
Progress: 0.01
translated_text: fear
backtranslated_text: takot
Progress: 0.01
translated_text: coward
backtranslated_text: duwag
Progress: 0.01
translated_text: sad
backtranslated_text: malungkot
Progress: 0.01
translated_text: clumsy
backtranslated_text: malamya
Progress: 0.01
translated_text: compulsively
backtranslated_text: mapilit
Progress: 0.01
translated_text: matiyaga
backtranslated_text: matiyaga
Progress: 0.01
translated_text: makulit
backtranslated_text: makulit
Progress: 0.01
translated_text: ganoon
backtranslated_text: ganoon
Progress: 0.01
translated_text: like
backtranslated_text: gaya ng
Progress: 0.01
translated_text: noisy
backtranslated_text: maingay
Progress: 0.01
translated_text: talkative
backtranslated_text: madaldal
Progress: 0.01
translated_text: strong
backtranslated_text: malakas
Progress: 0.01
translated_text: nuisance
backtranslated_text: istorbo
Progress: 0.01
translated_text: abala
backtranslated_text: abala
Progress: 0.01
translated_text: mabanas
backtranslated_text: mabanas
Progress: 0.01
translated_text: hot
backtranslated_text: mainit
Progress: 0.02
translated_text: bugso
backtranslated_text: bugso
Progress: 0.02
translated_text: buhos
backtranslated_text: buhos
Progress: 0.02
translated_text: marvelous
backtranslated_text: kahanga-hanga
Progress: 0.02
translated_text: however
backtranslated_text: gayunpaman
Progress: 0.02
translated_text: weight
backtranslated_text: timbang
Progress: 0.02
translated_text: short
backtranslated_text: maikli
Progress: 0.02
translated_text: small
backtranslated_text: maliit
Progress: 0.02
translated_text: maiksi
backtranslated_text: maiksi
Progress: 0.02
translated_text: sunny
backtranslated_text: maaraw
Progress: 0.02
translated_text: again
backtranslated_text: muli
Progress: 0.02
translated_text: parati
backtranslated_text: parati
Progress: 0.02
translated_text: always
backtranslated_text: palagi
Progress: 0.02
translated_text: bihira
backtranslated_text: bihira
Progress: 0.02
translated_text: sometimes
backtranslated_text: minsan
Progress: 0.02
translated_text: accommodation
backtranslated_text: tirahan
Progress: 0.02
translated_text: home
backtranslated_text: bahay
Progress: 0.02
translated_text: house
backtranslated_text: bahay
Progress: 0.02
translated_text: image
backtranslated_text: larawan
Progress: 0.02
translated_text: picture
backtranslated_text: larawan
Progress: 0.02
translated_text: magaaral
backtranslated_text: magaaral
Progress: 0.02
translated_text: student
backtranslated_text: mag-aaral
Progress: 0.02
translated_text: school
backtranslated_text: paaralan
Progress: 0.02
translated_text: school
backtranslated_text: paaralan
Progress: 0.02
translated_text: notebook
backtranslated_text: kuwaderno
Progress: 0.02
translated_text: records
backtranslated_text: mga talaan
Progress: 0.02
translated_text: salary
backtranslated_text: suweldo
Progress: 0.03
translated_text: wages
backtranslated_text: sahod
Progress: 0.03
translated_text: cold
backtranslated_text: malamig
Progress: 0.03
translated_text: chill
backtranslated_text: chill
Progress: 0.03
translated_text: brilliant
backtranslated_text: napakatalino
Progress: 0.03
translated_text: tapon
backtranslated_text: tapon
Progress: 0.03
translated_text: stone
backtranslated_text: bato
Progress: 0.03
translated_text: throw
backtranslated_text: itapon
Progress: 0.03
translated_text: usap
backtranslated_text: usap
Progress: 0.03
translated_text: words
backtranslated_text: mga salita
Progress: 0.03
translated_text: great
backtranslated_text: malaki
Progress: 0.03
translated_text: great
backtranslated_text: malaki
Progress: 0.03
translated_text: diligence
backtranslated_text: sipag
Progress: 0.03
translated_text: pandak
backtranslated_text: pandak
Progress: 0.03
translated_text: dwarf
backtranslated_text: duwende
Progress: 0.03
translated_text: stunt
backtranslated_text: pagkabansot
Progress: 0.03
translated_text: stink
backtranslated_text: mabaho
Progress: 0.03
translated_text: defect
backtranslated_text: depekto
Progress: 0.03
translated_text: mapakla
backtranslated_text: mapakla
Progress: 0.03
translated_text: bitter
backtranslated_text: mapait
Progress: 0.03
translated_text: pait
backtranslated_text: pait
Progress: 0.03
translated_text: brave
backtranslated_text: matapang
Progress: 0.03
translated_text: stop
backtranslated_text: huminto
Progress: 0.03
translated_text: cold
backtranslated_text: malamig
Progress: 0.03
translated_text: sadness
backtranslated_text: kalungkutan
Progress: 0.03
translated_text: gala
backtranslated_text: gala
Progress: 0.03
translated_text: pasyal
backtranslated_text: pasyal
Progress: 0.04
translated_text: tawa
backtranslated_text: tawa
Progress: 0.04
translated_text: smile
backtranslated_text: ngumiti
Progress: 0.04
translated_text: halakhak
backtranslated_text: halakhak
Progress: 0.04
translated_text: ligaya
backtranslated_text: ligaya
Progress: 0.04
translated_text: me
backtranslated_text: ako
Progress: 0.04
translated_text: delight
backtranslated_text: galak
Progress: 0.04
translated_text: fierce
backtranslated_text: mabangis
Progress: 0.04
translated_text: fat
backtranslated_text: mataba
Progress: 0.04
translated_text: tapos
backtranslated_text: tapos
Progress: 0.04
translated_text: finally
backtranslated_text: sa wakas
Progress: 0.04
translated_text: tired
backtranslated_text: pagod
Progress: 0.04
translated_text: cloth
backtranslated_text: tela
Progress: 0.04
translated_text: banat
backtranslated_text: banat
Progress: 0.04
translated_text: sapag
backtranslated_text: sapag
Progress: 0.04
translated_text: blow
backtranslated_text: suntok
Progress: 0.04
translated_text: run away
backtranslated_text: takbo
Progress: 0.04
translated_text: alis
backtranslated_text: alis
Progress: 0.04
translated_text: dali
backtranslated_text: dali
Progress: 0.04
translated_text: speed
backtranslated_text: bilis
Progress: 0.04
translated_text: future
backtranslated_text: kinabukasan
Progress: 0.04
translated_text: tomorrow
backtranslated_text: bukas
Progress: 0.04
translated_text: chick
backtranslated_text: sisiw
Progress: 0.04
translated_text: data
backtranslated_text: datos
Progress: 0.04
translated_text: when
backtranslated_text: kailan
Progress: 0.04
translated_text: toilet
backtranslated_text: palikuran
Progress: 0.04
translated_text: bathroom
backtranslated_text: banyo
Progress: 0.05
translated_text: ebak
backtranslated_text: ebak
Progress: 0.05
translated_text: color
backtranslated_text: kulay
Progress: 0.05
translated_text: book
backtranslated_text: aklat
Progress: 0.05
translated_text: book
backtranslated_text: aklat
Progress: 0.05
translated_text: perfume
backtranslated_text: pabango
Progress: 0.05
translated_text: ear
backtranslated_text: tainga
Progress: 0.05
translated_text: looks like

backtranslated_text: parang
Progress: 0.05
translated_text: resemblance
backtranslated_text: pagkakahawig
Progress: 0.05
translated_text: right
backtranslated_text: tama
Progress: 0.05
translated_text: exactly
backtranslated_text: eksakto
Progress: 0.05
translated_text: valid
backtranslated_text: wasto
Progress: 0.05
translated_text: accurate
backtranslated_text: tumpak
Progress: 0.05
translated_text: completely
backtranslated_text: ganap
Progress: 0.05
translated_text: right
backtranslated_text: tama
Progress: 0.05
translated_text: lapat
backtranslated_text: lapat
Progress: 0.05
translated_text: trap
backtranslated_text: bitag
Progress: 0.05
translated_text: pit
backtranslated_text: hukay
Progress: 0.05
translated_text: bura
backtranslated_text: bura
Progress: 0.05
translated_text: date
backtranslated_text: petsa
Progress: 0.05
translated_text: laglag
backtranslated_text: laglag
Progress: 0.05
translated_text: hulog
backtranslated_text: hulog
Progress: 0.05
translated_text: joint
backtranslated_text: magkadugtong
Progress: 0.05
translated_text: fixture
backtranslated_text: kabit
Progress: 0.05
translated_text: connect
backtranslated_text: kumonekta
Progress: 0.05
translated_text: wall
backtranslated_text: pader
Progress: 0.05
translated_text: rubbish
backtranslated_text: basura
Progress: 0.06
translated_text: notice
backtranslated_text: pansinin
Progress: 0.06
translated_text: discovery
backtranslated_text: pagtuklas
Progress: 0.06
translated_text: find
backtranslated_text: hanapin
Progress: 0.06
translated_text: insects
backtranslated_text: mga insekto
Progress: 0.06
translated_text: with
backtranslated_text: kasama
Progress: 0.06
translated_text: auto
backtranslated_text: sasakyan
Progress: 0.06
translated_text: car
backtranslated_text: sasakyan
Progress: 0.06
translated_text: wagon
backtranslated_text: bagon
Progress: 0.06
translated_text: vehicle
backtranslated_text: sasakyan
Progress: 0.06
translated_text: next
backtranslated_text: susunod
Progress: 0.06
translated_text: monster
backtranslated_text: halimaw
Progress: 0.06
translated_text: demon
backtranslated_text: demonyo
Progress: 0.06
translated_text: devil
backtranslated_text: demonyo
Progress: 0.06
translated_text: small
backtranslated_text: maliit
Progress: 0.06
translated_text: palpak
backtranslated_text: palpak
Progress: 0.06
translated_text: same
backtranslated_text: pareho
Progress: 0.06
translated_text: individual
backtranslated_text: indibidwal
Progress: 0.06
translated_text: tao
backtranslated_text: tao
Progress: 0.06
translated_text: group
backtranslated_text: pangkat
Progress: 0.06
translated_text: nutrients
backtranslated_text: sustansya
Progress: 0.06
translated_text: food
backtranslated_text: pagkain
Progress: 0.06
translated_text: garments
backtranslated_text: mga kasuotan
Progress: 0.06
translated_text: personhood
backtranslated_text: katauhan
Progress: 0.06
translated_text: character
backtranslated_text: karakter
Progress: 0.06
translated_text: personality
backtranslated_text: pagkatao
Progress: 0.06
translated_text: tanim
backtranslated_text: tanim
Progress: 0.07
translated_text: flora
backtranslated_text: flora
Progress: 0.07
translated_text: page
backtranslated_text: pahina
Progress: 0.07
translated_text: crops
backtranslated_text: mga pananim
Progress: 0.07
translated_text: papers
backtranslated_text: mga papel
Progress: 0.07
translated_text: document
backtranslated_text: dokumento
Progress: 0.07
translated_text: correspondence
backtranslated_text: pagsusulatan
Progress: 0.07
translated_text: product
backtranslated_text: produkto
Progress: 0.07
translated_text: goods
backtranslated_text: kalakal
Progress: 0.07
translated_text: decoration
backtranslated_text: palamuti
Progress: 0.07
translated_text: decoration
backtranslated_text: palamuti
Progress: 0.07
translated_text: building
backtranslated_text: gusali
Progress: 0.07
translated_text: robbery
backtranslated_text: pagnanakaw
Progress: 0.07
translated_text: cloth
backtranslated_text: tela
Progress: 0.07
translated_text: furniture
backtranslated_text: muwebles
Progress: 0.07
translated_text: drinkable
backtranslated_text: maiinom
Progress: 0.07
translated_text: drink
backtranslated_text: inumin
Progress: 0.07
translated_text: creature
backtranslated_text: nilalang
Progress: 0.07
translated_text: border
backtranslated_text: hangganan
Progress: 0.07
translated_text: limitations
backtranslated_text: mga limitasyon
Progress: 0.07
translated_text: asset
backtranslated_text: asset
Progress: 0.07
translated_text: dressed
backtranslated_text: nakabihis
Progress: 0.07
translated_text: suot
backtranslated_text: suot
Progress: 0.07
translated_text: clothing
backtranslated_text: damit
Progress: 0.07
translated_text: kinapal
backtranslated_text: kinapal
Progress: 0.07
translated_text: animal
backtranslated_text: hayop
Progress: 0.07
translated_text: quantity
backtranslated_text: dami
Progress: 0.08
translated_text: size
backtranslated_text: laki
Progress: 0.08
translated_text: value
backtranslated_text: halaga
Progress: 0.08
translated_text: takal
backtranslated_text: takal
Progress: 0.08
translated_text: price
backtranslated_text: presyo
Progress: 0.08
translated_text: raw
backtranslated_text: hilaw
Progress: 0.08
translated_text: new
backtranslated_text: bago
Progress: 0.08
translated_text: green
backtranslated_text: berde
Progress: 0.08
translated_text: green
backtranslated_text: berde
Progress: 0.08
translated_text: press
backtranslated_text: pindutin
Progress: 0.08
translated_text: below
backtranslated_text: sa ibaba
Progress: 0.08
translated_text: cruel
backtranslated_text: malupit
Progress: 0.08
translated_text: pain
backtranslated_text: sakit
Progress: 0.08
translated_text: hapdi
backtranslated_text: hapdi
Progress: 0.08
translated_text: sick
backtranslated_text: may sakit
Progress: 0.08
translated_text: suicide
backtranslated_text: pagpapakamatay
Progress: 0.08
translated_text: suicide
backtranslated_text: pagpapakamatay
Progress: 0.08
translated_text: commit suicide
backtranslated_text: magpakamatay
Progress: 0.08
translated_text: tomb
backtranslated_text: libingan
Progress: 0.08
translated_text: nitso
backtranslated_text: nitso
Progress: 0.08
translated_text: tragedy
backtranslated_text: trahedya
Progress: 0.08
translated_text: snore
backtranslated_text: hilik
Progress: 0.08
translated_text: die
backtranslated_text: mamatay
Progress: 0.08
translated_text: end
backtranslated_text: wakas
Progress: 0.08
translated_text: grief
backtranslated_text: kalungkutan
Progress: 0.08
translated_text: grief
backtranslated_text: kalungkutan
Progress: 0.08
translated_text: dalamhati
backtranslated_text: dalamhati
Progress: 0.09
translated_text: suffering
backtranslated_text: paghihirap
Progress: 0.09
translated_text: resentment
backtranslated_text: sama ng loob
Progress: 0.09
translated_text: inadequate
backtranslated_text: hindi sapat
Progress: 0.09
translated_text: windang
backtranslated_text: windang
Progress: 0.09
translated_text: nasira
backtranslated_text: nasira
Progress: 0.09
translated_text: violated
backtranslated_text: nilabag
Progress: 0.09
translated_text: lupaypay
backtranslated_text: lupaypay
Progress: 0.09
translated_text: putol
backtranslated_text: putol
Progress: 0.09
translated_text: ruined
backtranslated_text: wasak
Progress: 0.09
translated_text: sira
backtranslated_text: sira
Progress: 0.09
translated_text: bereavement
backtranslated_text: pangungulila
Progress: 0.09
translated_text: cried
backtranslated_text: sumigaw
Progress: 0.09
translated_text: regret
backtranslated_text: panghihinayang
Progress: 0.09
translated_text: complain
backtranslated_text: magreklamo
Progress: 0.09
translated_text: lament
backtranslated_text: managhoy
Progress: 0.09
translated_text: mass
backtranslated_text: misa
Progress: 0.09
translated_text: ago
backtranslated_text: kanina
Progress: 0.09
translated_text: yesterday
backtranslated_text: kahapon
Progress: 0.09
translated_text: disgust
backtranslated_text: pagkasuklam
Progress: 0.09
translated_text: hatred
backtranslated_text: poot
Progress: 0.09
translated_text: terror
backtranslated_text: takot
Progress: 0.09
translated_text: horror
backtranslated_text: katatakutan
Progress: 0.09
translated_text: lagim

backtranslated_text: lagim
Progress: 0.09
translated_text: panic
backtranslated_text: panic
Progress: 0.09
translated_text: search
backtranslated_text: paghahanap
Progress: 0.09
translated_text: chase
backtranslated_text: habulin
Progress: 0.10
translated_text: chase
backtranslated_text: habulin
Progress: 0.10
translated_text: kapkapan
backtranslated_text: kapkapan
Progress: 0.10
translated_text: check
backtranslated_text: suriin
Progress: 0.10
translated_text: monitor
backtranslated_text: subaybayan
Progress: 0.10
translated_text: ally
backtranslated_text: kakampi
Progress: 0.10
translated_text: friend
backtranslated_text: kaibigan
Progress: 0.10
translated_text: prick
backtranslated_text: tusok
Progress: 0.10
translated_text: push
backtranslated_text: itulak
Progress: 0.10
translated_text: push
backtranslated_text: itulak
Progress: 0.10
translated_text: force
backtranslated_text: puwersa
Progress: 0.10
translated_text: urge
backtranslated_text: paghihimok
Progress: 0.10
translated_text: force
backtranslated_text: puwersa
Progress: 0.10
translated_text: pound
backtranslated_text: libra
Progress: 0.10
translated_text: ibiyahe
backtranslated_text: ibiyahe
Progress: 0.10
translated_text: touch
backtranslated_text: hawakan
Progress: 0.10
translated_text: worry
backtranslated_text: mag-alala
Progress: 0.10
translated_text: resistance
backtranslated_text: paglaban
Progress: 0.10
translated_text: duwelo
backtranslated_text: duwelo
Progress: 0.10
translated_text: shallow
backtranslated_text: mababaw
Progress: 0.10
translated_text: makati
backtranslated_text: makati
Progress: 0.10
translated_text: vulgar
backtranslated_text: bulgar
Progress: 0.10
translated_text: little
backtranslated_text: maliit
Progress: 0.10
translated_text: scarce
backtranslated_text: kakaunti
Progress: 0.10
translated_text: evident
backtranslated_text: maliwanag
Progress: 0.10
translated_text: clear
backtranslated_text: malinaw
Progress: 0.10
translated_text: pale
backtranslated_text: maputla
Progress: 0.11
translated_text: light
backtranslated_text: liwanag
Progress: 0.11
translated_text: weak
backtranslated_text: mahina
Progress: 0.11
translated_text: easy
backtranslated_text: madali
Progress: 0.11
translated_text: soap
backtranslated_text: sabon
Progress: 0.11
translated_text: lesson
backtranslated_text: aralin
Progress: 0.11
translated_text: sermon
backtranslated_text: sermon
Progress: 0.11
translated_text: punishment
backtranslated_text: parusa
Progress: 0.11
translated_text: lesson
backtranslated_text: aralin
Progress: 0.11
translated_text: wound
backtranslated_text: sugat
Progress: 0.11
translated_text: trace
backtranslated_text: bakas
Progress: 0.11
translated_text: labi
backtranslated_text: labi
Progress: 0.11
translated_text: sign
backtranslated_text: tanda
Progress: 0.11
translated_text: scars
backtranslated_text: mga peklat
Progress: 0.11
translated_text: scratch
backtranslated_text: scratch
Progress: 0.11
translated_text: signs
backtranslated_text: palatandaan
Progress: 0.11
translated_text: suppose
backtranslated_text: kunwari
Progress: 0.11
translated_text: count
backtranslated_text: bilangin
Progress: 0.11
translated_text: count
backtranslated_text: bilangin
Progress: 0.11
translated_text: count
backtranslated_text: bilangin
Progress: 0.11
translated_text: count
backtranslated_text: bilangin
Progress: 0.11
translated_text: gender
backtranslated_text: kasarian
Progress: 0.11
translated_text: ani
backtranslated_text: ani
Progress: 0.11
translated_text: mamitas
backtranslated_text: mamitas
Progress: 0.11
translated_text: umani
backtranslated_text: umani
Progress: 0.11
translated_text: sagarin
backtranslated_text: sagarin
Progress: 0.11
translated_text: consume
backtranslated_text: ubusin
Progress: 0.12
translated_text: take advantage
backtranslated_text: samantalahin
Progress: 0.12
translated_text: use
backtranslated_text: gamitin
Progress: 0.12
translated_text: use
backtranslated_text: gamitin
Progress: 0.12
translated_text: tourist
backtranslated_text: turista
Progress: 0.12
translated_text: management
backtranslated_text: pamamahala
Progress: 0.12
translated_text: oversee
backtranslated_text: mangasiwa
Progress: 0.12
translated_text: guide
backtranslated_text: gabay
Progress: 0.12
translated_text: akay
backtranslated_text: okay
Progress: 0.12
translated_text: for example
backtranslated_text: Halimbawa
Progress: 0.12
translated_text: sample
backtranslated_text: sample
Progress: 0.12
translated_text: pattern
backtranslated_text: pattern
Progress: 0.12
translated_text: model
backtranslated_text: modelo
Progress: 0.12
translated_text: ehemplo
backtranslated_text: halimbawa
Progress: 0.12
translated_text: guide
backtranslated_text: gabay
Progress: 0.12
translated_text: guidance
backtranslated_text: gabay
Progress: 0.12
translated_text: stop
backtranslated_text: huminto
Progress: 0.12
translated_text: pass
backtranslated_text: pumasa
Progress: 0.12
translated_text: kill
backtranslated_text: pumatay
Progress: 0.12
translated_text: kill
backtranslated_text: pumatay
Progress: 0.12
translated_text: wait
backtranslated_text: maghintay
Progress: 0.12
translated_text: tunghayan
backtranslated_text: tunghayan
Progress: 0.12
translated_text: observe
backtranslated_text: obserbahan
Progress: 0.12
translated_text: masdan
backtranslated_text: masdan
Progress: 0.12
translated_text: matyagan
backtranslated_text: matyagan
Progress: 0.12
translated_text: observe
backtranslated_text: obserbahan
Progress: 0.12
translated_text: look
backtranslated_text: tingnan mo
Progress: 0.13
translated_text: portrait
backtranslated_text: portrait
Progress: 0.13
translated_text: lamina
backtranslated_text: lamina
Progress: 0.13
translated_text: deviate
backtranslated_text: lumihis
Progress: 0.13
translated_text: oppose
backtranslated_text: tutulan
Progress: 0.13
translated_text: arrival
backtranslated_text: pagdating
Progress: 0.13
translated_text: diligent
backtranslated_text: masipag
Progress: 0.13
translated_text: enthusiastic
backtranslated_text: masigasig
Progress: 0.13
translated_text: lively
backtranslated_text: masigla
Progress: 0.13
translated_text: nervous
backtranslated_text: kinakabahan
Progress: 0.13
translated_text: nervous
backtranslated_text: kinakabahan
Progress: 0.13
translated_text: remind
backtranslated_text: paalalahanan
Progress: 0.13
translated_text: slap
backtranslated_text: sampal
Progress: 0.13
translated_text: popular
backtranslated_text: sikat
Progress: 0.13
translated_text: famous
backtranslated_text: sikat
Progress: 0.13
translated_text: brush
backtranslated_text: magsipilyo
Progress: 0.13
translated_text: popular
backtranslated_text: sikat
Progress: 0.13
translated_text: classroom
backtranslated_text: silid-aralan
Progress: 0.13
translated_text: mystery
backtranslated_text: misteryo
Progress: 0.13
translated_text: mystery
backtranslated_text: misteryo
Progress: 0.13
translated_text: teacher
backtranslated_text: guro
Progress: 0.13
translated_text: titser
backtranslated_text: titser
Progress: 0.13
translated_text: professor
backtranslated_text: propesor
Progress: 0.13
translated_text: location
backtranslated_text: lokasyon
Progress: 0.13
translated_text: patient
backtranslated_text: pasyente
Progress: 0.13
translated_text: lethargic
backtranslated_text: matamlay
Progress: 0.13
translated_text: softening
backtranslated_text: paglambot
Progress: 0.14
translated_text: love
backtranslated_text: pag-ibig
Progress: 0.14
translated_text: hepe
backtranslated_text: hepe
Progress: 0.14
translated_text: leader
backtranslated_text: pinuno
Progress: 0.14
translated_text: batugan
backtranslated_text: batugan
Progress: 0.14
translated_text: lazy
backtranslated_text: tamad
Progress: 0.14
translated_text: petiks
backtranslated_text: petiks
Progress: 0.14
translated_text: sluggish
backtranslated_text: matamlay
Progress: 0.14
translated_text: disciplined
backtranslated_text: disiplinado
Progress: 0.14
translated_text: strict
backtranslated_text: mahigpit
Progress: 0.14
translated_text: patient
backtranslated_text: pasyente
Progress: 0.14
translated_text: kind
backtranslated_text: mabait
Progress: 0.14
translated_text: disability
backtranslated_text: kapansanan
Progress: 0.14
translated_text: illness

backtranslated_text: karamdaman
Progress: 0.14
translated_text: punda
backtranslated_text: punda
Progress: 0.14
translated_text: pillow
backtranslated_text: unan
Progress: 0.14
translated_text: game
backtranslated_text: laro
Progress: 0.14
translated_text: damages
backtranslated_text: pinsala
Progress: 0.14
translated_text: a lot
backtranslated_text: marami
Progress: 0.14
translated_text: pure
backtranslated_text: dalisay
Progress: 0.14
translated_text: pure
backtranslated_text: dalisay
Progress: 0.14
translated_text: smooth
backtranslated_text: makinis
Progress: 0.14
translated_text: crushed
backtranslated_text: durog
Progress: 0.14
translated_text: pino
backtranslated_text: pino
Progress: 0.14
translated_text: mainam
backtranslated_text: mainam
Progress: 0.14
translated_text: good
backtranslated_text: mabuti
Progress: 0.14
translated_text: sharp
backtranslated_text: matalas
Progress: 0.15
translated_text: lunas
backtranslated_text: lunas
Progress: 0.15
translated_text: medicine
backtranslated_text: gamot
Progress: 0.15
translated_text: treatment
backtranslated_text: paggamot
Progress: 0.15
translated_text: napkin
backtranslated_text: napkin
Progress: 0.15
translated_text: bimpo
backtranslated_text: bimpo
Progress: 0.15
translated_text: towels
backtranslated_text: mga tuwalya
Progress: 0.15
translated_text: periodical
backtranslated_text: periodical
Progress: 0.15
translated_text: newspaper
backtranslated_text: pahayagan
Progress: 0.15
translated_text: newspaper
backtranslated_text: pahayagan
Progress: 0.15
translated_text: paper
backtranslated_text: papel
Progress: 0.15
translated_text: report
backtranslated_text: ulat
Progress: 0.15
translated_text: report
backtranslated_text: ulat
Progress: 0.15
translated_text: write
backtranslated_text: magsulat
Progress: 0.15
translated_text: narrative
backtranslated_text: salaysay
Progress: 0.15
translated_text: manifest
backtranslated_text: mahayag
Progress: 0.15
translated_text: base
backtranslated_text: base
Progress: 0.15
translated_text: suitcase
backtranslated_text: maleta
Progress: 0.15
translated_text: sack
backtranslated_text: sako
Progress: 0.15
translated_text: bag
backtranslated_text: bag
Progress: 0.15
translated_text: wallet
backtranslated_text: wallet
Progress: 0.15
translated_text: bag
backtranslated_text: bag
Progress: 0.15
translated_text: plastic
backtranslated_text: plastik
Progress: 0.15
translated_text: sound
backtranslated_text: tunog
Progress: 0.15
translated_text: term
backtranslated_text: termino
Progress: 0.15
translated_text: call
backtranslated_text: tawag
Progress: 0.15
translated_text: radio
backtranslated_text: radyo
Progress: 0.16
translated_text: bulb
backtranslated_text: bombilya
Progress: 0.16
translated_text: lampara
backtranslated_text: lampara
Progress: 0.16
translated_text: torch
backtranslated_text: tanglaw
Progress: 0.16
translated_text: light
backtranslated_text: liwanag
Progress: 0.16
translated_text: light
backtranslated_text: liwanag
Progress: 0.16
translated_text: clear
backtranslated_text: malinaw
Progress: 0.16
translated_text: clean
backtranslated_text: malinis
Progress: 0.16
translated_text: ball
backtranslated_text: bola
Progress: 0.16
translated_text: globe
backtranslated_text: globo
Progress: 0.16
translated_text: diamond
backtranslated_text: brilyante
Progress: 0.16
translated_text: diamond
backtranslated_text: brilyante
Progress: 0.16
translated_text: ice
backtranslated_text: yelo
Progress: 0.16
translated_text: icing
backtranslated_text: icing
Progress: 0.16
translated_text: mamon
backtranslated_text: mamon
Progress: 0.16
translated_text: cake
backtranslated_text: cake
Progress: 0.16
translated_text: tea
backtranslated_text: tsaa
Progress: 0.16
translated_text: rice
backtranslated_text: kanin
Progress: 0.16
translated_text: sinaing
backtranslated_text: sinaing
Progress: 0.16
translated_text: rice
backtranslated_text: kanin
Progress: 0.16
translated_text: palay
backtranslated_text: palay
Progress: 0.16
translated_text: fried rice
backtranslated_text: sinangag
Progress: 0.16
translated_text: bread
backtranslated_text: tinapay
Progress: 0.16
translated_text: baker
backtranslated_text: panadero
Progress: 0.16
translated_text: plant
backtranslated_text: halaman
Progress: 0.16
translated_text: erect
backtranslated_text: magtayo
Progress: 0.16
translated_text: establish
backtranslated_text: magtatag
Progress: 0.17
translated_text: start
backtranslated_text: simulan
Progress: 0.17
translated_text: start
backtranslated_text: simulan
Progress: 0.17
translated_text: itanim
backtranslated_text: itanim
Progress: 0.17
translated_text: workshop
backtranslated_text: pagawaan
Progress: 0.17
translated_text: factory
backtranslated_text: pabrika
Progress: 0.17
translated_text: plant
backtranslated_text: halaman
Progress: 0.17
translated_text: article
backtranslated_text: artikulo
Progress: 0.17
translated_text: messenger
backtranslated_text: sugo
Progress: 0.17
translated_text: page
backtranslated_text: pahina
Progress: 0.17
translated_text: leaves
backtranslated_text: dahon
Progress: 0.17
translated_text: consequence
backtranslated_text: kahihinatnan
Progress: 0.17
translated_text: result
backtranslated_text: resulta
Progress: 0.17
translated_text: flowers
backtranslated_text: mga bulaklak
Progress: 0.17
translated_text: flowers
backtranslated_text: mga bulaklak
Progress: 0.17
translated_text: childish
backtranslated_text: pambata
Progress: 0.17
translated_text: babe
backtranslated_text: babe
Progress: 0.17
translated_text: baby
backtranslated_text: baby
Progress: 0.17
translated_text: infant
backtranslated_text: sanggol
Progress: 0.17
translated_text: youngest
backtranslated_text: bunso
Progress: 0.17
translated_text: baby
backtranslated_text: baby
Progress: 0.17
translated_text: wake up
backtranslated_text: gising na
Progress: 0.17
translated_text: gatungan
backtranslated_text: gatungan
Progress: 0.17
translated_text: burn
backtranslated_text: paso
Progress: 0.17
translated_text: expel
backtranslated_text: paalisin
Progress: 0.17
translated_text: expel
backtranslated_text: paalisin
Progress: 0.17
translated_text: suffering
backtranslated_text: paghihirap
Progress: 0.18
translated_text: firing
backtranslated_text: pagpapaputok
Progress: 0.18
translated_text: fire
backtranslated_text: apoy
Progress: 0.18
translated_text: air
backtranslated_text: hangin
Progress: 0.18
translated_text: ere
backtranslated_text: kanina
Progress: 0.18
translated_text: alapaap
backtranslated_text: alapaap
Progress: 0.18
translated_text: breeze
backtranslated_text: simoy ng hangin
Progress: 0.18
translated_text: wind
backtranslated_text: hangin
Progress: 0.18
translated_text: salivate
backtranslated_text: maglaway
Progress: 0.18
translated_text: hose
backtranslated_text: hose
Progress: 0.18
translated_text: water
backtranslated_text: tubig
Progress: 0.18
translated_text: space
backtranslated_text: space
Progress: 0.18
translated_text: space
backtranslated_text: space
Progress: 0.18
translated_text: hole
backtranslated_text: butas
Progress: 0.18
translated_text: strategy
backtranslated_text: diskarte
Progress: 0.18
translated_text: style
backtranslated_text: istilo
Progress: 0.18
translated_text: way
backtranslated_text: paraan
Progress: 0.18
translated_text: operation
backtranslated_text: operasyon
Progress: 0.18
translated_text: technique
backtranslated_text: pamamaraan
Progress: 0.18
translated_text: running
backtranslated_text: tumatakbo
Progress: 0.18
translated_text: direction
backtranslated_text: direksyon
Progress: 0.18
translated_text: flow
backtranslated_text: daloy
Progress: 0.18
translated_text: agos
backtranslated_text: agos
Progress: 0.18
translated_text: subok
backtranslated_text: subok
Progress: 0.18
translated_text: conclusion
backtranslated_text: konklusyon
Progress: 0.18
translated_text: end
backtranslated_text: wakas
Progress: 0.18
translated_text: do
backtranslated_text: gawin
Progress: 0.19
translated_text: be
backtranslated_text: maging
Progress: 0.19
translated_text: gain
backtranslated_text: makakuha
Progress: 0.19
translated_text: likha
backtranslated_text: likha
Progress: 0.19
translated_text: action
backtranslated_text: aksyon
Progress: 0.19
translated_text: create

backtranslated_text: lumikha
Progress: 0.19
translated_text: buo
backtranslated_text: buo
Progress: 0.19
translated_text: cook
backtranslated_text: magluto
Progress: 0.19
translated_text: develop
backtranslated_text: bumuo
Progress: 0.19
translated_text: make
backtranslated_text: gumawa
Progress: 0.19
translated_text: perseverance
backtranslated_text: tiyaga
Progress: 0.19
translated_text: effort
backtranslated_text: pagsisikap
Progress: 0.19
translated_text: perseverance
backtranslated_text: tiyaga
Progress: 0.19
translated_text: kusa
backtranslated_text: kusa
Progress: 0.19
translated_text: attitude
backtranslated_text: saloobin
Progress: 0.19
translated_text: fold
backtranslated_text: tiklop
Progress: 0.19
translated_text: motion
backtranslated_text: galaw
Progress: 0.19
translated_text: step
backtranslated_text: hakbang
Progress: 0.19
translated_text: push
backtranslated_text: itulak
Progress: 0.19
translated_text: kilos
backtranslated_text: kilo
Progress: 0.19
translated_text: walk
backtranslated_text: lakad
Progress: 0.19
translated_text: motion
backtranslated_text: galaw
Progress: 0.19
translated_text: deliver
backtranslated_text: ihatid
Progress: 0.19
translated_text: strength
backtranslated_text: lakas
Progress: 0.19
translated_text: walk
backtranslated_text: lakad
Progress: 0.19
translated_text: retreat
backtranslated_text: urong
Progress: 0.19
translated_text: atras
backtranslated_text: atras
Progress: 0.20
translated_text: run
backtranslated_text: tumakbo
Progress: 0.20
translated_text: drive
backtranslated_text: magmaneho
Progress: 0.20
translated_text: on the road
backtranslated_text: nasa kalsada
Progress: 0.20
translated_text: street
backtranslated_text: kalye
Progress: 0.20
translated_text: way
backtranslated_text: paraan
Progress: 0.20
translated_text: driving
backtranslated_text: pagmamaneho
Progress: 0.20
translated_text: the street
backtranslated_text: ang kalye
Progress: 0.20
translated_text: fight
backtranslated_text: lumaban
Progress: 0.20
translated_text: movement
backtranslated_text: paggalaw
Progress: 0.20
translated_text: campaign
backtranslated_text: kampanya
Progress: 0.20
translated_text: awayin
backtranslated_text: awayin
Progress: 0.20
translated_text: kumandidato
backtranslated_text: kumandidato
Progress: 0.20
translated_text: run
backtranslated_text: tumakbo
Progress: 0.20
translated_text: campaign
backtranslated_text: kampanya
Progress: 0.20
translated_text: reconcile
backtranslated_text: magkasundo
Progress: 0.20
translated_text: decide
backtranslated_text: magpasya
Progress: 0.20
translated_text: decision
backtranslated_text: desisyon
Progress: 0.20
translated_text: termination
backtranslated_text: pagwawakas
Progress: 0.20
translated_text: closing
backtranslated_text: pagsasara
Progress: 0.20
translated_text: end
backtranslated_text: wakas
Progress: 0.20
translated_text: close
backtranslated_text: malapit na
Progress: 0.20
translated_text: finish
backtranslated_text: tapusin
Progress: 0.20
translated_text: end
backtranslated_text: wakas
Progress: 0.20
translated_text: debate
backtranslated_text: debate
Progress: 0.20
translated_text: argument
backtranslated_text: argumento
Progress: 0.20
translated_text: reason
backtranslated_text: dahilan
Progress: 0.21
translated_text: urge
backtranslated_text: paghihimok
Progress: 0.21
translated_text: provoke
backtranslated_text: pukawin
Progress: 0.21
translated_text: carry out
backtranslated_text: isagawa
Progress: 0.21
translated_text: pasimuno
backtranslated_text: pasimuno
Progress: 0.21
translated_text: cause
backtranslated_text: dahilan
Progress: 0.21
translated_text: reason
backtranslated_text: dahilan
Progress: 0.21
translated_text: crusade
backtranslated_text: krusada
Progress: 0.21
translated_text: premise
backtranslated_text: premise
Progress: 0.21
translated_text: basis
backtranslated_text: batayan
Progress: 0.21
translated_text: foundation
backtranslated_text: pundasyon
Progress: 0.21
translated_text: intellect
backtranslated_text: talino
Progress: 0.21
translated_text: sanity
backtranslated_text: katinuan
Progress: 0.21
translated_text: way of thinking
backtranslated_text: Paraan ng pag iisip
Progress: 0.21
translated_text: understanding
backtranslated_text: pagkakaunawaan
Progress: 0.21
translated_text: talent
backtranslated_text: talento
Progress: 0.21
translated_text: ideklara
backtranslated_text: ideklara
Progress: 0.21
translated_text: say
backtranslated_text: sabihin
Progress: 0.21
translated_text: reveal
backtranslated_text: ibunyag
Progress: 0.21
translated_text: said
backtranslated_text: sabi
Progress: 0.21
translated_text: lahad
backtranslated_text: lahad
Progress: 0.21
translated_text: reveal
backtranslated_text: ibunyag
Progress: 0.21
translated_text: confess
backtranslated_text: umamin
Progress: 0.21
translated_text: form
backtranslated_text: anyo
Progress: 0.21
translated_text: appearance
backtranslated_text: hitsura
Progress: 0.21
translated_text: state
backtranslated_text: estado
Progress: 0.21
translated_text: condition
backtranslated_text: kundisyon
Progress: 0.22
translated_text: face
backtranslated_text: mukha
Progress: 0.22
translated_text: province
backtranslated_text: lalawigan
Progress: 0.22
translated_text: ipot
backtranslated_text: ipot
Progress: 0.22
translated_text: dirt
backtranslated_text: dumi
Progress: 0.22
translated_text: reply
backtranslated_text: sagot
Progress: 0.22
translated_text: townspeople
backtranslated_text: taong bayan
Progress: 0.22
translated_text: after
backtranslated_text: pagkatapos
Progress: 0.22
translated_text: nation
backtranslated_text: bansa
Progress: 0.22
translated_text: farm
backtranslated_text: sakahan
Progress: 0.22
translated_text: province
backtranslated_text: lalawigan
Progress: 0.22
translated_text: country
backtranslated_text: bansa
Progress: 0.22
translated_text: place
backtranslated_text: lugar
Progress: 0.22
translated_text: range
backtranslated_text: saklaw
Progress: 0.22
translated_text: mud
backtranslated_text: putik
Progress: 0.22
translated_text: lupa
backtranslated_text: kalimutan
Progress: 0.22
translated_text: fertilizer
backtranslated_text: pataba
Progress: 0.22
translated_text: filth
backtranslated_text: karumihan
Progress: 0.22
translated_text: waste
backtranslated_text: basura
Progress: 0.22
translated_text: fat
backtranslated_text: mataba
Progress: 0.22
translated_text: libag
backtranslated_text: libag
Progress: 0.22
translated_text: filth
backtranslated_text: karumihan
Progress: 0.22
translated_text: stain
backtranslated_text: mantsa
Progress: 0.22
translated_text: mark
backtranslated_text: marka
Progress: 0.22
translated_text: streak
backtranslated_text: guhit
Progress: 0.22
translated_text: batik
backtranslated_text: batik
Progress: 0.22
translated_text: keep
backtranslated_text: panatilihin
Progress: 0.23
translated_text: ban
backtranslated_text: pagbabawal
Progress: 0.23
translated_text: basehan
backtranslated_text: basehan
Progress: 0.23
translated_text: justification
backtranslated_text: katwiran
Progress: 0.23
translated_text: malagay
backtranslated_text: malagay
Progress: 0.23
translated_text: lead
backtranslated_text: nangunguna
Progress: 0.23
translated_text: bring
backtranslated_text: dalhin
Progress: 0.23
translated_text: bring
backtranslated_text: dalhin
Progress: 0.23
translated_text: covered
backtranslated_text: sakop
Progress: 0.23
translated_text: kingdom
backtranslated_text: kaharian
Progress: 0.23
translated_text: land
backtranslated_text: lupain
Progress: 0.23
translated_text: property
backtranslated_text: ari-arian
Progress: 0.23
translated_text: arrive
backtranslated_text: dumating
Progress: 0.23
translated_text: will go
backtranslated_text: pupunta
Progress: 0.23
translated_text: come
backtranslated_text: halika
Progress: 0.23
translated_text: go up
backtranslated_text: umakyat ka
Progress: 0.23
translated_text: tread
backtranslated_text: pagtapak
Progress: 0.23
translated_text: landed
backtranslated_text: nakarating
Progress: 0.23
translated_text: fallen
backtranslated_text: nahulog
Progress: 0.23
translated_text: get off
backtranslated_text: bumaba ka
Progress: 0.23
translated_text: universe
backtranslated_text: sansinukob
Progress: 0.23
translated_text: world

backtranslated_text: mundo
Progress: 0.23
translated_text: circle
backtranslated_text: bilog
Progress: 0.23
translated_text: lawn
backtranslated_text: damuhan
Progress: 0.23
translated_text: terrain
backtranslated_text: lupain
Progress: 0.23
translated_text: archipelago
backtranslated_text: kapuluan
Progress: 0.23
translated_text: island
backtranslated_text: isla
Progress: 0.24
translated_text: outburst
backtranslated_text: pagsabog
Progress: 0.24
translated_text: seizures
backtranslated_text: mga seizure
Progress: 0.24
translated_text: lupit
backtranslated_text: lupit
Progress: 0.24
translated_text: fatality
backtranslated_text: pagkamatay
Progress: 0.24
translated_text: brutal
backtranslated_text: brutal
Progress: 0.24
translated_text: stops
backtranslated_text: huminto
Progress: 0.24
translated_text: shampoo
backtranslated_text: shampoo
Progress: 0.24
translated_text: twenty
backtranslated_text: dalawampu
Progress: 0.24
translated_text: fourteen
backtranslated_text: labing-apat
Progress: 0.24
translated_text: dosena
backtranslated_text: dosena
Progress: 0.24
translated_text: Eleven
backtranslated_text: Labing-isa
Progress: 0.24
translated_text: ten
backtranslated_text: sampu
Progress: 0.24
translated_text: nine
backtranslated_text: siyam
Progress: 0.24
translated_text: eight
backtranslated_text: walo
Progress: 0.24
translated_text: eighth
backtranslated_text: ikawalo
Progress: 0.24
translated_text: three
backtranslated_text: tatlo
Progress: 0.24
translated_text: four
backtranslated_text: apat
Progress: 0.24
translated_text: anim
backtranslated_text: anim
Progress: 0.24
translated_text: seven
backtranslated_text: pito
Progress: 0.24
translated_text: appointment
backtranslated_text: appointment
Progress: 0.24
translated_text: election
backtranslated_text: eleksyon
Progress: 0.24
translated_text: elections
backtranslated_text: halalan
Progress: 0.24
translated_text: polls
backtranslated_text: mga botohan
Progress: 0.24
translated_text: elections
backtranslated_text: halalan
Progress: 0.24
translated_text: hill
backtranslated_text: burol
Progress: 0.24
translated_text: mountain
backtranslated_text: bundok
Progress: 0.25
translated_text: discussion
backtranslated_text: talakayan
Progress: 0.25
translated_text: balitaktakan
backtranslated_text: balitaktakan
Progress: 0.25
translated_text: opposite
backtranslated_text: kabaligtaran
Progress: 0.25
translated_text: contrary
backtranslated_text: salungat
Progress: 0.25
translated_text: same
backtranslated_text: pareho
Progress: 0.25
translated_text: the bible
backtranslated_text: Ang Bibliya
Progress: 0.25
translated_text: bible
backtranslated_text: bibliya
Progress: 0.25
translated_text: decades
backtranslated_text: mga dekada
Progress: 0.25
translated_text: century
backtranslated_text: siglo
Progress: 0.25
translated_text: una
backtranslated_text: una
Progress: 0.25
translated_text: thousand
backtranslated_text: libo
Progress: 0.25
translated_text: identical
backtranslated_text: magkapareho
Progress: 0.25
translated_text: identical
backtranslated_text: magkapareho
Progress: 0.25
translated_text: uno
backtranslated_text: uno
Progress: 0.25
translated_text: isa
backtranslated_text: ay isang
Progress: 0.25
translated_text: ace
backtranslated_text: alas
Progress: 0.25
translated_text: laos
backtranslated_text: laos
Progress: 0.25
translated_text: side
backtranslated_text: gilid
Progress: 0.25
translated_text: or
backtranslated_text: o
Progress: 0.25
translated_text: baybay
backtranslated_text: Bay bay
Progress: 0.25
translated_text: edge
backtranslated_text: gilid
Progress: 0.25
translated_text: week
backtranslated_text: linggo
Progress: 0.25
translated_text: beetle
backtranslated_text: salagubang
Progress: 0.25
translated_text: blanket
backtranslated_text: kumot
Progress: 0.25
translated_text: polite
backtranslated_text: magalang
Progress: 0.25
translated_text: arrogant
backtranslated_text: mayabang
Progress: 0.26
translated_text: arrogant
backtranslated_text: mayabang
Progress: 0.26
translated_text: arrogant
backtranslated_text: mayabang
Progress: 0.26
translated_text: arrogant
backtranslated_text: mayabang
Progress: 0.26
translated_text: silver
backtranslated_text: pilak
Progress: 0.26
translated_text: city
backtranslated_text: lungsod
Progress: 0.26
translated_text: pedal
backtranslated_text: pedal
Progress: 0.26
translated_text: footprints
backtranslated_text: bakas ng paa
Progress: 0.26
translated_text: bicycle
backtranslated_text: Bisikleta
Progress: 0.26
translated_text: starve
backtranslated_text: gutom
Progress: 0.26
translated_text: aspire
backtranslated_text: maghangad
Progress: 0.26
translated_text: hungry
backtranslated_text: gutom
Progress: 0.26
translated_text: longing
backtranslated_text: pananabik
Progress: 0.26
translated_text: desire
backtranslated_text: pagnanasa
Progress: 0.26
translated_text: hunger
backtranslated_text: gutom
Progress: 0.26
translated_text: hungry
backtranslated_text: gutom
Progress: 0.26
translated_text: eager
backtranslated_text: sabik
Progress: 0.26
translated_text: thirst
backtranslated_text: pagkauhaw
Progress: 0.26
translated_text: joy
backtranslated_text: kagalakan
Progress: 0.26
translated_text: pleasure
backtranslated_text: kasiyahan
Progress: 0.26
translated_text: happiness
backtranslated_text: kaligayahan
Progress: 0.26
translated_text: come
backtranslated_text: halika
Progress: 0.26
translated_text: sumara
backtranslated_text: sumara
Progress: 0.26
translated_text: isara
backtranslated_text: isara
Progress: 0.26
translated_text: stingy
backtranslated_text: kuripot
Progress: 0.26
translated_text: short
backtranslated_text: maikli
Progress: 0.26
translated_text: strictly
backtranslated_text: mahigpit
Progress: 0.27
translated_text: near
backtranslated_text: malapit
Progress: 0.27
translated_text: open
backtranslated_text: bukas
Progress: 0.27
translated_text: hesitant
backtranslated_text: nag-aalangan
Progress: 0.27
translated_text: field
backtranslated_text: patlang
Progress: 0.27
translated_text: tomorrow
backtranslated_text: bukas
Progress: 0.27
translated_text: turned on
backtranslated_text: binuksan
Progress: 0.27
translated_text: because
backtranslated_text: kasi
Progress: 0.27
translated_text: lantad
backtranslated_text: lantad
Progress: 0.27
translated_text: scar
backtranslated_text: peklat
Progress: 0.27
translated_text: hat
backtranslated_text: sumbrero
Progress: 0.27
translated_text: kalo
backtranslated_text: kalo
Progress: 0.27
translated_text: squid
backtranslated_text: pusit
Progress: 0.27
translated_text: squid
backtranslated_text: pusit
Progress: 0.27
translated_text: shield
backtranslated_text: kalasag
Progress: 0.27
translated_text: shield
backtranslated_text: kalasag
Progress: 0.27
translated_text: maton
backtranslated_text: maton
Progress: 0.27
translated_text: sanggano
backtranslated_text: sanggano
Progress: 0.27
translated_text: bullet
backtranslated_text: bala
Progress: 0.27
translated_text: canyon
backtranslated_text: canyon
Progress: 0.27
translated_text: guns
backtranslated_text: mga baril
Progress: 0.27
translated_text: far away
backtranslated_text: malayo
Progress: 0.27
translated_text: remote
backtranslated_text: remote
Progress: 0.27
translated_text: magic
backtranslated_text: mahika
Progress: 0.27
translated_text: queen
backtranslated_text: reyna
Progress: 0.27
translated_text: day
backtranslated_text: araw
Progress: 0.27
translated_text: caution
backtranslated_text: pag-iingat
Progress: 0.28
translated_text: trophy
backtranslated_text: tropeo
Progress: 0.28
translated_text: stolen
backtranslated_text: ninakaw
Progress: 0.28
translated_text: kinurakot
backtranslated_text: kinurakot
Progress: 0.28
translated_text: reward
backtranslated_text: gantimpala
Progress: 0.28
translated_text: won
backtranslated_text: nanalo
Progress: 0.28
translated_text: win
backtranslated_text: panalo
Progress: 0.28
translated_text: reward
backtranslated_text: gantimpala
Progress: 0.28
translated_text: prize
backtranslated_text: premyo
Progress: 0.28
translated_text: compensation
backtranslated_text: kabayaran
Progress: 0.28
translated_text: wagi
backtranslated_text: wagi
Progress: 0.28
translated_text: imagination
backtranslated_text: imahinasyon

Progress: 0.28
translated_text: hallucinations
backtranslated_text: guni-guni
Progress: 0.28
translated_text: illusion
backtranslated_text: ilusyon
Progress: 0.28
translated_text: yin
backtranslated_text: yin
Progress: 0.28
translated_text: guitar
backtranslated_text: gitara
Progress: 0.28
translated_text: yuan
backtranslated_text: yuan
Progress: 0.28
translated_text: yen
backtranslated_text: yen
Progress: 0.28
translated_text: yang
backtranslated_text: yang
Progress: 0.28
translated_text: wen
backtranslated_text: wen
Progress: 0.28
translated_text: won
backtranslated_text: nanalo
Progress: 0.28
translated_text: tenge
backtranslated_text: tenge
Progress: 0.28
translated_text: taka
backtranslated_text: taka
Progress: 0.28
translated_text: sol
backtranslated_text: sol
Progress: 0.28
translated_text: som
backtranslated_text: som
Progress: 0.28
translated_text: shah
backtranslated_text: shah
Progress: 0.28
translated_text: riel
backtranslated_text: riel
Progress: 0.29
translated_text: real
backtranslated_text: totoo
Progress: 0.29
translated_text: red
backtranslated_text: pula
Progress: 0.29
translated_text: pound
backtranslated_text: libra
Progress: 0.29
translated_text: peso
backtranslated_text: piso
Progress: 0.29
translated_text: naira
backtranslated_text: naira
Progress: 0.29
translated_text: mark
backtranslated_text: marka
Progress: 0.29
translated_text: lev
backtranslated_text: lev
Progress: 0.29
translated_text: lek
backtranslated_text: lek
Progress: 0.29
translated_text: kwanza
backtranslated_text: kwanza
Progress: 0.29
translated_text: kina
backtranslated_text: kina
Progress: 0.29
translated_text: you
backtranslated_text: ikaw
Progress: 0.29
translated_text: dong
backtranslated_text: dong
Progress: 0.29
translated_text: dollars
backtranslated_text: dolyar
Progress: 0.29
translated_text: colon
backtranslated_text: colon
Progress: 0.29
translated_text: lead
backtranslated_text: nangunguna
Progress: 0.29
translated_text: gold
backtranslated_text: ginto
Progress: 0.29
translated_text: platinum
backtranslated_text: platinum
Progress: 0.29
translated_text: tin
backtranslated_text: lata
Progress: 0.29
translated_text: silver
backtranslated_text: pilak
Progress: 0.29
translated_text: brass
backtranslated_text: tanso
Progress: 0.29
translated_text: nickel
backtranslated_text: nikel
Progress: 0.29
translated_text: iron
backtranslated_text: bakal
Progress: 0.29
translated_text: titanium
backtranslated_text: titan
Progress: 0.29
translated_text: potassium
backtranslated_text: potasa
Progress: 0.29
translated_text: silicon
backtranslated_text: silikon
Progress: 0.29
translated_text: neon
backtranslated_text: neon
Progress: 0.30
translated_text: carbon
backtranslated_text: carbon
Progress: 0.30
translated_text: hydrogen
backtranslated_text: hydrogen
Progress: 0.30
translated_text: omega
backtranslated_text: omega
Progress: 0.30
translated_text: adam
backtranslated_text: adam
Progress: 0.30
translated_text: ecstasy
backtranslated_text: lubos na kaligayahan
Progress: 0.30
translated_text: go
backtranslated_text: pumunta ka
Progress: 0.30
translated_text: north
backtranslated_text: hilaga
Progress: 0.30
translated_text: to the north
backtranslated_text: sa hilaga
Progress: 0.30
translated_text: metro
backtranslated_text: metro
Progress: 0.30
translated_text: mb
backtranslated_text: mb
Progress: 0.30
translated_text: liter
backtranslated_text: litro
Progress: 0.30
translated_text: kelvin
backtranslated_text: kelvin
Progress: 0.30
translated_text: green
backtranslated_text: berde
Progress: 0.30
translated_text: jet
backtranslated_text: jet
Progress: 0.30
translated_text: kb
backtranslated_text: kb
Progress: 0.30
translated_text: henry
backtranslated_text: henry
Progress: 0.30
translated_text: gb
backtranslated_text: gb
Progress: 0.30
translated_text: gib
backtranslated_text: gib
Progress: 0.30
translated_text: gee
backtranslated_text: sige
Progress: 0.30
translated_text: east
backtranslated_text: silangan
Progress: 0.30
translated_text: onsa
backtranslated_text: onsa
Progress: 0.30
translated_text: pound
backtranslated_text: libra
Progress: 0.30
translated_text: grams
backtranslated_text: gramo
Progress: 0.30
translated_text: kilo
backtranslated_text: kilo
Progress: 0.30
translated_text: tons
backtranslated_text: tonelada
Progress: 0.30
translated_text: utopia
backtranslated_text: utopia
Progress: 0.31
translated_text: zion
backtranslated_text: zion
Progress: 0.31
translated_text: vigor
backtranslated_text: sigla
Progress: 0.31
translated_text: courage
backtranslated_text: lakas ng loob
Progress: 0.31
translated_text: sink
backtranslated_text: lababo
Progress: 0.31
translated_text: peak
backtranslated_text: tugatog
Progress: 0.31
translated_text: peak
backtranslated_text: tugatog
Progress: 0.31
translated_text: zen
backtranslated_text: zen
Progress: 0.31
translated_text: fanatical
backtranslated_text: panatiko
Progress: 0.31
translated_text: eliminate
backtranslated_text: alisin
Progress: 0.31
translated_text: eradicate
backtranslated_text: lipulin
Progress: 0.31
translated_text: kill
backtranslated_text: pumatay
Progress: 0.31
translated_text: stupid
backtranslated_text: bobo
Progress: 0.31
translated_text: stupid
backtranslated_text: bobo
Progress: 0.31
translated_text: dumb
backtranslated_text: pipi
Progress: 0.31
translated_text: anxious
backtranslated_text: balisa
Progress: 0.31
translated_text: zombie
backtranslated_text: zombie
Progress: 0.31
translated_text: can
backtranslated_text: pwede
Progress: 0.31
translated_text: validation
backtranslated_text: pagpapatunay
Progress: 0.31
translated_text: balibol
backtranslated_text: balibol
Progress: 0.31
translated_text: bucket
backtranslated_text: balde
Progress: 0.31
translated_text: bucket
backtranslated_text: balde
Progress: 0.31
translated_text: crippled
backtranslated_text: baldado
Progress: 0.31
translated_text: crippled
backtranslated_text: baldado
Progress: 0.31
translated_text: balbal
backtranslated_text: balbal
Progress: 0.31
translated_text: soy
backtranslated_text: toyo
Progress: 0.31
translated_text: framework
backtranslated_text: balangkas
Progress: 0.32
translated_text: grasshopper
backtranslated_text: tipaklong
Progress: 0.32
translated_text: locusts
backtranslated_text: mga balang
Progress: 0.32
translated_text: scales
backtranslated_text: kaliskis
Progress: 0.32
translated_text: balance
backtranslated_text: balanse
Progress: 0.32
translated_text: membrane
backtranslated_text: lamad
Progress: 0.32
translated_text: dandruff
backtranslated_text: balakubak
Progress: 0.32
translated_text: obstacle
backtranslated_text: balakid
Progress: 0.32
translated_text: obstacle
backtranslated_text: balakid
Progress: 0.32
translated_text: elise
backtranslated_text: elise
Progress: 0.32
translated_text: aloy
backtranslated_text: aloy
Progress: 0.32
translated_text: balag
backtranslated_text: balag
Progress: 0.32
translated_text: cloak
backtranslated_text: balabal
Progress: 0.32
translated_text: yard
backtranslated_text: bakuran
Progress: 0.32
translated_text: vaccine
backtranslated_text: bakuna
Progress: 0.32
translated_text: fence
backtranslated_text: bakod
Progress: 0.32
translated_text: bako
backtranslated_text: bako
Progress: 0.32
translated_text: chaos
backtranslated_text: kaguluhan
Progress: 0.32
translated_text: bay
backtranslated_text: bay
Progress: 0.32
translated_text: reef
backtranslated_text: bahura
Progress: 0.32
translated_text: part
backtranslated_text: bahagi
Progress: 0.32
translated_text: brand
backtranslated_text: tatak
Progress: 0.32
translated_text: score
backtranslated_text: puntos
Progress: 0.32
translated_text: grade
backtranslated_text: grado
Progress: 0.32
translated_text: company
backtranslated_text: kumpanya
Progress: 0.32
translated_text: owl
backtranslated_text: kuwago
Progress: 0.32
translated_text: bahala
backtranslated_text: bahala
Progress: 0.33
translated_text: bahag
backtranslated_text: bahag
Progress: 0.33
translated_text: young man
backtranslated_text: binata
Progress: 0.33
translated_text: bachelor
backtranslated_text: bachelor
Progress: 0.33
translated_text: maiden
backtranslated_text: dalaga
Progress: 0.33
translated_text: bored
backtranslated_text: naiinip
Progress: 0.33
translated_text: though

backtranslated_text: bagaman
Progress: 0.33
translated_text: hostile
backtranslated_text: pagalit
Progress: 0.33
translated_text: oration
backtranslated_text: orasyon
Progress: 0.33
translated_text: dilis
backtranslated_text: dilis
Progress: 0.33
translated_text: resemblance
backtranslated_text: pagkakahawig
Progress: 0.33
translated_text: cutting
backtranslated_text: pagputol
Progress: 0.33
translated_text: cut off
backtranslated_text: putulin
Progress: 0.33
translated_text: increase
backtranslated_text: pagtaas
Progress: 0.33
translated_text: fill in
backtranslated_text: punan
Progress: 0.33
translated_text: big
backtranslated_text: malaki
Progress: 0.33
translated_text: broad
backtranslated_text: malawak
Progress: 0.33
translated_text: loose
backtranslated_text: maluwag
Progress: 0.33
translated_text: wide
backtranslated_text: malawak
Progress: 0.33
translated_text: forgiveness
backtranslated_text: pagpapatawad
Progress: 0.33
translated_text: forgetfulness
backtranslated_text: pagkalimot
Progress: 0.33
translated_text: friendship
backtranslated_text: pagkakaibigan
Progress: 0.33
translated_text: lovely
backtranslated_text: kaibig-ibig
Progress: 0.33
translated_text: enjoyable
backtranslated_text: kasiya-siya
Progress: 0.33
translated_text: amendment
backtranslated_text: susog
Progress: 0.33
translated_text: amended
backtranslated_text: sinusugan
Progress: 0.33
translated_text: abangan
backtranslated_text: abangan
Progress: 0.34
translated_text: mine
backtranslated_text: akin
Progress: 0.34
translated_text: ambulance
backtranslated_text: ambulansya
Progress: 0.34
translated_text: ambulance
backtranslated_text: ambulansya
Progress: 0.34
translated_text: kataka-taka
backtranslated_text: kataka-taka
Progress: 0.34
translated_text: astonishment
backtranslated_text: pagtataka
Progress: 0.34
translated_text: tall
backtranslated_text: matangkad
Progress: 0.34
translated_text: altar
backtranslated_text: altar
Progress: 0.34
translated_text: dambana
backtranslated_text: dambana
Progress: 0.34
translated_text: away
backtranslated_text: malayo
Progress: 0.34
translated_text: donate
backtranslated_text: mag-abuloy
Progress: 0.34
translated_text: limos
backtranslated_text: limos
Progress: 0.34
translated_text: specific
backtranslated_text: tiyak
Progress: 0.34
translated_text: about
backtranslated_text: tungkol sa
Progress: 0.34
translated_text: igawad
backtranslated_text: igawad
Progress: 0.34
translated_text: give
backtranslated_text: magbigay
Progress: 0.34
translated_text: bestow
backtranslated_text: ipagkaloob
Progress: 0.34
translated_text: sustento
backtranslated_text: sustento
Progress: 0.34
translated_text: spending
backtranslated_text: paggastos
Progress: 0.34
translated_text: denial
backtranslated_text: pagtanggi
Progress: 0.34
translated_text: rason
backtranslated_text: rason
Progress: 0.34
translated_text: taguri
backtranslated_text: taguri
Progress: 0.34
translated_text: boast
backtranslated_text: magyabang
Progress: 0.34
translated_text: nickname
backtranslated_text: palayaw
Progress: 0.34
translated_text: hallway
backtranslated_text: pasilyo
Progress: 0.34
translated_text: farming
backtranslated_text: pagsasaka
Progress: 0.34
translated_text: agree
backtranslated_text: sumang-ayon
Progress: 0.35
translated_text: pleasing
backtranslated_text: nakalulugod
Progress: 0.35
translated_text: zealous
backtranslated_text: masigasig
Progress: 0.35
translated_text: representative
backtranslated_text: kinatawan
Progress: 0.35
translated_text: agent
backtranslated_text: ahente
Progress: 0.35
translated_text: representative
backtranslated_text: kinatawan
Progress: 0.35
translated_text: agency
backtranslated_text: ahensya
Progress: 0.35
translated_text: branch
backtranslated_text: sangay
Progress: 0.35
translated_text: agency
backtranslated_text: ahensya
Progress: 0.35
translated_text: can be given
backtranslated_text: maaaring ibigay
Progress: 0.35
translated_text: can
backtranslated_text: pwede
Progress: 0.35
translated_text: misfortune
backtranslated_text: kasawian
Progress: 0.35
translated_text: prove
backtranslated_text: patunayan
Progress: 0.35
translated_text: foundation
backtranslated_text: pundasyon
Progress: 0.35
translated_text: friendly
backtranslated_text: palakaibigan
Progress: 0.35
translated_text: loving
backtranslated_text: mapagmahal
Progress: 0.35
translated_text: advertise
backtranslated_text: mag-advertise
Progress: 0.35
translated_text: ilathala
backtranslated_text: ilathala
Progress: 0.35
translated_text: announce
backtranslated_text: ipahayag
Progress: 0.35
translated_text: neighboring
backtranslated_text: kapitbahay
Progress: 0.35
translated_text: adjacent
backtranslated_text: katabi
Progress: 0.35
translated_text: gandahan
backtranslated_text: gandahan
Progress: 0.35
translated_text: recognition
backtranslated_text: pagkilala
Progress: 0.35
translated_text: acquaintance
backtranslated_text: kakilala
Progress: 0.35
translated_text: acquaintance
backtranslated_text: kakilala
Progress: 0.35
translated_text: reputation
backtranslated_text: reputasyon
Progress: 0.35
translated_text: introduce
backtranslated_text: ipakilala
Progress: 0.36
translated_text: let
backtranslated_text: hayaan
Progress: 0.36
translated_text: sting
backtranslated_text: sumakit
Progress: 0.36
translated_text: hurt
backtranslated_text: nasaktan
Progress: 0.36
translated_text: gather
backtranslated_text: magtipon
Progress: 0.36
translated_text: consider
backtranslated_text: isaalang-alang
Progress: 0.36
translated_text: explain
backtranslated_text: ipaliwanag
Progress: 0.36
translated_text: accordingly
backtranslated_text: naaayon
Progress: 0.36
translated_text: unity
backtranslated_text: pagkakaisa
Progress: 0.36
translated_text: reconciliation
backtranslated_text: pagkakasundo
Progress: 0.36
translated_text: diana
backtranslated_text: diana
Progress: 0.36
translated_text: archbishop
backtranslated_text: arsobispo
Progress: 0.36
translated_text: army
backtranslated_text: hukbo
Progress: 0.36
translated_text: architect
backtranslated_text: arkitekto
Progress: 0.36
translated_text: archangel
backtranslated_text: arkanghel
Progress: 0.36
translated_text: abdominal
backtranslated_text: tiyan
Progress: 0.36
translated_text: av
backtranslated_text: av
Progress: 0.36
translated_text: amp
backtranslated_text: amp
Progress: 0.36
translated_text: celebrate
backtranslated_text: magdiwang
Progress: 0.36
translated_text: accident
backtranslated_text: aksidente
Progress: 0.36
translated_text: disaster
backtranslated_text: sakuna
Progress: 0.36
translated_text: point
backtranslated_text: punto
Progress: 0.36
translated_text: acceptance
backtranslated_text: pagtanggap
Progress: 0.36
translated_text: facilitate
backtranslated_text: mapadali
Progress: 0.36
translated_text: speed up
backtranslated_text: bilisan
Progress: 0.36
translated_text: agreed
backtranslated_text: sumang-ayon
Progress: 0.36
translated_text: consent
backtranslated_text: pagpayag
Progress: 0.37
translated_text: academia
backtranslated_text: akademya
Progress: 0.37
translated_text: rich
backtranslated_text: mayaman
Progress: 0.37
translated_text: abundant
backtranslated_text: sagana
Progress: 0.37
translated_text: abundance
backtranslated_text: kasaganaan
Progress: 0.37
translated_text: yaman
backtranslated_text: yaman
Progress: 0.37
translated_text: very much
backtranslated_text: sobra
Progress: 0.37
translated_text: sobra
backtranslated_text: sobra
Progress: 0.37
translated_text: funny
backtranslated_text: nakakatawa
Progress: 0.37
translated_text: avoid
backtranslated_text: iwasan
Progress: 0.37
translated_text: absorb
backtranslated_text: sumipsip
Progress: 0.37
translated_text: suck
backtranslated_text: sipsipin
Progress: 0.37
translated_text: quite
backtranslated_text: medyo
Progress: 0.37
translated_text: loss
backtranslated_text: pagkawala
Progress: 0.37
translated_text: absence
backtranslated_text: kawalan
Progress: 0.37
translated_text: suddenly
backtranslated_text: bigla
Progress: 0.37
translated_text: shorten
backtranslated_text: paikliin
Progress: 0.37
translated_text: hingil
backtranslated_text: hingil
Progress: 0.37
translated_text: failed
backtranslated_text: nabigo
Progress: 0.37
translated_text: departure

backtranslated_text: pag-alis
Progress: 0.37
translated_text: elimination
backtranslated_text: pag-aalis
Progress: 0.37
translated_text: repeal
backtranslated_text: bawiin
Progress: 0.37
translated_text: remove
backtranslated_text: tanggalin
Progress: 0.37
translated_text: so
backtranslated_text: kaya
Progress: 0.37
translated_text: waiting
backtranslated_text: naghihintay
Progress: 0.37
translated_text: restraint
backtranslated_text: pagpigil
Progress: 0.37
translated_text: sweep away
backtranslated_text: walisin
Progress: 0.38
translated_text: resignation
backtranslated_text: pagbibitiw
Progress: 0.38
translated_text: resign
backtranslated_text: magbitiw
Progress: 0.38
translated_text: subside
backtranslated_text: humupa
Progress: 0.38
translated_text: let go
backtranslated_text: pakawalan
Progress: 0.38
translated_text: iwan
backtranslated_text: iwan
Progress: 0.38
translated_text: secretly
backtranslated_text: palihim
Progress: 0.38
translated_text: description
backtranslated_text: paglalarawan
Progress: 0.38
translated_text: theme
backtranslated_text: tema
Progress: 0.38
translated_text: motive
backtranslated_text: motibo
Progress: 0.38
translated_text: vision
backtranslated_text: pangitain
Progress: 0.38
translated_text: scene
backtranslated_text: eksena
Progress: 0.38
translated_text: sambitin
backtranslated_text: sambitin
Progress: 0.38
translated_text: horizontal
backtranslated_text: pahalang
Progress: 0.38
translated_text: superimposed
backtranslated_text: nakapatong
Progress: 0.38
translated_text: glue
backtranslated_text: pandikit
Progress: 0.38
translated_text: art
backtranslated_text: sining
Progress: 0.38
translated_text: appreciation
backtranslated_text: pagpapahalaga
Progress: 0.38
translated_text: postscript
backtranslated_text: pahabol
Progress: 0.38
translated_text: proverbs
backtranslated_text: mga salawikain
Progress: 0.38
translated_text: story
backtranslated_text: kwento
Progress: 0.38
translated_text: utter
backtranslated_text: salitain
Progress: 0.38
translated_text: pronounce
backtranslated_text: bigkasin
Progress: 0.38
translated_text: up
backtranslated_text: pataas
Progress: 0.38
translated_text: command
backtranslated_text: utos
Progress: 0.38
translated_text: criticize
backtranslated_text: pumuna
Progress: 0.38
translated_text: singular
backtranslated_text: isahan
Progress: 0.39
translated_text: limitations
backtranslated_text: mga limitasyon
Progress: 0.39
translated_text: dot
backtranslated_text: tuldok
Progress: 0.39
translated_text: rectum
backtranslated_text: tumbong
Progress: 0.39
translated_text: bell
backtranslated_text: kampana
Progress: 0.39
translated_text: timbre
backtranslated_text: timbre
Progress: 0.39
translated_text: prick
backtranslated_text: tusok
Progress: 0.39
translated_text: nails
backtranslated_text: pako
Progress: 0.39
translated_text: heels
backtranslated_text: takong
Progress: 0.39
translated_text: piccolo
backtranslated_text: piccolo
Progress: 0.39
translated_text: gong
backtranslated_text: gong
Progress: 0.39
translated_text: torotot
backtranslated_text: torotot
Progress: 0.39
translated_text: trumpet
backtranslated_text: trumpeta
Progress: 0.39
translated_text: drumstick
backtranslated_text: drumstick
Progress: 0.39
translated_text: flute
backtranslated_text: plauta
Progress: 0.39
translated_text: mouthpiece
backtranslated_text: tagapagsalita
Progress: 0.39
translated_text: spike
backtranslated_text: spike
Progress: 0.39
translated_text: answer
backtranslated_text: sagot
Progress: 0.39
translated_text: tuning
backtranslated_text: pag-tune
Progress: 0.39
translated_text: drone
backtranslated_text: drone
Progress: 0.39
translated_text: kapote
backtranslated_text: kapote
Progress: 0.39
translated_text: numerong
backtranslated_text: numerong
Progress: 0.39
translated_text: guess
backtranslated_text: hulaan
Progress: 0.39
translated_text: study
backtranslated_text: pag-aaral
Progress: 0.39
translated_text: multiplication
backtranslated_text: pagpaparami
Progress: 0.39
translated_text: theory
backtranslated_text: teorya
Progress: 0.39
translated_text: bill
backtranslated_text: bill
Progress: 0.40
translated_text: equivalent
backtranslated_text: katumbas
Progress: 0.40
translated_text: rank
backtranslated_text: ranggo
Progress: 0.40
translated_text: parte
backtranslated_text: bahagi
Progress: 0.40
translated_text: part
backtranslated_text: bahagi
Progress: 0.40
translated_text: generation
backtranslated_text: henerasyon
Progress: 0.40
translated_text: sharing
backtranslated_text: pagbabahagi
Progress: 0.40
translated_text: division
backtranslated_text: dibisyon
Progress: 0.40
translated_text: division
backtranslated_text: dibisyon
Progress: 0.40
translated_text: divide
backtranslated_text: hatiin
Progress: 0.40
translated_text: trillion
backtranslated_text: trilyon
Progress: 0.40
translated_text: billion
backtranslated_text: bilyon
Progress: 0.40
translated_text: million
backtranslated_text: milyon
Progress: 0.40
translated_text: land
backtranslated_text: lupain
Progress: 0.40
translated_text: ferry
backtranslated_text: lantsa
Progress: 0.40
translated_text: throw away
backtranslated_text: Itapon mo
Progress: 0.40
translated_text: ibasura
backtranslated_text: ibasura
Progress: 0.40
translated_text: boat
backtranslated_text: bangka
Progress: 0.40
translated_text: binta
backtranslated_text: binta
Progress: 0.40
translated_text: submarine
backtranslated_text: submarino
Progress: 0.40
translated_text: ruler
backtranslated_text: tagapamahala
Progress: 0.40
translated_text: stapler
backtranslated_text: stapler
Progress: 0.40
translated_text: officer
backtranslated_text: opisyal
Progress: 0.40
translated_text: metric
backtranslated_text: panukat
Progress: 0.40
translated_text: puncher
backtranslated_text: manuntok
Progress: 0.40
translated_text: sour
backtranslated_text: maasim
Progress: 0.40
translated_text: acidic
backtranslated_text: acidic
Progress: 0.41
translated_text: rambutan
backtranslated_text: rambutan
Progress: 0.41
translated_text: pasas
backtranslated_text: pasas
Progress: 0.41
translated_text: watermelon
backtranslated_text: pakwan
Progress: 0.41
translated_text: grenade
backtranslated_text: granada
Progress: 0.41
translated_text: duhat
backtranslated_text: duhat
Progress: 0.41
translated_text: pineapple
backtranslated_text: pinya
Progress: 0.41
translated_text: papaya
backtranslated_text: papaya
Progress: 0.41
translated_text: dalandan
backtranslated_text: dalandan
Progress: 0.41
translated_text: mango
backtranslated_text: mangga
Progress: 0.41
translated_text: kiwi
backtranslated_text: kiwi
Progress: 0.41
translated_text: rare
backtranslated_text: bihira
Progress: 0.41
translated_text: guava
backtranslated_text: bayabas
Progress: 0.41
translated_text: grapes
backtranslated_text: ubas
Progress: 0.41
translated_text: suha
backtranslated_text: suha
Progress: 0.41
translated_text: figs
backtranslated_text: igos
Progress: 0.41
translated_text: buko
backtranslated_text: buko
Progress: 0.41
translated_text: tomatoes
backtranslated_text: mga kamatis
Progress: 0.41
translated_text: bananas
backtranslated_text: saging
Progress: 0.41
translated_text: apples
backtranslated_text: mansanas
Progress: 0.41
translated_text: caldereta
backtranslated_text: kaldereta
Progress: 0.41
translated_text: tinola
backtranslated_text: tinola
Progress: 0.41
translated_text: porridge
backtranslated_text: sinigang
Progress: 0.41
translated_text: stewed
backtranslated_text: nilaga
Progress: 0.41
translated_text: momentary
backtranslated_text: panandalian
Progress: 0.41
translated_text: in the meantime
backtranslated_text: samantala
Progress: 0.41
translated_text: shrink
backtranslated_text: lumiit
Progress: 0.42
translated_text: very deep
backtranslated_text: napakalalim
Progress: 0.42
translated_text: inventory
backtranslated_text: imbentaryo
Progress: 0.42
translated_text: capital
backtranslated_text: kabisera
Progress: 0.42
translated_text: investment
backtranslated_text: pamumuhunan
Progress: 0.42
translated_text: steam
backtranslated_text: singaw
Progress: 0.42
translated_text: victim
backtranslated_text: biktima
Progress: 0.42
translated_text: guardian
backtranslated_text: tagapag-alaga
Progress: 0.42
translated_text: protector

backtranslated_text: tagapagtanggol
Progress: 0.42
translated_text: protector
backtranslated_text: tagapagtanggol
Progress: 0.42
translated_text: cheater
backtranslated_text: manloloko
Progress: 0.42
translated_text: manloloko
backtranslated_text: manloloko
Progress: 0.42
translated_text: swift
backtranslated_text: matulin
Progress: 0.42
translated_text: fast
backtranslated_text: mabilis
Progress: 0.42
translated_text: commander
backtranslated_text: kumander
Progress: 0.42
translated_text: barely
backtranslated_text: bahagya
Progress: 0.42
translated_text: minor
backtranslated_text: menor de edad
Progress: 0.42
translated_text: novice
backtranslated_text: baguhan
Progress: 0.42
translated_text: beginner
backtranslated_text: baguhan
Progress: 0.42
translated_text: wonder
backtranslated_text: pagtataka
Progress: 0.42
translated_text: liking
backtranslated_text: pagkagusto
Progress: 0.42
translated_text: harvesting
backtranslated_text: pag-aani
Progress: 0.42
translated_text: saving
backtranslated_text: nagtitipid
Progress: 0.42
translated_text: infection
backtranslated_text: impeksyon
Progress: 0.42
translated_text: mortal
backtranslated_text: mortal
Progress: 0.42
translated_text: deadly
backtranslated_text: nakamamatay
Progress: 0.42
translated_text: frame
backtranslated_text: kuwadro
Progress: 0.43
translated_text: professional
backtranslated_text: propesyonal
Progress: 0.43
translated_text: over
backtranslated_text: tapos na
Progress: 0.43
translated_text: witch
backtranslated_text: mangkukulam
Progress: 0.43
translated_text: clown
backtranslated_text: payaso
Progress: 0.43
translated_text: voodoo
backtranslated_text: voodoo
Progress: 0.43
translated_text: disciple
backtranslated_text: alagad
Progress: 0.43
translated_text: disciple
backtranslated_text: alagad
Progress: 0.43
translated_text: slipped
backtranslated_text: nadulas
Progress: 0.43
translated_text: panda
backtranslated_text: panda
Progress: 0.43
translated_text: predator
backtranslated_text: mandaragit
Progress: 0.43
translated_text: pebble
backtranslated_text: maliit na bato
Progress: 0.43
translated_text: giant
backtranslated_text: higante
Progress: 0.43
translated_text: unos
backtranslated_text: unos
Progress: 0.43
translated_text: crazy
backtranslated_text: baliw
Progress: 0.43
translated_text: mad
backtranslated_text: galit
Progress: 0.43
translated_text: ungas
backtranslated_text: ungas
Progress: 0.43
translated_text: sentri
backtranslated_text: sentri
Progress: 0.43
translated_text: sentinel
backtranslated_text: sentinel
Progress: 0.43
translated_text: guwardiya
backtranslated_text: guwardiya
Progress: 0.43
translated_text: bane
backtranslated_text: bane
Progress: 0.43
translated_text: rebellion
backtranslated_text: paghihimagsik
Progress: 0.43
translated_text: mosquitoes
backtranslated_text: mga lamok
Progress: 0.43
translated_text: jogging
backtranslated_text: jogging
Progress: 0.43
translated_text: swim
backtranslated_text: lumangoy
Progress: 0.43
translated_text: fishing
backtranslated_text: pangingisda
Progress: 0.43
translated_text: poker
backtranslated_text: poker
Progress: 0.44
translated_text: lady
backtranslated_text: ginang
Progress: 0.44
translated_text: chess
backtranslated_text: chess
Progress: 0.44
translated_text: hockey
backtranslated_text: hockey
Progress: 0.44
translated_text: cursed
backtranslated_text: isinumpa
Progress: 0.44
translated_text: basketball
backtranslated_text: basketball
Progress: 0.44
translated_text: basketball
backtranslated_text: basketball
Progress: 0.44
translated_text: billiards
backtranslated_text: bilyaran
Progress: 0.44
translated_text: darts
backtranslated_text: darts
Progress: 0.44
translated_text: bowling
backtranslated_text: bowling
Progress: 0.44
translated_text: pingpong
backtranslated_text: Ping pong
Progress: 0.44
translated_text: badminton
backtranslated_text: badminton
Progress: 0.44
translated_text: sumo
backtranslated_text: sumo
Progress: 0.44
translated_text: karate
backtranslated_text: karate
Progress: 0.44
translated_text: boxing
backtranslated_text: boksing
Progress: 0.44
translated_text: lungs
backtranslated_text: baga
Progress: 0.44
translated_text: intestines
backtranslated_text: bituka
Progress: 0.44
translated_text: heart
backtranslated_text: puso
Progress: 0.44
translated_text: feet
backtranslated_text: paa
Progress: 0.44
translated_text: tongue
backtranslated_text: dila
Progress: 0.44
translated_text: ipin
backtranslated_text: ipin
Progress: 0.44
translated_text: teeth
backtranslated_text: ngipin
Progress: 0.44
translated_text: eyelashes
backtranslated_text: pilikmata
Progress: 0.44
translated_text: cheeks
backtranslated_text: pisngi
Progress: 0.44
translated_text: throat
backtranslated_text: lalamunan
Progress: 0.44
translated_text: waist
backtranslated_text: baywang
Progress: 0.44
translated_text: noo
backtranslated_text: noo
Progress: 0.45
translated_text: shoulder
backtranslated_text: balikat
Progress: 0.45
translated_text: the brain
backtranslated_text: ang utak
Progress: 0.45
translated_text: kiki
backtranslated_text: kiki
Progress: 0.45
translated_text: bilat
backtranslated_text: bilat
Progress: 0.45
translated_text: burat
backtranslated_text: burat
Progress: 0.45
translated_text: titi
backtranslated_text: titi
Progress: 0.45
translated_text: back
backtranslated_text: pabalik
Progress: 0.45
translated_text: butt
backtranslated_text: puwit
Progress: 0.45
translated_text: hita
backtranslated_text: tamaan ang
Progress: 0.45
translated_text: sense of smell
backtranslated_text: pang-amoy
Progress: 0.45
translated_text: nose
backtranslated_text: ilong
Progress: 0.45
translated_text: bunganga
backtranslated_text: bunganga
Progress: 0.45
translated_text: mouth
backtranslated_text: bibig
Progress: 0.45
translated_text: snout
backtranslated_text: nguso
Progress: 0.45
translated_text: head
backtranslated_text: ulo
Progress: 0.45
translated_text: knee
backtranslated_text: tuhod
Progress: 0.45
translated_text: baba
backtranslated_text: baba
Progress: 0.45
translated_text: hip
backtranslated_text: balakang
Progress: 0.45
translated_text: hand
backtranslated_text: kamay
Progress: 0.45
translated_text: leeg
backtranslated_text: leeg
Progress: 0.45
translated_text: hair
backtranslated_text: buhok
Progress: 0.45
translated_text: feet
backtranslated_text: paa
Progress: 0.45
translated_text: fingers
backtranslated_text: mga daliri
Progress: 0.45
translated_text: fist
backtranslated_text: kamao
Progress: 0.45
translated_text: elbow
backtranslated_text: siko
Progress: 0.45
translated_text: thumb
backtranslated_text: hinlalaki
Progress: 0.46
translated_text: breasts
backtranslated_text: mga suso
Progress: 0.46
translated_text: chest
backtranslated_text: dibdib
Progress: 0.46
translated_text: daughter
backtranslated_text: anak na babae
Progress: 0.46
translated_text: puson
backtranslated_text: puson
Progress: 0.46
translated_text: stomach
backtranslated_text: tiyan
Progress: 0.46
translated_text: sikmura
backtranslated_text: sikmura
Progress: 0.46
translated_text: eyebrows
backtranslated_text: kilay
Progress: 0.46
translated_text: eyes
backtranslated_text: mata
Progress: 0.46
translated_text: wolf
backtranslated_text: lobo
Progress: 0.46
translated_text: whales
backtranslated_text: mga balyena
Progress: 0.46
translated_text: turtles
backtranslated_text: mga pagong
Progress: 0.46
translated_text: turtle
backtranslated_text: pagong
Progress: 0.46
translated_text: tiger
backtranslated_text: tigre
Progress: 0.46
translated_text: maya
backtranslated_text: maya
Progress: 0.46
translated_text: arm
backtranslated_text: braso
Progress: 0.46
translated_text: arm
backtranslated_text: braso
Progress: 0.46
translated_text: snake
backtranslated_text: ahas
Progress: 0.46
translated_text: seal
backtranslated_text: selyo
Progress: 0.46
translated_text: sardines
backtranslated_text: sardinas
Progress: 0.46
translated_text: rabbit
backtranslated_text: kuneho
Progress: 0.46
translated_text: quail
backtranslated_text: pugo
Progress: 0.46
translated_text: oyster
backtranslated_text: talaba
Progress: 0.46
translated_text: owl
backtranslated_text: kuwago
Progress: 0.46
translated_text: mare
backtranslated_text: mare
Progress: 0.46
translated_text: leon

backtranslated_text: leon
Progress: 0.46
translated_text: muning
backtranslated_text: muning
Progress: 0.47
translated_text: kittens
backtranslated_text: mga kuting
Progress: 0.47
translated_text: tentacle
backtranslated_text: galamay
Progress: 0.47
translated_text: jellyfish
backtranslated_text: dikya
Progress: 0.47
translated_text: horse
backtranslated_text: kabayo
Progress: 0.47
translated_text: hen
backtranslated_text: hen
Progress: 0.47
translated_text: hawk
backtranslated_text: lawin
Progress: 0.47
translated_text: goat
backtranslated_text: kambing
Progress: 0.47
translated_text: goose
backtranslated_text: gansa
Progress: 0.47
translated_text: fish
backtranslated_text: isda
Progress: 0.47
translated_text: emu
backtranslated_text: emu
Progress: 0.47
translated_text: elephant
backtranslated_text: elepante
Progress: 0.47
translated_text: duck
backtranslated_text: itik
Progress: 0.47
translated_text: duck
backtranslated_text: itik
Progress: 0.47
translated_text: dragon
backtranslated_text: Dragon
Progress: 0.47
translated_text: pigeon
backtranslated_text: kalapati
Progress: 0.47
translated_text: tilaok
backtranslated_text: tilaok
Progress: 0.47
translated_text: crow
backtranslated_text: uwak
Progress: 0.47
translated_text: bones
backtranslated_text: buto
Progress: 0.47
translated_text: skeleton
backtranslated_text: kalansay
Progress: 0.47
translated_text: skull
backtranslated_text: bungo
Progress: 0.47
translated_text: jaw
backtranslated_text: panga
Progress: 0.47
translated_text: crocodile
backtranslated_text: buwaya
Progress: 0.47
translated_text: stork
backtranslated_text: tagak
Progress: 0.47
translated_text: cobra
backtranslated_text: ulupong
Progress: 0.47
translated_text: ipis
backtranslated_text: ipis
Progress: 0.47
translated_text: buffalo
backtranslated_text: kalabaw
Progress: 0.48
translated_text: baka
backtranslated_text: baka
Progress: 0.48
translated_text: cat
backtranslated_text: pusa
Progress: 0.48
translated_text: desert
backtranslated_text: disyerto
Progress: 0.48
translated_text: camel
backtranslated_text: kamelyo
Progress: 0.48
translated_text: birds
backtranslated_text: mga ibon
Progress: 0.48
translated_text: bee
backtranslated_text: bubuyog
Progress: 0.48
translated_text: bee
backtranslated_text: bubuyog
Progress: 0.48
translated_text: bear
backtranslated_text: oso
Progress: 0.48
translated_text: paniki
backtranslated_text: paniki
Progress: 0.48
translated_text: ass
backtranslated_text: puwet
Progress: 0.48
translated_text: gorilla
backtranslated_text: bakulaw
Progress: 0.48
translated_text: monkey
backtranslated_text: unggoy
Progress: 0.48
translated_text: matsing
backtranslated_text: matsing
Progress: 0.48
translated_text: langgam
backtranslated_text: langgam
Progress: 0.48
translated_text: anniversary
backtranslated_text: anibersaryo
Progress: 0.48
translated_text: like
backtranslated_text: gaya ng
Progress: 0.48
translated_text: total
backtranslated_text: kabuuan
Progress: 0.48
translated_text: composition
backtranslated_text: komposisyon
Progress: 0.48
translated_text: limited
backtranslated_text: limitado
Progress: 0.48
translated_text: humor
backtranslated_text: katatawanan
Progress: 0.48
translated_text: comedy
backtranslated_text: komedya
Progress: 0.48
translated_text: lyrics
backtranslated_text: lyrics
Progress: 0.48
translated_text: database
backtranslated_text: database
Progress: 0.48
translated_text: list
backtranslated_text: listahan
Progress: 0.48
translated_text: list
backtranslated_text: listahan
Progress: 0.48
translated_text: global
backtranslated_text: global
Progress: 0.49
translated_text: socks
backtranslated_text: medyas
Progress: 0.49
translated_text: bank
backtranslated_text: bangko
Progress: 0.49
translated_text: windows
backtranslated_text: mga bintana
Progress: 0.49
translated_text: the door
backtranslated_text: ang pintuan
Progress: 0.49
translated_text: door
backtranslated_text: pinto
Progress: 0.49
translated_text: shoes
backtranslated_text: sapatos
Progress: 0.49
translated_text: parole
backtranslated_text: parol
Progress: 0.49
translated_text: fan
backtranslated_text: tagahanga
Progress: 0.49
translated_text: fill
backtranslated_text: punan
Progress: 0.49
translated_text: defeat
backtranslated_text: pagkatalo
Progress: 0.49
translated_text: clean
backtranslated_text: malinis
Progress: 0.49
translated_text: impossible
backtranslated_text: imposible
Progress: 0.49
translated_text: test
backtranslated_text: pagsusulit
Progress: 0.49
translated_text: examination
backtranslated_text: pagsusuri
Progress: 0.49
translated_text: exam
backtranslated_text: pagsusulit
Progress: 0.49
translated_text: matches
backtranslated_text: mga posporo
Progress: 0.49
translated_text: uniforms
backtranslated_text: mga uniporme
Progress: 0.49
translated_text: appetizer
backtranslated_text: pampagana
Progress: 0.49
translated_text: pulutan
backtranslated_text: pulutan
Progress: 0.49
translated_text: lundag
backtranslated_text: lundag
Progress: 0.49
translated_text: talon
backtranslated_text: talon
Progress: 0.49
translated_text: miscellaneous
backtranslated_text: sari-sari
Progress: 0.49
translated_text: halo-halo
backtranslated_text: halo-halo
Progress: 0.49
translated_text: posture
backtranslated_text: tindig
Progress: 0.49
translated_text: tayo
backtranslated_text: tayo
Progress: 0.49
translated_text: bearing
backtranslated_text: tindig
Progress: 0.50
translated_text: sori
backtranslated_text: sori
Progress: 0.50
translated_text: sorry
backtranslated_text: sorry
Progress: 0.50
translated_text: often
backtranslated_text: madalas
Progress: 0.50
translated_text: often
backtranslated_text: madalas
Progress: 0.50
translated_text: whip
backtranslated_text: latigo
Progress: 0.50
translated_text: bump
backtranslated_text: mauntog
Progress: 0.50
translated_text: tracker
backtranslated_text: tagasubaybay
Progress: 0.50
translated_text: fans
backtranslated_text: tagahanga
Progress: 0.50
translated_text: certainly
backtranslated_text: tiyak
Progress: 0.50
translated_text: sure
backtranslated_text: sigurado
Progress: 0.50
translated_text: once
backtranslated_text: minsan
Progress: 0.50
translated_text: for sure
backtranslated_text: Sigurado
Progress: 0.50
translated_text: dumausdos
backtranslated_text: dumausdos
Progress: 0.50
translated_text: prolong
backtranslated_text: pahabain
Progress: 0.50
translated_text: extend
backtranslated_text: pahabain
Progress: 0.50
translated_text: sell
backtranslated_text: magbenta
Progress: 0.50
translated_text: sell
backtranslated_text: magbenta
Progress: 0.50
translated_text: kabigin
backtranslated_text: kabigin
Progress: 0.50
translated_text: hingi
backtranslated_text: hihi
Progress: 0.50
translated_text: hug
backtranslated_text: yakapin
Progress: 0.50
translated_text: hug
backtranslated_text: yakapin
Progress: 0.50
translated_text: similar
backtranslated_text: katulad
Progress: 0.50
translated_text: history
backtranslated_text: kasaysayan
Progress: 0.50
translated_text: cable
backtranslated_text: kable
Progress: 0.50
translated_text: stay away
backtranslated_text: lumayo
Progress: 0.51
translated_text: kawala
backtranslated_text: kawala
Progress: 0.51
translated_text: takas
backtranslated_text: takas
Progress: 0.51
translated_text: materials
backtranslated_text: materyales
Progress: 0.51
translated_text: using
backtranslated_text: gamit
Progress: 0.51
translated_text: instrument
backtranslated_text: instrumento
Progress: 0.51
translated_text: evaluation
backtranslated_text: pagsusuri
Progress: 0.51
translated_text: fallacy
backtranslated_text: kamalian
Progress: 0.51
translated_text: failure
backtranslated_text: kabiguan
Progress: 0.51
translated_text: star
backtranslated_text: bituin
Progress: 0.51
translated_text: story
backtranslated_text: kwento
Progress: 0.51
translated_text: twilight
backtranslated_text: takipsilim
Progress: 0.51
translated_text: sunset
backtranslated_text: paglubog ng araw
Progress: 0.51
translated_text: telephone
backtranslated_text: telepono
Progress: 0.51
translated_text: kapos
backtranslated_text: kapos
Progress: 0.51
translated_text: sharp
backtranslated_text: matalas
Progress: 0.51
translated_text: sharp
backtranslated_text: matalas
Progress: 0.51
translated_text: crush

backtranslated_text: crush
Progress: 0.51
translated_text: community
backtranslated_text: pamayanan
Progress: 0.51
translated_text: terrorist
backtranslated_text: terorista
Progress: 0.51
translated_text: bandit
backtranslated_text: bandido
Progress: 0.51
translated_text: writing
backtranslated_text: pagsusulat
Progress: 0.51
translated_text: prisoner
backtranslated_text: bilanggo
Progress: 0.51
translated_text: prisoner
backtranslated_text: bilanggo
Progress: 0.51
translated_text: supply
backtranslated_text: panustos
Progress: 0.51
translated_text: vow
backtranslated_text: panata
Progress: 0.51
translated_text: promise
backtranslated_text: pangako
Progress: 0.52
translated_text: hataw
backtranslated_text: hataw
Progress: 0.52
translated_text: palo
backtranslated_text: palo
Progress: 0.52
translated_text: ringing
backtranslated_text: nagri-ring
Progress: 0.52
translated_text: music
backtranslated_text: musika
Progress: 0.52
translated_text: swerte
backtranslated_text: swerte
Progress: 0.52
translated_text: lucky
backtranslated_text: maswerte
Progress: 0.52
translated_text: lucky
backtranslated_text: maswerte
Progress: 0.52
translated_text: point
backtranslated_text: punto
Progress: 0.52
translated_text: letter
backtranslated_text: sulat
Progress: 0.52
translated_text: capital
backtranslated_text: kabisera
Progress: 0.52
translated_text: capitol
backtranslated_text: kapitolyo
Progress: 0.52
translated_text: summary
backtranslated_text: buod
Progress: 0.52
translated_text: sadness
backtranslated_text: kalungkutan
Progress: 0.52
translated_text: jar
backtranslated_text: banga
Progress: 0.52
translated_text: boat
backtranslated_text: bangka
Progress: 0.52
translated_text: banga
backtranslated_text: banga
Progress: 0.52
translated_text: confidence
backtranslated_text: kumpiyansa
Progress: 0.52
translated_text: trust
backtranslated_text: magtiwala
Progress: 0.52
translated_text: candle
backtranslated_text: kandila
Progress: 0.52
translated_text: electricity
backtranslated_text: kuryente
Progress: 0.52
translated_text: electricity
backtranslated_text: kuryente
Progress: 0.52
translated_text: blue
backtranslated_text: asul
Progress: 0.52
translated_text: blue
backtranslated_text: asul
Progress: 0.52
translated_text: get over
backtranslated_text: lagpasan
Progress: 0.52
translated_text: survive
backtranslated_text: mabuhay
Progress: 0.52
translated_text: miracle
backtranslated_text: himala
Progress: 0.53
translated_text: miracle
backtranslated_text: himala
Progress: 0.53
translated_text: money
backtranslated_text: pera
Progress: 0.53
translated_text: money
backtranslated_text: pera
Progress: 0.53
translated_text: lens
backtranslated_text: lente
Progress: 0.53
translated_text: song
backtranslated_text: kanta
Progress: 0.53
translated_text: investigation
backtranslated_text: pagsisiyasat
Progress: 0.53
translated_text: research
backtranslated_text: pananaliksik
Progress: 0.53
translated_text: room
backtranslated_text: silid
Progress: 0.53
translated_text: room
backtranslated_text: silid
Progress: 0.53
translated_text: speed
backtranslated_text: bilis
Progress: 0.53
translated_text: weapons
backtranslated_text: mga armas
Progress: 0.53
translated_text: weapons
backtranslated_text: mga armas
Progress: 0.53
translated_text: sipa
backtranslated_text: sipa
Progress: 0.53
translated_text: tadyak
backtranslated_text: tadyak
Progress: 0.53
translated_text: disturb
backtranslated_text: istorbohin
Progress: 0.53
translated_text: disturb
backtranslated_text: istorbohin
Progress: 0.53
translated_text: film
backtranslated_text: pelikula
Progress: 0.53
translated_text: sine
backtranslated_text: sine
Progress: 0.53
translated_text: the beginning
backtranslated_text: ang simula
Progress: 0.53
translated_text: umpisa
backtranslated_text: umpisa
Progress: 0.53
translated_text: trained
backtranslated_text: sinanay
Progress: 0.53
translated_text: expert
backtranslated_text: dalubhasa
Progress: 0.53
translated_text: arguing
backtranslated_text: nagtatalo
Progress: 0.53
translated_text: suyo
backtranslated_text: suyo
Progress: 0.53
translated_text: wild
backtranslated_text: ligaw
Progress: 0.53
translated_text: nap
backtranslated_text: idlip
Progress: 0.54
translated_text: asleep
backtranslated_text: natutulog
Progress: 0.54
translated_text: duda
backtranslated_text: duda
Progress: 0.54
translated_text: doubt
backtranslated_text: pagdududa
Progress: 0.54
translated_text: glance
backtranslated_text: sulyap
Progress: 0.54
translated_text: think
backtranslated_text: isipin mo
Progress: 0.54
translated_text: relos
backtranslated_text: relos
Progress: 0.54
translated_text: unawa
backtranslated_text: unawa
Progress: 0.54
translated_text: intindi
backtranslated_text: intindi
Progress: 0.54
translated_text: cage
backtranslated_text: kulungan
Progress: 0.54
translated_text: dungeon
backtranslated_text: piitan
Progress: 0.54
translated_text: prison
backtranslated_text: bilangguan
Progress: 0.54
translated_text: captain
backtranslated_text: kapitan
Progress: 0.54
translated_text: sabit
backtranslated_text: sabit
Progress: 0.54
translated_text: inom
backtranslated_text: inom
Progress: 0.54
translated_text: suction
backtranslated_text: pagsipsip
Progress: 0.54
translated_text: suck
backtranslated_text: sipsipin
Progress: 0.54
translated_text: kalkal
backtranslated_text: kalkal
Progress: 0.54
translated_text: stab
backtranslated_text: saksakin
Progress: 0.54
translated_text: stitch
backtranslated_text: tahiin
Progress: 0.54
translated_text: stage
backtranslated_text: yugto
Progress: 0.54
translated_text: blast
backtranslated_text: sabog
Progress: 0.54
translated_text: bang
backtranslated_text: putok
Progress: 0.54
translated_text: section
backtranslated_text: seksyon
Progress: 0.54
translated_text: age
backtranslated_text: edad
Progress: 0.54
translated_text: first
backtranslated_text: una
Progress: 0.54
translated_text: signature
backtranslated_text: lagda
Progress: 0.55
translated_text: message
backtranslated_text: mensahe
Progress: 0.55
translated_text: message
backtranslated_text: mensahe
Progress: 0.55
translated_text: letter
backtranslated_text: sulat
Progress: 0.55
translated_text: letter
backtranslated_text: sulat
Progress: 0.55
translated_text: all
backtranslated_text: lahat
Progress: 0.55
translated_text: take
backtranslated_text: kunin
Progress: 0.55
translated_text: accept
backtranslated_text: tanggapin
Progress: 0.55
translated_text: receive
backtranslated_text: tumanggap
Progress: 0.55
translated_text: secret
backtranslated_text: lihim
Progress: 0.55
translated_text: secret
backtranslated_text: lihim
Progress: 0.55
translated_text: drawing
backtranslated_text: pagguhit
Progress: 0.55
translated_text: line
backtranslated_text: linya
Progress: 0.55
translated_text: dedicate
backtranslated_text: mag-alay
Progress: 0.55
translated_text: offer
backtranslated_text: alok
Progress: 0.55
translated_text: government
backtranslated_text: pamahalaan
Progress: 0.55
translated_text: government
backtranslated_text: pamahalaan
Progress: 0.55
translated_text: authority
backtranslated_text: awtoridad
Progress: 0.55
translated_text: warehouse
backtranslated_text: bodega
Progress: 0.55
translated_text: storage
backtranslated_text: imbakan
Progress: 0.55
translated_text: uri
backtranslated_text: uri
Progress: 0.55
translated_text: class
backtranslated_text: klase
Progress: 0.55
translated_text: quality
backtranslated_text: kalidad
Progress: 0.55
translated_text: landas
backtranslated_text: landas
Progress: 0.55
translated_text: delete
backtranslated_text: tanggalin
Progress: 0.55
translated_text: erase
backtranslated_text: burahin
Progress: 0.55
translated_text: gunita
backtranslated_text: gunita
Progress: 0.56
translated_text: memories
backtranslated_text: mga alaala
Progress: 0.56
translated_text: knowledge
backtranslated_text: kaalaman
Progress: 0.56
translated_text: information
backtranslated_text: impormasyon
Progress: 0.56
translated_text: data
backtranslated_text: datos
Progress: 0.56
translated_text: agad
backtranslated_text: agad
Progress: 0.56
translated_text: apura
backtranslated_text: apura
Progress: 0.56
translated_text: command
backtranslated_text: utos
Progress: 0.56
translated_text: dish

backtranslated_text: ulam
Progress: 0.56
translated_text: dish
backtranslated_text: ulam
Progress: 0.56
translated_text: sink
backtranslated_text: lababo
Progress: 0.56
translated_text: size
backtranslated_text: laki
Progress: 0.56
translated_text: extra
backtranslated_text: dagdag
Progress: 0.56
translated_text: opinions
backtranslated_text: opinyon
Progress: 0.56
translated_text: assumption
backtranslated_text: pagpapalagay
Progress: 0.56
translated_text: mental
backtranslated_text: kaisipan
Progress: 0.56
translated_text: opinion
backtranslated_text: opinyon
Progress: 0.56
translated_text: notion
backtranslated_text: paniwala
Progress: 0.56
translated_text: feelings
backtranslated_text: damdamin
Progress: 0.56
translated_text: towards
backtranslated_text: patungo sa
Progress: 0.56
translated_text: statement
backtranslated_text: pahayag
Progress: 0.56
translated_text: news
backtranslated_text: balita
Progress: 0.56
translated_text: shape
backtranslated_text: Hugis
Progress: 0.56
translated_text: curved
backtranslated_text: hubog
Progress: 0.56
translated_text: experience
backtranslated_text: karanasan
Progress: 0.56
translated_text: today
backtranslated_text: ngayon
Progress: 0.56
translated_text: competition
backtranslated_text: kompetisyon
Progress: 0.57
translated_text: contest
backtranslated_text: paligsahan
Progress: 0.57
translated_text: sports
backtranslated_text: laro
Progress: 0.57
translated_text: cultivating
backtranslated_text: paglilinang
Progress: 0.57
translated_text: development
backtranslated_text: pag-unlad
Progress: 0.57
translated_text: reduce
backtranslated_text: bawasan
Progress: 0.57
translated_text: slim down
backtranslated_text: pumayat
Progress: 0.57
translated_text: condition
backtranslated_text: kundisyon
Progress: 0.57
translated_text: response
backtranslated_text: tugon
Progress: 0.57
translated_text: office
backtranslated_text: opisina
Progress: 0.57
translated_text: palit
backtranslated_text: palit
Progress: 0.57
translated_text: iba
backtranslated_text: iba
Progress: 0.57
translated_text: salit
backtranslated_text: salit
Progress: 0.57
translated_text: willing
backtranslated_text: payag
Progress: 0.57
translated_text: let
backtranslated_text: hayaan
Progress: 0.57
translated_text: purpose
backtranslated_text: layunin
Progress: 0.57
translated_text: purpose
backtranslated_text: layunin
Progress: 0.57
translated_text: focus
backtranslated_text: focus
Progress: 0.57
translated_text: law
backtranslated_text: batas
Progress: 0.57
translated_text: akto
backtranslated_text: akto
Progress: 0.57
translated_text: amor
backtranslated_text: pag-ibig
Progress: 0.57
translated_text: dishes
backtranslated_text: mga pinggan
Progress: 0.57
translated_text: siren
backtranslated_text: sirena
Progress: 0.57
translated_text: fell
backtranslated_text: nahulog
Progress: 0.57
translated_text: fell
backtranslated_text: nahulog
Progress: 0.57
translated_text: at
backtranslated_text: sa
Progress: 0.57
translated_text: tsaka
backtranslated_text: tsaka
Progress: 0.58
translated_text: haplos
backtranslated_text: haplos
Progress: 0.58
translated_text: voice
backtranslated_text: boses
Progress: 0.58
translated_text: voice
backtranslated_text: boses
Progress: 0.58
translated_text: summer
backtranslated_text: tag-init
Progress: 0.58
translated_text: summer
backtranslated_text: tag-init
Progress: 0.58
translated_text: cigarette
backtranslated_text: sigarilyo
Progress: 0.58
translated_text: cigarettes
backtranslated_text: mga sigarilyo
Progress: 0.58
translated_text: vessel
backtranslated_text: sisidlan
Progress: 0.58
translated_text: container
backtranslated_text: lalagyan
Progress: 0.58
translated_text: intense
backtranslated_text: matindi
Progress: 0.58
translated_text: grabe
backtranslated_text: grabe
Progress: 0.58
translated_text: convenient
backtranslated_text: maginhawa
Progress: 0.58
translated_text: difficult
backtranslated_text: mahirap
Progress: 0.58
translated_text: hotel
backtranslated_text: hotel
Progress: 0.58
translated_text: cap
backtranslated_text: takip
Progress: 0.58
translated_text: hat
backtranslated_text: sumbrero
Progress: 0.58
translated_text: inside
backtranslated_text: sa loob
Progress: 0.58
translated_text: away
backtranslated_text: malayo
Progress: 0.58
translated_text: paalis
backtranslated_text: paalis
Progress: 0.58
translated_text: off
backtranslated_text: off
Progress: 0.58
translated_text: candy
backtranslated_text: kendi
Progress: 0.58
translated_text: chocolate
backtranslated_text: tsokolate
Progress: 0.58
translated_text: double
backtranslated_text: doble
Progress: 0.58
translated_text: search
backtranslated_text: paghahanap
Progress: 0.58
translated_text: buy
backtranslated_text: bumili
Progress: 0.58
translated_text: buy
backtranslated_text: bumili
Progress: 0.59
translated_text: henyo
backtranslated_text: henyo
Progress: 0.59
translated_text: smart
backtranslated_text: matalino
Progress: 0.59
translated_text: flood
backtranslated_text: baha
Progress: 0.59
translated_text: overflow
backtranslated_text: pag-apaw
Progress: 0.59
translated_text: inspiration
backtranslated_text: inspirasyon
Progress: 0.59
translated_text: sigla
backtranslated_text: sigla
Progress: 0.59
translated_text: bed
backtranslated_text: kama
Progress: 0.59
translated_text: the bible
backtranslated_text: Ang Bibliya
Progress: 0.59
translated_text: annoyed
backtranslated_text: inis
Progress: 0.59
translated_text: pants
backtranslated_text: pantalon
Progress: 0.59
translated_text: dark
backtranslated_text: madilim
Progress: 0.59
translated_text: forgetful
backtranslated_text: nakakalimot
Progress: 0.59
translated_text: forget
backtranslated_text: kalimutan
Progress: 0.59
translated_text: bath
backtranslated_text: paliguan
Progress: 0.59
translated_text: fragrant
backtranslated_text: mabango
Progress: 0.59
translated_text: quiet
backtranslated_text: tahimik
Progress: 0.59
translated_text: taimtim
backtranslated_text: taimtim
Progress: 0.59
translated_text: trash
backtranslated_text: basura
Progress: 0.59
translated_text: cork
backtranslated_text: tapon
Progress: 0.59
translated_text: power
backtranslated_text: kapangyarihan
Progress: 0.59
translated_text: machine
backtranslated_text: makina
Progress: 0.59
translated_text: machinery
backtranslated_text: makinarya
Progress: 0.59
translated_text: damot
backtranslated_text: damot
Progress: 0.59
translated_text: greedy
backtranslated_text: matakaw
Progress: 0.59
translated_text: hayok
backtranslated_text: hayok
Progress: 0.59
translated_text: bride
backtranslated_text: nobya
Progress: 0.60
translated_text: girlfriend
backtranslated_text: kasintahan
Progress: 0.60
translated_text: circumstances
backtranslated_text: mga pangyayari
Progress: 0.60
translated_text: event
backtranslated_text: kaganapan
Progress: 0.60
translated_text: resentment
backtranslated_text: sama ng loob
Progress: 0.60
translated_text: quarrel
backtranslated_text: awayan
Progress: 0.60
translated_text: cheap
backtranslated_text: mura
Progress: 0.60
translated_text: proactive
backtranslated_text: maagap
Progress: 0.60
translated_text: early
backtranslated_text: maaga
Progress: 0.60
translated_text: especially
backtranslated_text: lalo na
Progress: 0.60
translated_text: Handsome
backtranslated_text: Gwapo
Progress: 0.60
translated_text: handsome
backtranslated_text: gwapo
Progress: 0.60
translated_text: ama
backtranslated_text: ama
Progress: 0.60
translated_text: dad
backtranslated_text: tatay
Progress: 0.60
translated_text: has
backtranslated_text: may
Progress: 0.60
translated_text: mother
backtranslated_text: ina
Progress: 0.60
translated_text: sandals
backtranslated_text: sandals
Progress: 0.60
translated_text: Wait
backtranslated_text: Teka
Progress: 0.60
translated_text: saglit
backtranslated_text: saglit
Progress: 0.60
translated_text: stand up
backtranslated_text: tayo
Progress: 0.60
translated_text: rise
backtranslated_text: tumaas
Progress: 0.60
translated_text: bahing
backtranslated_text: bahagig
Progress: 0.60
translated_text: mura
backtranslated_text: mura
Progress: 0.60
translated_text: date
backtranslated_text: petsa
Progress: 0.60
translated_text: day
backtranslated_text: araw
Progress: 0.60
translated_text: breakfast

backtranslated_text: almusal
Progress: 0.60
translated_text: agahan
backtranslated_text: agahan
Progress: 0.61
translated_text: cabinet
backtranslated_text: cabinet
Progress: 0.61
translated_text: cupboard
backtranslated_text: aparador
Progress: 0.61
translated_text: soup
backtranslated_text: sabaw
Progress: 0.61
translated_text: broth
backtranslated_text: sabaw
Progress: 0.61
translated_text: important
backtranslated_text: mahalaga
Progress: 0.61
translated_text: important
backtranslated_text: mahalaga
Progress: 0.61
translated_text: souvenir
backtranslated_text: souvenir
Progress: 0.61
translated_text: gift
backtranslated_text: regalo
Progress: 0.61
translated_text: scissors
backtranslated_text: gunting
Progress: 0.61
translated_text: included
backtranslated_text: kasama
Progress: 0.61
translated_text: kadamay
backtranslated_text: kadamay
Progress: 0.61
translated_text: stop
backtranslated_text: huminto
Progress: 0.61
translated_text: stops
backtranslated_text: huminto
Progress: 0.61
translated_text: corner
backtranslated_text: sulok
Progress: 0.61
translated_text: kanto
backtranslated_text: kanto
Progress: 0.61
translated_text: television
backtranslated_text: telebisyon
Progress: 0.61
translated_text: asikaso
backtranslated_text: asikaso
Progress: 0.61
translated_text: take care
backtranslated_text: ingat
Progress: 0.61
translated_text: free
backtranslated_text: libre
Progress: 0.61
translated_text: Free
backtranslated_text: Libre
Progress: 0.61
translated_text: vacancy
backtranslated_text: bakante
Progress: 0.61
translated_text: sin
backtranslated_text: kasalanan
Progress: 0.61
translated_text: arrears
backtranslated_text: atraso
Progress: 0.61
translated_text: yaya
backtranslated_text: yaya
Progress: 0.61
translated_text: offer
backtranslated_text: alok
Progress: 0.61
translated_text: assistant
backtranslated_text: katulong
Progress: 0.62
translated_text: family
backtranslated_text: pamilya
Progress: 0.62
translated_text: number
backtranslated_text: numero
Progress: 0.62
translated_text: problem
backtranslated_text: problema
Progress: 0.62
translated_text: problem
backtranslated_text: problema
Progress: 0.62
translated_text: lolo
backtranslated_text: lolo
Progress: 0.62
translated_text: grandma
backtranslated_text: lola
Progress: 0.62
translated_text: damage
backtranslated_text: pinsala
Progress: 0.62
translated_text: wait
backtranslated_text: maghintay
Progress: 0.62
translated_text: wait
backtranslated_text: maghintay
Progress: 0.62
translated_text: respect
backtranslated_text: paggalang
Progress: 0.62
translated_text: uncle
backtranslated_text: tiyuhin
Progress: 0.62
translated_text: uncle
backtranslated_text: tiyuhin
Progress: 0.62
translated_text: powder
backtranslated_text: pulbos
Progress: 0.62
translated_text: mascara
backtranslated_text: mascara
Progress: 0.62
translated_text: traitor
backtranslated_text: taksil
Progress: 0.62
translated_text: traitor
backtranslated_text: taksil
Progress: 0.62
translated_text: guest
backtranslated_text: bisita
Progress: 0.62
translated_text: skin
backtranslated_text: balat
Progress: 0.62
translated_text: skin
backtranslated_text: balat
Progress: 0.62
translated_text: presko
backtranslated_text: presko
Progress: 0.62
translated_text: fresh
backtranslated_text: sariwa
Progress: 0.62
translated_text: required
backtranslated_text: kailangan
Progress: 0.62
translated_text: drama
backtranslated_text: drama
Progress: 0.62
translated_text: the sky
backtranslated_text: ang langit
Progress: 0.62
translated_text: lotion
backtranslated_text: losyon
Progress: 0.62
translated_text: left
backtranslated_text: umalis
Progress: 0.63
translated_text: right
backtranslated_text: tama
Progress: 0.63
translated_text: right
backtranslated_text: tama
Progress: 0.63
translated_text: robot
backtranslated_text: robot
Progress: 0.63
translated_text: earthquake
backtranslated_text: lindol
Progress: 0.63
translated_text: tremor
backtranslated_text: panginginig
Progress: 0.63
translated_text: awake
backtranslated_text: gising
Progress: 0.63
translated_text: cracked
backtranslated_text: basag
Progress: 0.63
translated_text: piece
backtranslated_text: piraso
Progress: 0.63
translated_text: floor
backtranslated_text: palapag
Progress: 0.63
translated_text: merchandise
backtranslated_text: paninda
Progress: 0.63
translated_text: flatulence
backtranslated_text: utot
Progress: 0.63
translated_text: fart
backtranslated_text: umutot
Progress: 0.63
translated_text: environment
backtranslated_text: kapaligiran
Progress: 0.63
translated_text: grab
backtranslated_text: sunggaban
Progress: 0.63
translated_text: butterfly
backtranslated_text: paruparo
Progress: 0.63
translated_text: dizzy
backtranslated_text: nahihilo
Progress: 0.63
translated_text: naliliyo
backtranslated_text: naliliyo
Progress: 0.63
translated_text: cheat
backtranslated_text: manloko
Progress: 0.63
translated_text: cheat
backtranslated_text: manloko
Progress: 0.63
translated_text: clear
backtranslated_text: malinaw
Progress: 0.63
translated_text: coat
backtranslated_text: amerikana
Progress: 0.63
translated_text: manta
backtranslated_text: manta
Progress: 0.63
translated_text: a lot
backtranslated_text: marami
Progress: 0.63
translated_text: spear
backtranslated_text: sibat
Progress: 0.63
translated_text: eagle
backtranslated_text: agila
Progress: 0.63
translated_text: talisman
backtranslated_text: anting-anting
Progress: 0.64
translated_text: war
backtranslated_text: digmaan
Progress: 0.64
translated_text: war
backtranslated_text: digmaan
Progress: 0.64
translated_text: resist
backtranslated_text: lumaban
Progress: 0.64
translated_text: belt
backtranslated_text: sinturon
Progress: 0.64
translated_text: hammer
backtranslated_text: martilyo
Progress: 0.64
translated_text: staff
backtranslated_text: mga tauhan
Progress: 0.64
translated_text: cane
backtranslated_text: tungkod
Progress: 0.64
translated_text: gem
backtranslated_text: hiyas
Progress: 0.64
translated_text: guard
backtranslated_text: bantay
Progress: 0.64
translated_text: girl
backtranslated_text: babae
Progress: 0.64
translated_text: virgin
backtranslated_text: Birhen
Progress: 0.64
translated_text: prophet
backtranslated_text: propeta
Progress: 0.64
translated_text: sniper
backtranslated_text: sniper
Progress: 0.64
translated_text: moon
backtranslated_text: buwan
Progress: 0.64
translated_text: smuggling
backtranslated_text: pagpupuslit
Progress: 0.64
translated_text: shadow
backtranslated_text: anino
Progress: 0.64
translated_text: venom
backtranslated_text: lason
Progress: 0.64
translated_text: poison
backtranslated_text: lason
Progress: 0.64
translated_text: puzzle
backtranslated_text: palaisipan
Progress: 0.64
translated_text: forgetfulness
backtranslated_text: pagkalimot
Progress: 0.64
translated_text: ax
backtranslated_text: palakol
Progress: 0.64
translated_text: individual
backtranslated_text: indibidwal
Progress: 0.64
translated_text: alone
backtranslated_text: mag-isa
Progress: 0.64
translated_text: butcher
backtranslated_text: magkakatay ng karne
Progress: 0.64
translated_text: immortal
backtranslated_text: walang kamatayan
Progress: 0.64
translated_text: bonus
backtranslated_text: bonus
Progress: 0.65
translated_text: incentive
backtranslated_text: insentibo
Progress: 0.65
translated_text: goblin
backtranslated_text: duwende
Progress: 0.65
translated_text: duwende
backtranslated_text: duwende
Progress: 0.65
translated_text: magma
backtranslated_text: magma
Progress: 0.65
translated_text: respected
backtranslated_text: iginagalang
Progress: 0.65
translated_text: respected
backtranslated_text: iginagalang
Progress: 0.65
translated_text: sand
backtranslated_text: buhangin
Progress: 0.65
translated_text: North West
backtranslated_text: Hilagang kanluran
Progress: 0.65
translated_text: North East
backtranslated_text: Hilagang Silangan
Progress: 0.65
translated_text: South East
backtranslated_text: Timog Silangan
Progress: 0.65
translated_text: South West
backtranslated_text: Timog Kanluran
Progress: 0.65
translated_text: south
backtranslated_text: Timog
Progress: 0.65
translated_text: see
backtranslated_text: tingnan mo
Progress: 0.65
translated_text: pinatubo
backtranslated_text: pinatubo
Progress: 0.65
translated_text: yellow

backtranslated_text: dilaw
Progress: 0.65
translated_text: xavier
backtranslated_text: xavier
Progress: 0.65
translated_text: xian
backtranslated_text: si xian
Progress: 0.65
translated_text: xy
backtranslated_text: xy
Progress: 0.65
translated_text: existence
backtranslated_text: pag-iral
Progress: 0.65
translated_text: stick
backtranslated_text: patpat
Progress: 0.65
translated_text: put
backtranslated_text: ilagay
Progress: 0.65
translated_text: connect
backtranslated_text: kumonekta
Progress: 0.65
translated_text: include
backtranslated_text: isama
Progress: 0.65
translated_text: daredevil
backtranslated_text: pangahas
Progress: 0.65
translated_text: driver
backtranslated_text: driver
Progress: 0.65
translated_text: driver
backtranslated_text: driver
Progress: 0.66
translated_text: kutsero
backtranslated_text: kutsero
Progress: 0.66
translated_text: endurance
backtranslated_text: pagtitiis
Progress: 0.66
translated_text: restraint
backtranslated_text: pagpigil
Progress: 0.66
translated_text: baraha
backtranslated_text: baraha
Progress: 0.66
translated_text: bareta
backtranslated_text: bareta
Progress: 0.66
translated_text: bubbles
backtranslated_text: mga bula
Progress: 0.66
translated_text: cabinet
backtranslated_text: cabinet
Progress: 0.66
translated_text: cutlery
backtranslated_text: kubyertos
Progress: 0.66
translated_text: cross
backtranslated_text: krus
Progress: 0.66
translated_text: antanda
backtranslated_text: antanda
Progress: 0.66
translated_text: market
backtranslated_text: merkado
Progress: 0.66
translated_text: the market
backtranslated_text: ang palengke
Progress: 0.66
translated_text: market
backtranslated_text: merkado
Progress: 0.66
translated_text: market
backtranslated_text: merkado
Progress: 0.66
translated_text: store
backtranslated_text: tindahan
Progress: 0.66
translated_text: fireworks
backtranslated_text: paputok
Progress: 0.66
translated_text: libraries
backtranslated_text: mga aklatan
Progress: 0.66
translated_text: exercise
backtranslated_text: ehersisyo
Progress: 0.66
translated_text: training
backtranslated_text: pagsasanay
Progress: 0.66
translated_text: mesa
backtranslated_text: mesa
Progress: 0.66
translated_text: lamesa
backtranslated_text: lamesa
Progress: 0.66
translated_text: tray
backtranslated_text: tray
Progress: 0.66
translated_text: table
backtranslated_text: mesa
Progress: 0.66
translated_text: dining tables
backtranslated_text: mga hapag kainan
Progress: 0.66
translated_text: kinse
backtranslated_text: kinse
Progress: 0.66
translated_text: tunnel
backtranslated_text: lagusan
Progress: 0.67
translated_text: navel
backtranslated_text: pusod
Progress: 0.67
translated_text: bet
backtranslated_text: taya
Progress: 0.67
translated_text: artist
backtranslated_text: artista
Progress: 0.67
translated_text: actress
backtranslated_text: artista
Progress: 0.67
translated_text: bulbol
backtranslated_text: bulbol
Progress: 0.67
translated_text: hintuturo
backtranslated_text: hintuturo
Progress: 0.67
translated_text: flour
backtranslated_text: harina
Progress: 0.67
translated_text: drunk
backtranslated_text: lasing
Progress: 0.67
translated_text: fourth
backtranslated_text: pang-apat
Progress: 0.67
translated_text: sixth
backtranslated_text: pang-anim
Progress: 0.67
translated_text: ninth
backtranslated_text: ikasiyam
Progress: 0.67
translated_text: hood
backtranslated_text: hood
Progress: 0.67
translated_text: exhaust
backtranslated_text: tambutso
Progress: 0.67
translated_text: siping
backtranslated_text: humihigop
Progress: 0.67
translated_text: passion
backtranslated_text: pagsinta
Progress: 0.67
translated_text: love
backtranslated_text: pag-ibig
Progress: 0.67
translated_text: love
backtranslated_text: pag-ibig
Progress: 0.67
translated_text: view
backtranslated_text: tingnan
Progress: 0.67
translated_text: giliw
backtranslated_text: giliw
Progress: 0.67
translated_text: sinisinta
backtranslated_text: sinisinta
Progress: 0.67
translated_text: irog
backtranslated_text: irog
Progress: 0.67
translated_text: nothing
backtranslated_text: wala
Progress: 0.67
translated_text: bokya
backtranslated_text: bokya
Progress: 0.67
translated_text: love
backtranslated_text: pag-ibig
Progress: 0.67
translated_text: love
backtranslated_text: pag-ibig
Progress: 0.67
translated_text: have fun
backtranslated_text: magsaya ka
Progress: 0.68
translated_text: have fun
backtranslated_text: magsaya ka
Progress: 0.68
translated_text: excited
backtranslated_text: nasasabik
Progress: 0.68
translated_text: like
backtranslated_text: gaya ng
Progress: 0.68
translated_text: lust
backtranslated_text: pagnanasa
Progress: 0.68
translated_text: lust
backtranslated_text: pagnanasa
Progress: 0.68
translated_text: likes
backtranslated_text: gusto
Progress: 0.68
translated_text: angry
backtranslated_text: galit
Progress: 0.68
translated_text: hate
backtranslated_text: poot
Progress: 0.68
translated_text: heat
backtranslated_text: init
Progress: 0.68
translated_text: get angry
backtranslated_text: magalit
Progress: 0.68
translated_text: get angry
backtranslated_text: magalit
Progress: 0.68
translated_text: reprimand
backtranslated_text: pasaway
Progress: 0.68
translated_text: greed
backtranslated_text: kasakiman
Progress: 0.68
translated_text: envy
backtranslated_text: inggit
Progress: 0.68
translated_text: envy
backtranslated_text: inggit
Progress: 0.68
translated_text: yabang
backtranslated_text: yabang
Progress: 0.68
translated_text: pure
backtranslated_text: dalisay
Progress: 0.68
translated_text: Dignity
backtranslated_text: dangal
Progress: 0.68
translated_text: brag
backtranslated_text: magyabang
Progress: 0.68
translated_text: brag
backtranslated_text: magyabang
Progress: 0.68
translated_text: featured
backtranslated_text: Itinatampok
Progress: 0.68
translated_text: be proud
backtranslated_text: ipagmalaki mo
Progress: 0.68
translated_text: flag
backtranslated_text: bandila
Progress: 0.68
translated_text: flags
backtranslated_text: mga watawat
Progress: 0.68
translated_text: flag
backtranslated_text: bandila
Progress: 0.68
translated_text: soft
backtranslated_text: malambot
Progress: 0.69
translated_text: enough
backtranslated_text: tama na
Progress: 0.69
translated_text: abundant
backtranslated_text: sagana
Progress: 0.69
translated_text: easy
backtranslated_text: madali
Progress: 0.69
translated_text: very difficult
backtranslated_text: napakahirap
Progress: 0.69
translated_text: tiring
backtranslated_text: nakakapagod
Progress: 0.69
translated_text: exhausting
backtranslated_text: nakakapagod
Progress: 0.69
translated_text: heavy
backtranslated_text: mabigat
Progress: 0.69
translated_text: laborious
backtranslated_text: matrabaho
Progress: 0.69
translated_text: tamis
backtranslated_text: tamis
Progress: 0.69
translated_text: taste
backtranslated_text: panlasa
Progress: 0.69
translated_text: savor
backtranslated_text: sarap
Progress: 0.69
translated_text: see
backtranslated_text: tingnan mo
Progress: 0.69
translated_text: number
backtranslated_text: numero
Progress: 0.69
translated_text: call
backtranslated_text: tawag
Progress: 0.69
translated_text: livelihood
backtranslated_text: kabuhayan
Progress: 0.69
translated_text: scare
backtranslated_text: takutin
Progress: 0.69
translated_text: flies
backtranslated_text: langaw
Progress: 0.69
translated_text: mad
backtranslated_text: galit
Progress: 0.69
translated_text: tanga
backtranslated_text: tanga
Progress: 0.69
translated_text: stupid
backtranslated_text: bobo
Progress: 0.69
translated_text: minutes
backtranslated_text: minuto
Progress: 0.69
translated_text: time
backtranslated_text: oras
Progress: 0.69
translated_text: munti
backtranslated_text: munti
Progress: 0.69
translated_text: very little
backtranslated_text: napaka konti
Progress: 0.69
translated_text: second
backtranslated_text: pangalawa
Progress: 0.69
translated_text: occasion
backtranslated_text: okasyon
Progress: 0.70
translated_text: back off
backtranslated_text: lumayo ka
Progress: 0.70
translated_text: hamburger
backtranslated_text: hamburger
Progress: 0.70
translated_text: burger
backtranslated_text: burger
Progress: 0.70
translated_text: muscular
backtranslated_text: matipuno
Progress: 0.70
translated_text: garapata

backtranslated_text: garapata
Progress: 0.70
translated_text: doge
backtranslated_text: doge
Progress: 0.70
translated_text: doggy
backtranslated_text: aso
Progress: 0.70
translated_text: doggie
backtranslated_text: aso
Progress: 0.70
translated_text: lost
backtranslated_text: nawala
Progress: 0.70
translated_text: dogie
backtranslated_text: dogie
Progress: 0.70
translated_text: doctrine
backtranslated_text: doktrina
Progress: 0.70
translated_text: slave
backtranslated_text: alipin
Progress: 0.70
translated_text: nonsense
backtranslated_text: kalokohan
Progress: 0.70
translated_text: einstein
backtranslated_text: einstein
Progress: 0.70
translated_text: newton
backtranslated_text: newton
Progress: 0.70
translated_text: darwin
backtranslated_text: si darwin
Progress: 0.70
translated_text: maxwell
backtranslated_text: maxwell
Progress: 0.70
translated_text: mx
backtranslated_text: mx
Progress: 0.70
translated_text: ci
backtranslated_text: ci
Progress: 0.70
translated_text: tesla
backtranslated_text: tesla
Progress: 0.70
translated_text: nobel
backtranslated_text: nobela
Progress: 0.70
translated_text: graham
backtranslated_text: graham
Progress: 0.70
translated_text: bernard
backtranslated_text: bernard
Progress: 0.70
translated_text: born
backtranslated_text: ipinanganak
Progress: 0.70
translated_text: harvey
backtranslated_text: harvey
Progress: 0.70
translated_text: watson
backtranslated_text: watson
Progress: 0.71
translated_text: bethe
backtranslated_text: maging ang
Progress: 0.71
translated_text: lorenz
backtranslated_text: si lorenz
Progress: 0.71
translated_text: teller
backtranslated_text: teller
Progress: 0.71
translated_text: jenner
backtranslated_text: jenner
Progress: 0.71
translated_text: lister
backtranslated_text: maglista
Progress: 0.71
translated_text: gilbert
backtranslated_text: gilbert
Progress: 0.71
translated_text: gi
backtranslated_text: gi
Progress: 0.71
translated_text: bacon
backtranslated_text: bacon
Progress: 0.71
translated_text: black
backtranslated_text: itim
Progress: 0.71
translated_text: turing
backtranslated_text: turing
Progress: 0.71
translated_text: michael
backtranslated_text: michael
Progress: 0.71
translated_text: lee
backtranslated_text: lee
Progress: 0.71
translated_text: amazon
backtranslated_text: amazon
Progress: 0.71
translated_text: cam
backtranslated_text: cam
Progress: 0.71
translated_text: canadian
backtranslated_text: canadian
Progress: 0.71
translated_text: charles
backtranslated_text: charles
Progress: 0.71
translated_text: darling
backtranslated_text: sinta
Progress: 0.71
translated_text: driver
backtranslated_text: driver
Progress: 0.71
translated_text: don
backtranslated_text: don
Progress: 0.71
translated_text: down
backtranslated_text: pababa
Progress: 0.71
translated_text: forth
backtranslated_text: pasulong
Progress: 0.71
translated_text: crazy
backtranslated_text: baliw
Progress: 0.71
translated_text: james
backtranslated_text: james
Progress: 0.71
translated_text: jordan
backtranslated_text: jordan
Progress: 0.71
translated_text: kura
backtranslated_text: kura
Progress: 0.71
translated_text: lena
backtranslated_text: si lena
Progress: 0.72
translated_text: magdalena
backtranslated_text: magdalena
Progress: 0.72
translated_text: mobile
backtranslated_text: mobile
Progress: 0.72
translated_text: nile
backtranslated_text: nile
Progress: 0.72
translated_text: ob
backtranslated_text: ob
Progress: 0.72
translated_text: or
backtranslated_text: o
Progress: 0.72
translated_text: orange
backtranslated_text: kahel
Progress: 0.72
translated_text: own
backtranslated_text: sariling
Progress: 0.72
translated_text: para
backtranslated_text: para
Progress: 0.72
translated_text: ovary
backtranslated_text: obaryo
Progress: 0.72
translated_text: furnace
backtranslated_text: pugon
Progress: 0.72
translated_text: obesity
backtranslated_text: labis na katabaan
Progress: 0.72
translated_text: obligation
backtranslated_text: obligasyon
Progress: 0.72
translated_text: answer
backtranslated_text: sagot
Progress: 0.72
translated_text: duty
backtranslated_text: tungkulin
Progress: 0.72
translated_text: laborer
backtranslated_text: manggagawa
Progress: 0.72
translated_text: observations
backtranslated_text: mga obserbasyon
Progress: 0.72
translated_text: observation
backtranslated_text: pagmamasid
Progress: 0.72
translated_text: rare
backtranslated_text: bihira
Progress: 0.72
translated_text: okra
backtranslated_text: okra
Progress: 0.72
translated_text: procrastination
backtranslated_text: pagpapaliban
Progress: 0.72
translated_text: occupied
backtranslated_text: inookupahan
Progress: 0.72
translated_text: om
backtranslated_text: om
Progress: 0.72
translated_text: omnibus
backtranslated_text: omnibus
Progress: 0.72
translated_text: offensive
backtranslated_text: nakakasakit
Progress: 0.72
translated_text: opera
backtranslated_text: opera
Progress: 0.72
translated_text: offering
backtranslated_text: alay
Progress: 0.73
translated_text: opportunity
backtranslated_text: pagkakataon
Progress: 0.73
translated_text: opportunity
backtranslated_text: pagkakataon
Progress: 0.73
translated_text: opportunist
backtranslated_text: oportunista
Progress: 0.73
translated_text: opposition
backtranslated_text: pagsalungat
Progress: 0.73
translated_text: resistance
backtranslated_text: paglaban
Progress: 0.73
translated_text: outs
backtranslated_text: paglabas
Progress: 0.73
translated_text: resistance
backtranslated_text: paglaban
Progress: 0.73
translated_text: resistance
backtranslated_text: paglaban
Progress: 0.73
translated_text: opponent
backtranslated_text: kalaban
Progress: 0.73
translated_text: competitor
backtranslated_text: katunggali
Progress: 0.73
translated_text: oral
backtranslated_text: pasalita
Progress: 0.73
translated_text: orbit
backtranslated_text: orbit
Progress: 0.73
translated_text: ordinance
backtranslated_text: ordinansa
Progress: 0.73
translated_text: order
backtranslated_text: utos
Progress: 0.73
translated_text: ordinary
backtranslated_text: karaniwan
Progress: 0.73
translated_text: organized
backtranslated_text: organisado
Progress: 0.73
translated_text: organizer
backtranslated_text: organizer
Progress: 0.73
translated_text: organization
backtranslated_text: organisasyon
Progress: 0.73
translated_text: organization
backtranslated_text: organisasyon
Progress: 0.73
translated_text: original
backtranslated_text: orihinal
Progress: 0.73
translated_text: hospital
backtranslated_text: ospital
Progress: 0.73
translated_text: hospitalized
backtranslated_text: naospital
Progress: 0.73
translated_text: rabies
backtranslated_text: rabies
Progress: 0.73
translated_text: madness
backtranslated_text: kabaliwan
Progress: 0.73
translated_text: radar
backtranslated_text: radar
Progress: 0.73
translated_text: radical
backtranslated_text: radikal
Progress: 0.74
translated_text: charm
backtranslated_text: alindog
Progress: 0.74
translated_text: racket
backtranslated_text: raketa
Progress: 0.74
translated_text: racket
backtranslated_text: raketa
Progress: 0.74
translated_text: rank
backtranslated_text: ranggo
Progress: 0.74
translated_text: status
backtranslated_text: katayuan
Progress: 0.74
translated_text: ration
backtranslated_text: rasyon
Progress: 0.74
translated_text: reaction
backtranslated_text: reaksyon
Progress: 0.74
translated_text: reality
backtranslated_text: katotohanan
Progress: 0.74
translated_text: revelation
backtranslated_text: paghahayag
Progress: 0.74
translated_text: rebelde
backtranslated_text: rebelde
Progress: 0.74
translated_text: rebellion
backtranslated_text: paghihimagsik
Progress: 0.74
translated_text: revolution
backtranslated_text: rebolusyon
Progress: 0.74
translated_text: rebellion
backtranslated_text: paghihimagsik
Progress: 0.74
translated_text: revolutionary
backtranslated_text: rebolusyonaryo
Progress: 0.74
translated_text: rebyu
backtranslated_text: rebyu
Progress: 0.74
translated_text: change
backtranslated_text: pagbabago
Progress: 0.74
translated_text: regulation
backtranslated_text: regulasyon
Progress: 0.74
translated_text: rehabilitation
backtranslated_text: rehabilitasyon
Progress: 0.74
translated_text: registered
backtranslated_text: nakarehistro
Progress: 0.74
translated_text: register

backtranslated_text: magparehistro
Progress: 0.74
translated_text: register
backtranslated_text: magparehistro
Progress: 0.74
translated_text: region
backtranslated_text: rehiyon
Progress: 0.74
translated_text: rekado
backtranslated_text: rekado
Progress: 0.74
translated_text: ingredient
backtranslated_text: sangkap
Progress: 0.74
translated_text: advertisement
backtranslated_text: patalastas
Progress: 0.74
translated_text: recommendation
backtranslated_text: rekomendasyon
Progress: 0.75
translated_text: instructions
backtranslated_text: mga tagubilin
Progress: 0.75
translated_text: congratulations
backtranslated_text: binabati kita
Progress: 0.75
translated_text: record
backtranslated_text: rekord
Progress: 0.75
translated_text: relationship
backtranslated_text: relasyon
Progress: 0.75
translated_text: connection
backtranslated_text: koneksyon
Progress: 0.75
translated_text: religion
backtranslated_text: relihiyon
Progress: 0.75
translated_text: remedies
backtranslated_text: mga remedyo
Progress: 0.75
translated_text: cabbage
backtranslated_text: repolyo
Progress: 0.75
translated_text: reform
backtranslated_text: reporma
Progress: 0.75
translated_text: reporter
backtranslated_text: reporter
Progress: 0.75
translated_text: representation
backtranslated_text: representasyon
Progress: 0.75
translated_text: republic
backtranslated_text: republika
Progress: 0.75
translated_text: reserve
backtranslated_text: reserba
Progress: 0.75
translated_text: reseta
backtranslated_text: i-reseta
Progress: 0.75
translated_text: receipt
backtranslated_text: resibo
Progress: 0.75
translated_text: resolution
backtranslated_text: resolusyon
Progress: 0.75
translated_text: proposal
backtranslated_text: panukala
Progress: 0.75
translated_text: missing
backtranslated_text: nawawala
Progress: 0.75
translated_text: lito
backtranslated_text: lito
Progress: 0.75
translated_text: pitiful
backtranslated_text: nakakaawa
Progress: 0.75
translated_text: feeling
backtranslated_text: pakiramdam
Progress: 0.75
translated_text: diwa
backtranslated_text: diwa
Progress: 0.75
translated_text: spirit
backtranslated_text: espiritu
Progress: 0.75
translated_text: asphalt
backtranslated_text: aspalto
Progress: 0.75
translated_text: cause
backtranslated_text: dahilan
Progress: 0.75
translated_text: bear fruit
backtranslated_text: magbunga
Progress: 0.76
translated_text: huli
backtranslated_text: huli
Progress: 0.76
translated_text: thin
backtranslated_text: manipis
Progress: 0.76
translated_text: fatten
backtranslated_text: magpataba
Progress: 0.76
translated_text: fat
backtranslated_text: mataba
Progress: 0.76
translated_text: full
backtranslated_text: puno na
Progress: 0.76
translated_text: stairs
backtranslated_text: hagdan
Progress: 0.76
translated_text: stairs
backtranslated_text: hagdan
Progress: 0.76
translated_text: heart
backtranslated_text: puso
Progress: 0.76
translated_text: snacks
backtranslated_text: meryenda
Progress: 0.76
translated_text: chair
backtranslated_text: upuan
Progress: 0.76
translated_text: rain
backtranslated_text: ulan
Progress: 0.76
translated_text: idol
backtranslated_text: idol
Progress: 0.76
translated_text: sir
backtranslated_text: sir
Progress: 0.76
translated_text: binibini
backtranslated_text: binibini
Progress: 0.76
translated_text: sablay
backtranslated_text: sablay
Progress: 0.76
translated_text: palya
backtranslated_text: palya
Progress: 0.76
translated_text: madam
backtranslated_text: ginang
Progress: 0.76
translated_text: save
backtranslated_text: iligtas
Progress: 0.76
translated_text: gather
backtranslated_text: magtipon
Progress: 0.76
translated_text: write
backtranslated_text: magsulat
Progress: 0.76
translated_text: hide
backtranslated_text: tago
Progress: 0.76
translated_text: cover up
backtranslated_text: takpan
Progress: 0.76
translated_text: keep secret
backtranslated_text: maglihim
Progress: 0.76
translated_text: march
backtranslated_text: martsa
Progress: 0.76
translated_text: sketch
backtranslated_text: sketch
Progress: 0.76
translated_text: hanap
backtranslated_text: hanap
Progress: 0.77
translated_text: relative
backtranslated_text: kamag-anak
Progress: 0.77
translated_text: dilim
backtranslated_text: dilim
Progress: 0.77
translated_text: night
backtranslated_text: gabi
Progress: 0.77
translated_text: knife
backtranslated_text: kutsilyo
Progress: 0.77
translated_text: butterfly knife
backtranslated_text: butterfly kutsilyo
Progress: 0.77
translated_text: stab
backtranslated_text: saksakin
Progress: 0.77
translated_text: slice
backtranslated_text: hiwain
Progress: 0.77
translated_text: definition
backtranslated_text: kahulugan
Progress: 0.77
translated_text: child
backtranslated_text: bata
Progress: 0.77
translated_text: life
backtranslated_text: buhay
Progress: 0.77
translated_text: hanger
backtranslated_text: sabitan
Progress: 0.77
translated_text: translate
backtranslated_text: Isalin
Progress: 0.77
translated_text: wife
backtranslated_text: asawa
Progress: 0.77
translated_text: pedestal
backtranslated_text: pedestal
Progress: 0.77
translated_text: joint
backtranslated_text: magkadugtong
Progress: 0.77
translated_text: bigay
backtranslated_text: bigay
Progress: 0.77
translated_text: gift
backtranslated_text: regalo
Progress: 0.77
translated_text: close
backtranslated_text: malapit na
Progress: 0.77
translated_text: itching
backtranslated_text: nangangati
Progress: 0.77
translated_text: scratch
backtranslated_text: scratch
Progress: 0.77
translated_text: glasses
backtranslated_text: baso
Progress: 0.77
translated_text: get
backtranslated_text: makuha
Progress: 0.77
translated_text: find out
backtranslated_text: malaman
Progress: 0.77
translated_text: learn
backtranslated_text: matuto
Progress: 0.77
translated_text: fun
backtranslated_text: masaya
Progress: 0.77
translated_text: agreement
backtranslated_text: kasunduan
Progress: 0.78
translated_text: train
backtranslated_text: tren
Progress: 0.78
translated_text: practice
backtranslated_text: pagsasanay
Progress: 0.78
translated_text: hide
backtranslated_text: tago
Progress: 0.78
translated_text: issue
backtranslated_text: isyu
Progress: 0.78
translated_text: as
backtranslated_text: bilang
Progress: 0.78
translated_text: rent
backtranslated_text: upa
Progress: 0.78
translated_text: sentence
backtranslated_text: pangungusap
Progress: 0.78
translated_text: hum
backtranslated_text: ugong
Progress: 0.78
translated_text: bomb
backtranslated_text: bomba
Progress: 0.78
translated_text: root
backtranslated_text: ugat
Progress: 0.78
translated_text: buklatin
backtranslated_text: buklatin
Progress: 0.78
translated_text: swag
backtranslated_text: swag
Progress: 0.78
translated_text: crore
backtranslated_text: crore
Progress: 0.78
translated_text: malik
backtranslated_text: malik
Progress: 0.78
translated_text: poet
backtranslated_text: makata
Progress: 0.78
translated_text: ward
backtranslated_text: ward
Progress: 0.78
translated_text: burns
backtranslated_text: nasusunog
Progress: 0.78
translated_text: dean
backtranslated_text: dean
Progress: 0.78
translated_text: fry
backtranslated_text: magprito
Progress: 0.78
translated_text: abu
backtranslated_text: abu
Progress: 0.78
translated_text: ping
backtranslated_text: ping
Progress: 0.78
translated_text: po
backtranslated_text: po
Progress: 0.78
translated_text: red
backtranslated_text: pula
Progress: 0.78
translated_text: saale
backtranslated_text: saale
Progress: 0.78
translated_text: salmon
backtranslated_text: salmon
Progress: 0.78
translated_text: screwdriver
backtranslated_text: distornilyador
Progress: 0.79
translated_text: snake
backtranslated_text: ahas
Progress: 0.79
translated_text: avon
backtranslated_text: avon
Progress: 0.79
translated_text: white
backtranslated_text: puti
Progress: 0.79
translated_text: hell
backtranslated_text: impyerno
Progress: 0.79
translated_text: mess
backtranslated_text: gulo
Progress: 0.79
translated_text: protest
backtranslated_text: protesta
Progress: 0.79
translated_text: list
backtranslated_text: listahan
Progress: 0.79
translated_text: take note
backtranslated_text: Tandaan
Progress: 0.79
translated_text: write
backtranslated_text: magsulat
Progress: 0.79
translated_text: write
backtranslated_text: magsulat

Progress: 0.79
translated_text: row
backtranslated_text: hilera
Progress: 0.79
translated_text: umbrella
backtranslated_text: payong
Progress: 0.79
translated_text: confused
backtranslated_text: nalilito
Progress: 0.79
translated_text: riles
backtranslated_text: riles
Progress: 0.79
translated_text: tail
backtranslated_text: buntot
Progress: 0.79
translated_text: from
backtranslated_text: mula sa
Progress: 0.79
translated_text: asa
backtranslated_text: bilang isang
Progress: 0.79
translated_text: dynamite
backtranslated_text: dinamita
Progress: 0.79
translated_text: volcano
backtranslated_text: bulkan
Progress: 0.79
translated_text: abo
backtranslated_text: abo
Progress: 0.79
translated_text: dam
backtranslated_text: dam
Progress: 0.79
translated_text: dike
backtranslated_text: dike
Progress: 0.79
translated_text: works
backtranslated_text: gumagana
Progress: 0.79
translated_text: functioning
backtranslated_text: gumagana
Progress: 0.79
translated_text: sea
backtranslated_text: dagat
Progress: 0.79
translated_text: ocean
backtranslated_text: karagatan
Progress: 0.80
translated_text: color
backtranslated_text: kulay
Progress: 0.80
translated_text: salty
backtranslated_text: maalat
Progress: 0.80
translated_text: tool
backtranslated_text: kasangkapan
Progress: 0.80
translated_text: like
backtranslated_text: gaya ng
Progress: 0.80
translated_text: parade
backtranslated_text: parada
Progress: 0.80
translated_text: bureau
backtranslated_text: bureau
Progress: 0.80
translated_text: captive
backtranslated_text: bihag
Progress: 0.80
translated_text: halakhakan
backtranslated_text: halakhakan
Progress: 0.80
translated_text: tears
backtranslated_text: luha
Progress: 0.80
translated_text: wipe
backtranslated_text: punasan
Progress: 0.80
translated_text: fan
backtranslated_text: tagahanga
Progress: 0.80
translated_text: wounded
backtranslated_text: nasugatan
Progress: 0.80
translated_text: whip
backtranslated_text: latigo
Progress: 0.80
translated_text: male
backtranslated_text: lalaki
Progress: 0.80
translated_text: male
backtranslated_text: lalaki
Progress: 0.80
translated_text: punch
backtranslated_text: suntok
Progress: 0.80
translated_text: sapakin
backtranslated_text: sapakin
Progress: 0.80
translated_text: kite
backtranslated_text: saranggola
Progress: 0.80
translated_text: lens
backtranslated_text: lente
Progress: 0.80
translated_text: cup
backtranslated_text: tasa
Progress: 0.80
translated_text: toys
backtranslated_text: mga laruan
Progress: 0.80
translated_text: heroes
backtranslated_text: mga bayani
Progress: 0.80
translated_text: cold
backtranslated_text: malamig
Progress: 0.80
translated_text: ink
backtranslated_text: tinta
Progress: 0.80
translated_text: lapis
backtranslated_text: lapis
Progress: 0.80
translated_text: pondo
backtranslated_text: pondo
Progress: 0.81
translated_text: pondohan
backtranslated_text: pondohan
Progress: 0.81
translated_text: greedy
backtranslated_text: matakaw
Progress: 0.81
translated_text: steal
backtranslated_text: magnakaw
Progress: 0.81
translated_text: process
backtranslated_text: proseso
Progress: 0.81
translated_text: dampi
backtranslated_text: dampi
Progress: 0.81
translated_text: tapik
backtranslated_text: tapik
Progress: 0.81
translated_text: notice
backtranslated_text: pansinin
Progress: 0.81
translated_text: ancient
backtranslated_text: sinaunang
Progress: 0.81
translated_text: copy
backtranslated_text: kopya
Progress: 0.81
translated_text: copy
backtranslated_text: kopya
Progress: 0.81
translated_text: stand
backtranslated_text: tumayo
Progress: 0.81
translated_text: seat
backtranslated_text: upuan
Progress: 0.81
translated_text: doctor
backtranslated_text: doktor
Progress: 0.81
translated_text: bolero
backtranslated_text: bolero
Progress: 0.81
translated_text: boil
backtranslated_text: pakuluan
Progress: 0.81
translated_text: kulo
backtranslated_text: kulo
Progress: 0.81
translated_text: kutsara
backtranslated_text: kutsara
Progress: 0.81
translated_text: body
backtranslated_text: katawan
Progress: 0.81
translated_text: enemy
backtranslated_text: kaaway
Progress: 0.81
translated_text: anger
backtranslated_text: galit
Progress: 0.81
translated_text: eat
backtranslated_text: kumain
Progress: 0.81
translated_text: broom
backtranslated_text: walis
Progress: 0.81
translated_text: buck
backtranslated_text: buck
Progress: 0.81
translated_text: baraka
backtranslated_text: baraka
Progress: 0.81
translated_text: baldwin
backtranslated_text: baldwin
Progress: 0.81
translated_text: anderson
backtranslated_text: anderson
Progress: 0.82
translated_text: coward
backtranslated_text: duwag
Progress: 0.82
translated_text: miller
backtranslated_text: tagagiling
Progress: 0.82
translated_text: rice
backtranslated_text: kanin
Progress: 0.82
translated_text: shaw
backtranslated_text: shaw
Progress: 0.82
translated_text: simon
backtranslated_text: simon
Progress: 0.82
translated_text: vega
backtranslated_text: vega
Progress: 0.82
translated_text: lamb
backtranslated_text: tupa
Progress: 0.82
translated_text: guest
backtranslated_text: bisita
Progress: 0.82
translated_text: seaman
backtranslated_text: seaman
Progress: 0.82
translated_text: stanley
backtranslated_text: stanley
Progress: 0.82
translated_text: stone
backtranslated_text: bato
Progress: 0.82
translated_text: we
backtranslated_text: tayo
Progress: 0.82
translated_text: mars
backtranslated_text: mars
Progress: 0.82
translated_text: night
backtranslated_text: gabi
Progress: 0.82
translated_text: juno
backtranslated_text: juno
Progress: 0.82
translated_text: dis
backtranslated_text: dis
Progress: 0.82
translated_text: luna
backtranslated_text: luna
Progress: 0.82
translated_text: aurora
backtranslated_text: aurora
Progress: 0.82
translated_text: ops
backtranslated_text: ops
Progress: 0.82
translated_text: weird
backtranslated_text: kakaiba
Progress: 0.82
translated_text: crawford
backtranslated_text: crawford
Progress: 0.82
translated_text: french
backtranslated_text: pranses
Progress: 0.82
translated_text: lin
backtranslated_text: lin
Progress: 0.82
translated_text: smith
backtranslated_text: smith
Progress: 0.82
translated_text: taft
backtranslated_text: taft
Progress: 0.82
translated_text: allen
backtranslated_text: allen
Progress: 0.83
translated_text: bogart
backtranslated_text: bogart
Progress: 0.83
translated_text: booth
backtranslated_text: booth
Progress: 0.83
translated_text: drew
backtranslated_text: gumuhit
Progress: 0.83
translated_text: grant
backtranslated_text: bigyan
Progress: 0.83
translated_text: kean
backtranslated_text: kean
Progress: 0.83
translated_text: kelly
backtranslated_text: kelly
Progress: 0.83
translated_text: lloyd
backtranslated_text: lloyd
Progress: 0.83
translated_text: marsh
backtranslated_text: latian
Progress: 0.83
translated_text: mailer
backtranslated_text: mailer
Progress: 0.83
translated_text: lewis
backtranslated_text: lewis
Progress: 0.83
translated_text: joyce
backtranslated_text: joyce
Progress: 0.83
translated_text: jong
backtranslated_text: jong
Progress: 0.83
translated_text: johnson
backtranslated_text: si johnson
Progress: 0.83
translated_text: hunt
backtranslated_text: manghuli
Progress: 0.83
translated_text: holmes
backtranslated_text: holmes
Progress: 0.83
translated_text: hall
backtranslated_text: bulwagan
Progress: 0.83
translated_text: hale
backtranslated_text: hale
Progress: 0.83
translated_text: haggard
backtranslated_text: haggard
Progress: 0.83
translated_text: gray
backtranslated_text: kulay-abo
Progress: 0.83
translated_text: grass
backtranslated_text: damo
Progress: 0.83
translated_text: gogol
backtranslated_text: gogol
Progress: 0.83
translated_text: france
backtranslated_text: France
Progress: 0.83
translated_text: ford
backtranslated_text: ford
Progress: 0.83
translated_text: day
backtranslated_text: araw
Progress: 0.83
translated_text: butler
backtranslated_text: mayordomo
Progress: 0.83
translated_text: woman
backtranslated_text: babae
Progress: 0.84
translated_text: morse
backtranslated_text: morse
Progress: 0.84
translated_text: tobey
backtranslated_text: tobey
Progress: 0.84
translated_text: turner
backtranslated_text: turner
Progress: 0.84
translated_text: wb
backtranslated_text: wb
Progress: 0.84
translated_text: west

backtranslated_text: kanluran
Progress: 0.84
translated_text: wood
backtranslated_text: kahoy
Progress: 0.84
translated_text: rivera
backtranslated_text: rivera
Progress: 0.84
translated_text: homer
backtranslated_text: homer
Progress: 0.84
translated_text: kent
backtranslated_text: kent
Progress: 0.84
translated_text: klee
backtranslated_text: klee
Progress: 0.84
translated_text: constable
backtranslated_text: constable
Progress: 0.84
translated_text: david
backtranslated_text: david
Progress: 0.84
translated_text: davis
backtranslated_text: davis
Progress: 0.84
translated_text: goya
backtranslated_text: goya
Progress: 0.84
translated_text: avatar
backtranslated_text: avatar
Progress: 0.84
translated_text: embodiment
backtranslated_text: sagisag
Progress: 0.84
translated_text: krishna
backtranslated_text: krishna
Progress: 0.84
translated_text: rama
backtranslated_text: rama
Progress: 0.84
translated_text: pentagon
backtranslated_text: pentagon
Progress: 0.84
translated_text: basilica
backtranslated_text: basilica
Progress: 0.84
translated_text: exec
backtranslated_text: exec
Progress: 0.84
translated_text: slaughterhouse
backtranslated_text: bahay-katayan
Progress: 0.84
translated_text: marshall
backtranslated_text: marshall
Progress: 0.84
translated_text: warren
backtranslated_text: Warren
Progress: 0.84
translated_text: walker
backtranslated_text: lalakad
Progress: 0.84
translated_text: sue
backtranslated_text: magdemanda
Progress: 0.85
translated_text: stephen
backtranslated_text: si stephen
Progress: 0.85
translated_text: spark
backtranslated_text: kislap
Progress: 0.85
translated_text: snow
backtranslated_text: niyebe
Progress: 0.85
translated_text: singer
backtranslated_text: mang-aawit
Progress: 0.85
translated_text: service
backtranslated_text: serbisyo
Progress: 0.85
translated_text: scott
backtranslated_text: scott
Progress: 0.85
translated_text: sand
backtranslated_text: buhangin
Progress: 0.85
translated_text: post
backtranslated_text: post
Progress: 0.85
translated_text: percy
backtranslated_text: percy
Progress: 0.85
translated_text: parker
backtranslated_text: parker
Progress: 0.85
translated_text: nash
backtranslated_text: nash
Progress: 0.85
translated_text: saki
backtranslated_text: saki
Progress: 0.85
translated_text: milne
backtranslated_text: milne
Progress: 0.85
translated_text: mason
backtranslated_text: mason
Progress: 0.85
translated_text: sellers
backtranslated_text: mga nagbebenta
Progress: 0.85
translated_text: tracy
backtranslated_text: tracy
Progress: 0.85
translated_text: tree
backtranslated_text: puno
Progress: 0.85
translated_text: wayne
backtranslated_text: wayne
Progress: 0.85
translated_text: ball
backtranslated_text: bola
Progress: 0.85
translated_text: pride
backtranslated_text: pagmamalaki
Progress: 0.85
translated_text: leigh
backtranslated_text: leigh
Progress: 0.85
translated_text: torn
backtranslated_text: napunit
Progress: 0.85
translated_text: torn
backtranslated_text: napunit
Progress: 0.85
translated_text: tear
backtranslated_text: mapunit
Progress: 0.85
translated_text: pig
backtranslated_text: baboy
Progress: 0.85
translated_text: oil
backtranslated_text: langis
Progress: 0.86
translated_text: crude
backtranslated_text: krudo
Progress: 0.86
translated_text: fragrance
backtranslated_text: bango
Progress: 0.86
translated_text: triangle
backtranslated_text: tatsulok
Progress: 0.86
translated_text: construction
backtranslated_text: pagtatayo
Progress: 0.86
translated_text: mother
backtranslated_text: ina
Progress: 0.86
translated_text: nun
backtranslated_text: madre
Progress: 0.86
translated_text: pipi
backtranslated_text: pipi
Progress: 0.86
translated_text: sue
backtranslated_text: magdemanda
Progress: 0.86
translated_text: bakery
backtranslated_text: panaderya
Progress: 0.86
translated_text: tarangkahan
backtranslated_text: tarangkahan
Progress: 0.86
translated_text: troops
backtranslated_text: mga tropa
Progress: 0.86
translated_text: more
backtranslated_text: higit pa
Progress: 0.86
translated_text: birthday
backtranslated_text: kaarawan
Progress: 0.86
translated_text: bid
backtranslated_text: bid
Progress: 0.86
translated_text: forest
backtranslated_text: kagubatan
Progress: 0.86
translated_text: woods
backtranslated_text: gubat
Progress: 0.86
translated_text: war
backtranslated_text: digmaan
Progress: 0.86
translated_text: owner
backtranslated_text: may-ari
Progress: 0.86
translated_text: playful
backtranslated_text: mapaglaro
Progress: 0.86
translated_text: success
backtranslated_text: tagumpay
Progress: 0.86
translated_text: pilot
backtranslated_text: piloto
Progress: 0.86
translated_text: shout
backtranslated_text: sigaw
Progress: 0.86
translated_text: shout
backtranslated_text: sigaw
Progress: 0.86
translated_text: ngawa
backtranslated_text: ngawa
Progress: 0.86
translated_text: shouted
backtranslated_text: sigaw
Progress: 0.86
translated_text: shout
backtranslated_text: sigaw
Progress: 0.87
translated_text: truck
backtranslated_text: trak
Progress: 0.87
translated_text: bayong
backtranslated_text: bayong
Progress: 0.87
translated_text: basket
backtranslated_text: basket
Progress: 0.87
translated_text: coffee
backtranslated_text: kape
Progress: 0.87
translated_text: java
backtranslated_text: java
Progress: 0.87
translated_text: lightning
backtranslated_text: kidlat
Progress: 0.87
translated_text: thunder
backtranslated_text: kulog
Progress: 0.87
translated_text: growl
backtranslated_text: ungol
Progress: 0.87
translated_text: planet
backtranslated_text: planeta
Progress: 0.87
translated_text: ate
backtranslated_text: kumain
Progress: 0.87
translated_text: kuya
backtranslated_text: kuya
Progress: 0.87
translated_text: battery
backtranslated_text: baterya
Progress: 0.87
translated_text: service
backtranslated_text: serbisyo
Progress: 0.87
translated_text: read
backtranslated_text: basahin
Progress: 0.87
translated_text: basa
backtranslated_text: basa
Progress: 0.87
translated_text: rags
backtranslated_text: basahan
Progress: 0.87
translated_text: curtain
backtranslated_text: kurtina
Progress: 0.87
translated_text: curtain
backtranslated_text: kurtina
Progress: 0.87
translated_text: mission
backtranslated_text: misyon
Progress: 0.87
translated_text: president
backtranslated_text: presidente
Progress: 0.87
translated_text: mayor
backtranslated_text: mayor
Progress: 0.87
translated_text: box
backtranslated_text: kahon
Progress: 0.87
translated_text: replace
backtranslated_text: palitan
Progress: 0.87
translated_text: lunch
backtranslated_text: tanghalian
Progress: 0.87
translated_text: dinner
backtranslated_text: hapunan
Progress: 0.87
translated_text: celebration
backtranslated_text: pagdiriwang
Progress: 0.88
translated_text: celebration
backtranslated_text: pagdiriwang
Progress: 0.88
translated_text: acclaim
backtranslated_text: pagbubunyi
Progress: 0.88
translated_text: course
backtranslated_text: kurso
Progress: 0.88
translated_text: military
backtranslated_text: militar
Progress: 0.88
translated_text: captain
backtranslated_text: kapitan
Progress: 0.88
translated_text: cover
backtranslated_text: takip
Progress: 0.88
translated_text: then
backtranslated_text: pagkatapos
Progress: 0.88
translated_text: afterwards
backtranslated_text: pagkatapos
Progress: 0.88
translated_text: afterwards
backtranslated_text: pagkatapos
Progress: 0.88
translated_text: later
backtranslated_text: mamaya
Progress: 0.88
translated_text: palm
backtranslated_text: palad
Progress: 0.88
translated_text: nipa
backtranslated_text: nipa
Progress: 0.88
translated_text: blood
backtranslated_text: dugo
Progress: 0.88
translated_text: bleed
backtranslated_text: dumugo
Progress: 0.88
translated_text: lango
backtranslated_text: lango
Progress: 0.88
translated_text: wine
backtranslated_text: alak
Progress: 0.88
translated_text: necklace
backtranslated_text: kuwintas
Progress: 0.88
translated_text: bottom
backtranslated_text: ibaba
Progress: 0.88
translated_text: banal
backtranslated_text: karaniwan
Progress: 0.88
translated_text: case
backtranslated_text: kaso
Progress: 0.88
translated_text: lawsuit
backtranslated_text: kaso
Progress: 0.88
translated_text: beautiful
backtranslated_text: maganda
Progress: 0.88
translated_text: rugby

backtranslated_text: rugby
Progress: 0.88
translated_text: rugger
backtranslated_text: rugger
Progress: 0.88
translated_text: dams
backtranslated_text: mga dam
Progress: 0.88
translated_text: fever
backtranslated_text: lagnat
Progress: 0.89
translated_text: kuto
backtranslated_text: kuto
Progress: 0.89
translated_text: snoring
backtranslated_text: hilik
Progress: 0.89
translated_text: cracker
backtranslated_text: cracker
Progress: 0.89
translated_text: hacker
backtranslated_text: hacker
Progress: 0.89
translated_text: lineman
backtranslated_text: lineman
Progress: 0.89
translated_text: think
backtranslated_text: isipin mo
Progress: 0.89
translated_text: plot
backtranslated_text: balangkas
Progress: 0.89
translated_text: plan
backtranslated_text: plano
Progress: 0.89
translated_text: complaint
backtranslated_text: reklamo
Progress: 0.89
translated_text: ill
backtranslated_text: may sakit
Progress: 0.89
translated_text: failure
backtranslated_text: kabiguan
Progress: 0.89
translated_text: disturbance
backtranslated_text: kaguluhan
Progress: 0.89
translated_text: astronomer
backtranslated_text: astronomer
Progress: 0.89
translated_text: epidemiologist
backtranslated_text: epidemiologist
Progress: 0.89
translated_text: geologist
backtranslated_text: geologist
Progress: 0.89
translated_text: meteorologist
backtranslated_text: meteorologist
Progress: 0.89
translated_text: philosopher
backtranslated_text: pilosopo
Progress: 0.89
translated_text: economist
backtranslated_text: ekonomista
Progress: 0.89
translated_text: album
backtranslated_text: album
Progress: 0.89
translated_text: novel
backtranslated_text: nobela
Progress: 0.89
translated_text: gospel
backtranslated_text: ebanghelyo
Progress: 0.89
translated_text: lift
backtranslated_text: angat
Progress: 0.89
translated_text: mechanic
backtranslated_text: mekaniko
Progress: 0.89
translated_text: motorist
backtranslated_text: motorista
Progress: 0.89
translated_text: busina
backtranslated_text: busina
Progress: 0.89
translated_text: backseat
backtranslated_text: backseat
Progress: 0.90
translated_text: bumper
backtranslated_text: bumper
Progress: 0.90
translated_text: bus
backtranslated_text: bus
Progress: 0.90
translated_text: compact
backtranslated_text: compact
Progress: 0.90
translated_text: convertible
backtranslated_text: mapapalitan
Progress: 0.90
translated_text: primera
backtranslated_text: primera
Progress: 0.90
translated_text: jeep
backtranslated_text: jeep
Progress: 0.90
translated_text: trunk
backtranslated_text: baul
Progress: 0.90
translated_text: reverse
backtranslated_text: reverse
Progress: 0.90
translated_text: map
backtranslated_text: mapa
Progress: 0.90
translated_text: roof
backtranslated_text: bubong
Progress: 0.90
translated_text: sedan
backtranslated_text: sedan
Progress: 0.90
translated_text: showroom
backtranslated_text: showroom
Progress: 0.90
translated_text: medium
backtranslated_text: daluyan
Progress: 0.90
translated_text: secondhand
backtranslated_text: pangalawang kamay
Progress: 0.90
translated_text: passengers
backtranslated_text: mga pasahero
Progress: 0.90
translated_text: traction
backtranslated_text: traksyon
Progress: 0.90
translated_text: prang
backtranslated_text: prang
Progress: 0.90
translated_text: jinx
backtranslated_text: jinx
Progress: 0.90
translated_text: manna
backtranslated_text: manna
Progress: 0.90
translated_text: ointment
backtranslated_text: pamahid
Progress: 0.90
translated_text: deodorant
backtranslated_text: deodorant
Progress: 0.90
translated_text: powder
backtranslated_text: pulbos
Progress: 0.90
translated_text: noah
backtranslated_text: noah
Progress: 0.90
translated_text: elijah
backtranslated_text: elijah
Progress: 0.90
translated_text: christ
backtranslated_text: Kristo
Progress: 0.90
translated_text: jesus
backtranslated_text: Hesus
Progress: 0.91
translated_text: hesus
backtranslated_text: hesus
Progress: 0.91
translated_text: christ
backtranslated_text: Kristo
Progress: 0.91
translated_text: land
backtranslated_text: lupain
Progress: 0.91
translated_text: otis
backtranslated_text: otis
Progress: 0.91
translated_text: bomber
backtranslated_text: bombero
Progress: 0.91
translated_text: wings
backtranslated_text: mga pakpak
Progress: 0.91
translated_text: log
backtranslated_text: log
Progress: 0.91
translated_text: drift
backtranslated_text: naaanod
Progress: 0.91
translated_text: sales
backtranslated_text: benta
Progress: 0.91
translated_text: tinda
backtranslated_text: tinda
Progress: 0.91
translated_text: lodge
backtranslated_text: tutuluyan
Progress: 0.91
translated_text: ohm
backtranslated_text: ohm
Progress: 0.91
translated_text: milk
backtranslated_text: gatas
Progress: 0.91
translated_text: potion
backtranslated_text: gayuma
Progress: 0.91
translated_text: mixer
backtranslated_text: panghalo
Progress: 0.91
translated_text: cooler
backtranslated_text: palamigan
Progress: 0.91
translated_text: refresher
backtranslated_text: refresher
Progress: 0.91
translated_text: smoothie
backtranslated_text: smoothie
Progress: 0.91
translated_text: cider
backtranslated_text: cider
Progress: 0.91
translated_text: mate
backtranslated_text: kapareha
Progress: 0.91
translated_text: evans
backtranslated_text: evans
Progress: 0.91
translated_text: cartier
backtranslated_text: Cartier
Progress: 0.91
translated_text: cook
backtranslated_text: magluto
Progress: 0.91
translated_text: diaz
backtranslated_text: si diaz
Progress: 0.91
translated_text: dias
backtranslated_text: dias
Progress: 0.91
translated_text: drake
backtranslated_text: si drake
Progress: 0.92
translated_text: acronym
backtranslated_text: acronym
Progress: 0.92
translated_text: aloha
backtranslated_text: aloha
Progress: 0.92
translated_text: ciao
backtranslated_text: ciao
Progress: 0.92
translated_text: blend
backtranslated_text: timpla
Progress: 0.92
translated_text: contrary
backtranslated_text: salungat
Progress: 0.92
translated_text: converse
backtranslated_text: makipag-usap
Progress: 0.92
translated_text: accuracy
backtranslated_text: katumpakan
Progress: 0.92
translated_text: trooper
backtranslated_text: trooper
Progress: 0.92
translated_text: friendly
backtranslated_text: palakaibigan
Progress: 0.92
translated_text: hostile
backtranslated_text: pagalit
Progress: 0.92
translated_text: knight
backtranslated_text: kabalyero
Progress: 0.92
translated_text: soldier
backtranslated_text: sundalo
Progress: 0.92
translated_text: veteran
backtranslated_text: beterano
Progress: 0.92
translated_text: warrior
backtranslated_text: mandirigma
Progress: 0.92
translated_text: blue
backtranslated_text: asul
Progress: 0.92
translated_text: pink
backtranslated_text: kulay rosas
Progress: 0.92
translated_text: lapa
backtranslated_text: lapa
Progress: 0.92
translated_text: liver
backtranslated_text: atay
Progress: 0.92
translated_text: zoology
backtranslated_text: zoology
Progress: 0.92
translated_text: thompson
backtranslated_text: thompson
Progress: 0.92
translated_text: wheeler
backtranslated_text: wheeler
Progress: 0.92
translated_text: ipon
backtranslated_text: ipon
Progress: 0.92
translated_text: economy
backtranslated_text: ekonomiya
Progress: 0.92
translated_text: savings
backtranslated_text: pagtitipid
Progress: 0.92
translated_text: alpha
backtranslated_text: alpha
Progress: 0.92
translated_text: beta
backtranslated_text: beta
Progress: 0.93
translated_text: delta
backtranslated_text: delta
Progress: 0.93
translated_text: and
backtranslated_text: at
Progress: 0.93
translated_text: lambda
backtranslated_text: lambda
Progress: 0.93
translated_text: mu
backtranslated_text: mu
Progress: 0.93
translated_text: nu
backtranslated_text: nu
Progress: 0.93
translated_text: xi
backtranslated_text: xi
Progress: 0.93
translated_text: pi
backtranslated_text: pi
Progress: 0.93
translated_text: rho
backtranslated_text: rho
Progress: 0.93
translated_text: sigma
backtranslated_text: sigma
Progress: 0.93
translated_text: tau
backtranslated_text: tau
Progress: 0.93
translated_text: phi
backtranslated_text: phi
Progress: 0.93
translated_text: chi
backtranslated_text: chi
Progress: 0.93
translated_text: khi
backtranslated_text: khi
Progress: 0.93
translated_text: ac
backtranslated_text: ac
Progress: 0.93
translated_text: advertisement

backtranslated_text: patalastas
Progress: 0.93
translated_text: ad
backtranslated_text: Ad
Progress: 0.93
translated_text: beth
backtranslated_text: beth
Progress: 0.93
translated_text: he
backtranslated_text: siya
Progress: 0.93
translated_text: waw
backtranslated_text: waw
Progress: 0.93
translated_text: mem
backtranslated_text: mem
Progress: 0.93
translated_text: pe
backtranslated_text: pe
Progress: 0.93
translated_text: shin
backtranslated_text: shin
Progress: 0.93
translated_text: foot
backtranslated_text: paa
Progress: 0.93
translated_text: from
backtranslated_text: mula sa
Progress: 0.93
translated_text: pareto
backtranslated_text: pareto
Progress: 0.93
translated_text: spencer
backtranslated_text: spencer
Progress: 0.94
translated_text: alas
backtranslated_text: Naku
Progress: 0.94
translated_text: diamond
backtranslated_text: brilyante
Progress: 0.94
translated_text: spade
backtranslated_text: pala
Progress: 0.94
translated_text: heart
backtranslated_text: puso
Progress: 0.94
translated_text: clover
backtranslated_text: klouber
Progress: 0.94
translated_text: joker
backtranslated_text: joker
Progress: 0.94
translated_text: rap
backtranslated_text: rap
Progress: 0.94
translated_text: intercourse
backtranslated_text: pakikipagtalik
Progress: 0.94
translated_text: lasagna
backtranslated_text: lasagna
Progress: 0.94
translated_text: circumcision
backtranslated_text: pagtutuli
Progress: 0.94
translated_text: decaf
backtranslated_text: decaf
Progress: 0.94
translated_text: espresso
backtranslated_text: espresso
Progress: 0.94
translated_text: mocha
backtranslated_text: mocha
Progress: 0.94
translated_text: soda
backtranslated_text: soda
Progress: 0.94
translated_text: pop
backtranslated_text: pop
Progress: 0.94
translated_text: bark
backtranslated_text: tumahol
Progress: 0.94
translated_text: chirp
backtranslated_text: huni
Progress: 0.94
translated_text: satsat
backtranslated_text: satsat
Progress: 0.94
translated_text: chest
backtranslated_text: dibdib
Progress: 0.94
translated_text: boom
backtranslated_text: boom
Progress: 0.94
translated_text: peep
backtranslated_text: sumilip
Progress: 0.94
translated_text: crow
backtranslated_text: uwak
Progress: 0.94
translated_text: moo
backtranslated_text: moo
Progress: 0.94
translated_text: click
backtranslated_text: i-click
Progress: 0.94
translated_text: coo
backtranslated_text: coo
Progress: 0.94
translated_text: quack
backtranslated_text: kwek-kwek
Progress: 0.95
translated_text: tili
backtranslated_text: tili
Progress: 0.95
translated_text: kokak
backtranslated_text: kokak
Progress: 0.95
translated_text: roar
backtranslated_text: dagundong
Progress: 0.95
translated_text: ngawngaw
backtranslated_text: ngawngaw
Progress: 0.95
translated_text: instrumental
backtranslated_text: instrumental
Progress: 0.95
translated_text: comb
backtranslated_text: suklay
Progress: 0.95
translated_text: comb
backtranslated_text: suklay
Progress: 0.95
translated_text: blade
backtranslated_text: talim
Progress: 0.95
translated_text: iangat
backtranslated_text: iangat
Progress: 0.95
translated_text: pukpok
backtranslated_text: pukpok
Progress: 0.95
translated_text: eyes
backtranslated_text: mata
Progress: 0.95
translated_text: foundry
backtranslated_text: pandayan
Progress: 0.95
translated_text: blacksmith
backtranslated_text: panday
Progress: 0.95
translated_text: hold on
backtranslated_text: hawakan mo
Progress: 0.95
translated_text: miswa
backtranslated_text: miswa
Progress: 0.95
translated_text: macaroni
backtranslated_text: macaroni
Progress: 0.95
translated_text: dumpling
backtranslated_text: dumpling
Progress: 0.95
translated_text: dumplings
backtranslated_text: dumplings
Progress: 0.95
translated_text: shake
backtranslated_text: iling
Progress: 0.95
translated_text: game
backtranslated_text: laro
Progress: 0.95
translated_text: cuts
backtranslated_text: mga hiwa
Progress: 0.95
translated_text: halal
backtranslated_text: halal
Progress: 0.95
translated_text: sausage
backtranslated_text: sausage
Progress: 0.95
translated_text: whey
backtranslated_text: patis ng gatas
Progress: 0.95
translated_text: reforestation
backtranslated_text: reforestation
Progress: 0.95
translated_text: stock
backtranslated_text: stock
Progress: 0.96
translated_text: kabo
backtranslated_text: kabo
Progress: 0.96
translated_text: sintas
backtranslated_text: sintas
Progress: 0.96
translated_text: dvd
backtranslated_text: dvd
Progress: 0.96
translated_text: gasoline
backtranslated_text: gasolina
Progress: 0.96
translated_text: bol
backtranslated_text: bol
Progress: 0.96
translated_text: semen
backtranslated_text: semilya
Progress: 0.96
translated_text: gyera
backtranslated_text: gyera
Progress: 0.96
translated_text: surrender
backtranslated_text: pagsuko
Progress: 0.96
translated_text: advantages
backtranslated_text: mga pakinabang
Progress: 0.96
translated_text: advantage
backtranslated_text: kalamangan
Progress: 0.96
translated_text: disaster
backtranslated_text: sakuna
Progress: 0.96
translated_text: welfare
backtranslated_text: kapakanan
Progress: 0.96
translated_text: adventure
backtranslated_text: pakikipagsapalaran
Progress: 0.96
translated_text: advice
backtranslated_text: payo
Progress: 0.96
translated_text: paalaala
backtranslated_text: paalaala
Progress: 0.96
translated_text: ship
backtranslated_text: barko
Progress: 0.96
translated_text: counselor
backtranslated_text: tagapayo
Progress: 0.96
translated_text: ratify
backtranslated_text: pagtibayin
Progress: 0.96
translated_text: stance
backtranslated_text: paninindigan
Progress: 0.96
translated_text: signature
backtranslated_text: lagda
Progress: 0.96
translated_text: sign
backtranslated_text: tanda
Progress: 0.96
translated_text: uli
backtranslated_text: uli
Progress: 0.96
translated_text: again
backtranslated_text: muli
Progress: 0.96
translated_text: alert
backtranslated_text: alerto
Progress: 0.96
translated_text: ready
backtranslated_text: handa na
Progress: 0.96
translated_text: addicted
backtranslated_text: adik
Progress: 0.97
translated_text: foreigner
backtranslated_text: dayuhan
Progress: 0.97
translated_text: living
backtranslated_text: nabubuhay
Progress: 0.97
translated_text: alliance
backtranslated_text: alyansa
Progress: 0.97
translated_text: distribute
backtranslated_text: ipamahagi
Progress: 0.97
translated_text: allow
backtranslated_text: payagan
Progress: 0.97
translated_text: allow
backtranslated_text: payagan
Progress: 0.97
translated_text: banwa
backtranslated_text: banwa
Progress: 0.97
translated_text: barangay
backtranslated_text: barangay
Progress: 0.97
translated_text: take sides
backtranslated_text: pumanig
Progress: 0.97
translated_text: join
backtranslated_text: sumali
Progress: 0.97
translated_text: almost
backtranslated_text: halos
Progress: 0.97
translated_text: parking
backtranslated_text: paradahan
Progress: 0.97
translated_text: station
backtranslated_text: istasyon
Progress: 0.97
translated_text: station
backtranslated_text: istasyon
Progress: 0.97
translated_text: basbas
backtranslated_text: basbas
Progress: 0.97
translated_text: unique
backtranslated_text: kakaiba
Progress: 0.97
translated_text: batak
backtranslated_text: batak
Progress: 0.97
translated_text: call
backtranslated_text: tawag
Progress: 0.97
translated_text: eldest
backtranslated_text: panganay
Progress: 0.97
translated_text: change
backtranslated_text: pagbabago
Progress: 0.97
translated_text: change
backtranslated_text: pagbabago
Progress: 0.97
translated_text: salitan
backtranslated_text: salitan
Progress: 0.97
translated_text: in return
backtranslated_text: kapalit
Progress: 0.97
translated_text: alternate
backtranslated_text: kahalili
Progress: 0.97
translated_text: testicles
backtranslated_text: mga testicle
Progress: 0.97
translated_text: graduated
backtranslated_text: nagtapos
Progress: 0.98
translated_text: beach
backtranslated_text: tabing dagat
Progress: 0.98
translated_text: wonder
backtranslated_text: pagtataka
Progress: 0.98
translated_text: scare
backtranslated_text: takutin
Progress: 0.98
translated_text: mukmok
backtranslated_text: mukmok
Progress: 0.98
translated_text: tampo
backtranslated_text: tampo
Progress: 0.98
translated_text: pokpok
backtranslated_text: pokpok

Progress: 0.98
translated_text: mumo
backtranslated_text: mumo
Progress: 0.98
translated_text: messenger
backtranslated_text: sugo
Progress: 0.98
translated_text: ambassador
backtranslated_text: ambassador
Progress: 0.98
translated_text: ambition
backtranslated_text: ambisyon
Progress: 0.98
translated_text: desire
backtranslated_text: pagnanasa
Progress: 0.98
translated_text: mithiin
backtranslated_text: mithiin
Progress: 0.98
translated_text: dream
backtranslated_text: pangarap
Progress: 0.98
translated_text: ninang
backtranslated_text: ninang
Progress: 0.98
translated_text: violent
backtranslated_text: marahas
Progress: 0.98
translated_text: interested
backtranslated_text: interesado
Progress: 0.98
translated_text: beke
backtranslated_text: beke
Progress: 0.98
translated_text: greet
backtranslated_text: batiin
Progress: 0.98
translated_text: kiss
backtranslated_text: halikan
Progress: 0.98
translated_text: honest
backtranslated_text: tapat
Progress: 0.98
translated_text: brown
backtranslated_text: kayumanggi
Progress: 0.98
translated_text: moreno
backtranslated_text: moreno
Progress: 0.98
translated_text: biik
backtranslated_text: biik
Progress: 0.98
translated_text: boyfriend
backtranslated_text: kasintahan
Progress: 0.98
translated_text: old
backtranslated_text: luma
Progress: 0.98
translated_text: clam
backtranslated_text: kabibe
Progress: 0.99
translated_text: gums
backtranslated_text: gilagid
Progress: 0.99
translated_text: warning
backtranslated_text: babala
Progress: 0.99
translated_text: puday
backtranslated_text: puday
Progress: 0.99
translated_text: left
backtranslated_text: umalis
Progress: 0.99
translated_text: galaxy
backtranslated_text: galaxy
Progress: 0.99
translated_text: hilo
backtranslated_text: hilo
Progress: 0.99
translated_text: only
backtranslated_text: lamang
Progress: 0.99
translated_text: started
backtranslated_text: nagsimula
Progress: 0.99
translated_text: comedian
backtranslated_text: komedyante
Progress: 0.99
translated_text: condition
backtranslated_text: kundisyon
Progress: 0.99
translated_text: butaw
backtranslated_text: butaw
Progress: 0.99
translated_text: fix
backtranslated_text: ayusin
Progress: 0.99
translated_text: boutique
backtranslated_text: boutique
Progress: 0.99
translated_text: shot
backtranslated_text: binaril
Progress: 0.99
translated_text: flight
backtranslated_text: paglipad
Progress: 0.99
translated_text: black
backtranslated_text: itim
Progress: 0.99
translated_text: pumpkin
backtranslated_text: kalabasa
Progress: 0.99
translated_text: guitarist
backtranslated_text: gitarista
Progress: 0.99
translated_text: natural
backtranslated_text: natural
Progress: 0.99
translated_text: gapang
backtranslated_text: gapang
Progress: 0.99
translated_text: playground
backtranslated_text: palaruan
Progress: 0.99
translated_text: bath
backtranslated_text: paliguan
Progress: 0.99
translated_text: truth
backtranslated_text: katotohanan
Progress: 0.99
translated_text: cheerful
backtranslated_text: masayahin
Progress: 0.99
translated_text: defeated
backtranslated_text: natalo
Progress: 0.99
translated_text: lawyer
backtranslated_text: abogado
Progress: 1.00
translated_text: rainbow
backtranslated_text: bahaghari
Progress: 1.00
translated_text: box office
backtranslated_text: takilya
Progress: 1.00
translated_text: ululin
backtranslated_text: ululin
Progress: 1.00
translated_text: cunning
backtranslated_text: tuso
Progress: 1.00
translated_text: doubt
backtranslated_text: pagdududa
Progress: 1.00
translated_text: inam
backtranslated_text: inam
Progress: 1.00
translated_text: dunong
backtranslated_text: dunong
Progress: 1.00
translated_text: lupig
backtranslated_text: lupig
Progress: 1.00
translated_text: bilasa
backtranslated_text: bilasa
Progress: 1.00
translated_text: narrow
backtranslated_text: makitid
Progress: 1.00
translated_text: tuod
backtranslated_text: tuod
Progress: 1.00
translated_text: turn around
backtranslated_text: umikot
Progress: 1.00
translated_text: anas
backtranslated_text: anas

        fil_text     eng_text backtranslation
0         matino        sober          matino
1         maayos         well          mabuti
2     hanapbuhay   occupation      hanapbuhay
3        trabaho         work         trabaho
4           obra         work         trabaho
...          ...          ...             ...
2593      bilasa       bilasa          bilasa
2594     makipot       narrow         makitid
2595        tuod         tuod            tuod
2596    bumaling  turn around          umikot
2597        anas         anas            anas

[2598 rows x 3 columns]

In [ ]:
translated_text = translated_text.rename(columns={'eng_text': 'eng_word'})
translated_text = translated_text.rename(columns={'fil_text': 'fil_word'})
translated_text

In [30]:
translated_text.to_csv('full_vocab_translated.csv', index=False)