# Merge NLP and NetSci

**Notes:**

* Currently, vocab intersection lang ng NLP and NetSci ang nareretain sa merged wordnet. Possible na may mga vocab na wala sa intersection and hindi masali sa final wordnet.

* This does not take into account existing synsets.

## Setup

In [1]:
import pandas as pd
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!ls

drive  sample_data

## Load NetSci WordNet

In [4]:
NETSCI_WORDNET_PATH = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NetSci Team/wordnet_entries_v3"

In [ ]:
json_files = [NETSCI_WORDNET_PATH + "/" + json_file for json_file in os.listdir(NETSCI_WORDNET_PATH)]
json_files[:5]

In [ ]:
# Load json to dataframe

%%time
from tqdm import tqdm

files = []
for file in tqdm(json_files[450:500]):
  files.append(pd.read_json(file, orient='index').transpose())

In [38]:
# Concatenate dataframes
ns_wordnet = pd.concat(files).reset_index(drop=True)
# Band-aid solution for empty example sentences. Fix this problem at NetSci code level
to_drop = ns_wordnet.loc[ns_wordnet.example_sentences.apply(type) != list].index.values # drop empty example sentences
ns_wordnet = ns_wordnet.drop(to_drop).reset_index(drop=True)
ns_wordnet

,sense_id,word,synset_id,community,example_sentences,contextual_info
0,ns_tugtog_2,tugtog,9106,"[bahay, loob, labas, kapitbahay, malakas, kwar...",[XX_USERNAME nagbabardagulan kami ng kapit bah...,"{'books': {'100year': {'1907': 4, '1908': 1, '..."
1,ns_tugtog_3,tugtog,9107,"[lagi, sana, baka, nalang, kuya, birthday, hap...",[Hap nagising ako sa malakas na tugtog na Happ...,"{'news_sites': {'abscbn': {'2021': 1}, 'bander..."
2,ns_tugtog_4,tugtog,9108,"[buhay, kailangan, alam, parang, anong, kita, ...",[di ko alam kung anong meron pero every Sunday...,"{'news_sites': {'abante': {'2020': 1}, 'balita..."
3,ns_tugtog_5,tugtog,9109,"[kasama, oras, lalaki, umaga, matapos, red, il...",[At sino rin ang makalilimot sa eksena ng libi...,"{'books': {'100year': {'1901': 1, '1902': 1, '..."
4,ns_tuhod_0,tuhod,9110,"[buwan, bahay, lugar, tagalog, araw, laro, kar...",[Hindi nakalaro si Curry at inaasahang magpapa...,"{'books': {'100year': {'1902': 1, '1905': 1, '..."
5,ns_tuhod_1,tuhod,158,"[puso, tama, puti, daliri, katawan, sakit, mat...","[Sa bikas na iyon ni Gloria , lilis ang salawa...","{'books': {'100year': {'1902': 2, '1907': 5, '..."
6,ns_tuhod_2,tuhod,109,"[lagi, ung, tapos, sana, ginagawa, alam, paran...","[""E , kasi sumabay ako sa contestants , sinaba...","{'books': {'100year': {'1902': 2, '1907': 3, '..."
7,ns_tuhod_3,tuhod,9111,"[mahirap, kailangan, pati, kapatid, pangalan, ...","[9 Kaya siya naman ay pinakadakila ng Dios , a...","{'books': {'100year': {'1902': 2, '1907': 2, '..."
8,ns_tuklas_0,tuklas,9112,"[bagong, pag-aaral, program, lunas, natuklasan...",[Nasa 32 klase ng halaman ang mga bagong natuk...,"{'books': {'100year': {'1937': 1, '1959': 1, '..."
9,ns_tuklas_1,tuklas,9113,"[entertainment, ilang, larangan, makasaysayang]",[Anim na prizes ang napunta sa mga mananaliksi...,"{'news_sites': {'balita': {'2014': 3, '2016': ..."
10,ns_tukoy_0,tukoy,9114,"[kasama, tao, sana, alam, anong, loob, pangala...",[XX_OTHERS mula sa XX_OTHERS Ang Gawain ng Diy...,"{'books': {'100year': {'1902': 3, '1907': 10, ..."
11,ns_tukoy_1,tukoy,9115,"[pangalang, biktima, lalaki, kasamahan, dalawa...",[Tukoy na ng mga awtoridad ang pagkakakilanlan...,"{'news_sites': {'abante': {'2020': 4, '2021': ..."
12,ns_tukoy_2,tukoy,9116,"[katawan, baril, bala, bahagi, sanhi, pinagmul...",[Dead on the spot ang biktimang si Lyndie Saca...,"{'news_sites': {'abante': {'2020': 1}, 'balita..."
13,ns_tukoy_3,tukoy,9117,"[lugar, nasabing, kabilang, ilang, miyembro, p...","[Sa nasabing bilang , 1 , 663 na ang tukoy ang...","{'books': {'100year': {'1946': 1, '1986': 1, '..."
14,ns_tulak_0,tulak,9118,"[biktima, patuloy, gamot, ipinagbabawal, kasam...",[Naaresto ang isang babae sa ikinasang buy-bus...,"{'books': {'100year': {'1902': 1, '1907': 1, '..."
15,ns_tulak_1,tulak,9119,"[buhay, kasama, tapos, alam, bahay, pagiging, ...","[Matapos ang krimen , nag-iwan ang mga suspek ...","{'books': {'100year': {'1908': 1, '1920': 1, '..."
16,ns_tulak_2,tulak,239,"[driver, lalaki, spot, matapos, itong, dalawan...",[Patay ang dalawang lalaki matapos pagbabarili...,"{'news_sites': {'abante': {'2020': 6, '2021': ..."
17,ns_tulak_3,tulak,9120,"[mahigit, bansa, pitong, kabilang, limang, eda...",[Arestado ang siyam na pinaghihinalaang tulak ...,"{'news_sites': {'abante': {'2020': 3, '2021': ..."
18,ns_tulak_4,tulak,9121,"[bayan, lugar, nasabing, maynila, manila, baco...",[Ang iba pang hinihinalang tulak ay binitbit n...,"{'news_sites': {'abante': {'2020': 15, '2021':..."
19,ns_tuldok_0,tuldok,9122,"[tao, lupa, lalo, ginawa, maliliit, galit, tal...",[18 Sapagka't katotohanang sinasabi ko sa inyo...,"{'books': {'100year': {'1938': 1, '1980': 1, '..."
20,ns_tuldok_1,tuldok,9123,"[lagyan, tapos, pala, akala, dulo, napansin, p...",[XX_USERNAME nakakatakot naman 'yung tuldok sa...,"{'news_sites': {'balita': {'2017': 1}, 'bander..."
21,ns_tuldok_2,tuldok,9124,"[natin, sana, alam, baka, point, basta, usapan...",[XX_USERNAME basta tuldok pa lang ni ate Keia ...,"{'news_sites': {'abante': {'2021': 1}, 'balita..."
22,ns_tuldok_3,tuldok,9125,"[parang, ata, sobrang, cute, bat, bula, pogi, ...","[parang hindi siya yon , nanay niya ata yung s...","{'news_sites': {'abante': {'2020': 1, '2021': ..."
23,ns_tulin_0,tulin,9126,"[hayop, taong, simbahan, gawain, kasabay, tila...","["" At kasabay nito ang panakbuhang duma-raguno...","{'books': {'100year': {'1901': 2, '1902': 4, '..."
24,ns_tulin_1,tulin,9127,"[araw, driver, dalawang, halos, panalo, takbo,...","[Sa tulin ng takbo , tumilapon ang mag-asawa m...","{'books': {'100year': {'1914': 1, '1921': 1}, ..."
25,ns_tulin_2,tulin,298,"[sobrang, lakas, umubra]",[Hindi umubra ang tulin sa pagtakbo ng lima da...,"{'news_sites': {'abante': {'2020': 3, '2021': ..."
26,ns_tulisan_0,tulisan,9128,"[tao, natin, puso, parang, baka, gawa, ginawa,...","[8:9 At ngayon , masdan , wala na akong sasabi...","{'books': {'100year': {'1902': 9, '1907': 7, '..."
27,ns_tulisan_1,tulisan,9129,"[bayan, pangulo, bundok, magnanakaw, civil, ak...",[Ang paglusob ng mga tulisan kasama si Modesto...,"{'books': {'100year': {'1902': 10, '1907': 10,..."
28,ns_tulisan_2,tulisan,9130,"[kasama, bahay, loob, anak, dalawang, dala, pa...",[Ang pangalang sinambít ay naging wari isang t...,"{'books': {'100year': {'1902': 2, '1907': 2, '..."
29,ns_tulog_0,tulog,45,"[ung, tapos, hirap, daming, class, parin, para...",[Ang sarap nang tulog ko kanina kasi napanagin...,"{'books': {'100year': {'1902': 2, '1905': 1, '..."
30,ns_tulog_1,tulog,295,"[pre, pera, fb, pwede, sana, gagawa, aalis, ma...",[After bantay kay papa alawads na araw lang tu...,"{'books': {'100year': {'1936': 1, '1980': 1, '..."
31,ns_tulog_2,tulog,9131,"[boss, kasama, pasko, namatay, nagkaroon, buwa...",[Sa isang pag-aaral ng University of Pennysylv...,"{'books': {'100year': {'1901': 1, '1902': 2, '..."
32,ns_tulog_3,tulog,96,"[mahirap, buhay, kailangan, lagi, tao, natin, ...",[Maaring lagi syang tulog pero siya yung taong...,"{'books': {'100year': {'1901': 1, '1905': 1, '..."
33,ns_tuluyan_0,tuluyan,9132,"[ung, tapos, pera, fb, pati, meron, pwede, san...",[Thankyouu sa pagsama sakin mahal XX_EMOJI XX_...,"{'books': {'100year': {'1905': 2, '1908': 1, '..."
34,ns_tuluyan_1,tuluyan,9133,"[namatay, bayan, mindanao, bagyo, lugar, pilip...",[Itinanong din kay Sec Andanar kung nahihirapa...,"{'books': {'100year': {'1918': 1, '1933': 1, '..."
35,ns_tuluyan_2,tuluyan,9134,"[buhay, kailangan, tao, natin, ginagawa, bagay...",[Nagbalik ang Panginoong Jesus upang gawin ang...,"{'books': {'100year': {'1902': 1, '1907': 1, '..."
36,ns_tumaas_0,tumaas,9135,"[mahirap, kailangan, kasama, ung, tapos, pera,...",[I read ur biography sa wikipedia ... lalong t...,"{'books': {'100year': {'1937': 2, '1976': 3, '..."
37,ns_tumaas_1,tumaas,344,"[filipino, bayan, mindanao, mataas, cash, luga...",[Batay sa ulat ng Bangko Sentral ng Pilipinas ...,"{'books': {'100year': {'1974': 1, '2001': 2, '..."
38,ns_tumaas_2,tumaas,194,"[namatay, buwan, beses, martes, araw, taon, bi...","[Makaraang makatipon ng kabuuang 8 , 156 , 366...","{'books': {'100year': {'1976': 2, '1999': 1, '..."
39,ns_tumaas_3,tumaas,9136,"[kada, meralco, spot, prices, manok, gumagamit...",[Tumaas umano ang singil ng P0 . 1135 / kWh da...,"{'books': {'100year': {'1956': 1, '1974': 1, '..."
40,ns_tumakbo_0,tumakbo,220,"[filipino, mataas, pilipinas, ilalim, karapata...",[Si Robredo ay tumakbo sa ilalim ng Liberal Pa...,"{'books': {'100year': {'1902': 3, '1907': 3, '..."
41,ns_tumakbo_1,tumakbo,9137,"[ung, tapos, pera, hirap, pati, meron, parin, ...",[- then isang gabi mag sstay lang sana ako sa ...,"{'books': {'100year': {'1907': 1, '1908': 6, '..."
42,ns_tumakbo_2,tumakbo,76,"[buhay, kailangan, puno, tao, nagkaroon, natin...",[Isa itong patunay na handang tumulong ang tao...,"{'books': {'100year': {'1902': 2, '1907': 2, '..."
43,ns_tumanaw_0,tumanaw,9138,"[kailangan, tao, sana, tama, anak, taong, maru...",[Hindi muna sumagot si Modesto kay Victor at w...,"{'books': {'100year': {'1902': 1, '1905': 1, '..."
44,ns_tumanaw_1,tumanaw,9139,"[bahay, loob, labas, utang, bintana, dakong, d...","[Ganoon siya kung tumanaw ng utang na loob ., ...","{'books': {'100year': {'1907': 1, '1908': 3, '..."
45,ns_tumanggap_0,tumanggap,9140,"[mahirap, kailangan, tapos, pera, natin, hirap...",[Nang tanungin kasi namin kung puwede siyang t...,"{'books': {'100year': {'1905': 2, '1908': 1, '..."
46,ns_tumanggap_1,tumanggap,9141,"[buhay, tao, ginagawa, bagay, magiging, puso, ...",[Ang Gawain sa Kapanahunan ng Kautusan Ang Tun...,"{'books': {'100year': {'1902': 1, '1907': 1, '..."
47,ns_tumanggap_2,tumanggap,9142,"[silver, pasko, namatay, buwan, filipino, bese...",[Binanggit ni PAO forensics chief Dr Erwin Erf...,"{'books': {'100year': {'1902': 1, '1908': 1, '..."
48,ns_tumanggap_3,tumanggap,9143,"[mataas, empleyado, sahod, karapatang, karagda...",[Inihayag ng abogado ni dating Senador Ferdina...,"{'books': {'100year': {'1909': 1, '1910': 2, '..."
49,ns_tumanggap_4,tumanggap,9144,"[bayan, lugar, nasabing, maynila, foreign, loc...",[Nasabat ng mga operatiba ng Bureau of Customs...,"{'books': {'100year': {'1910': 1, '1936': 2, '..."

## Load NLP WordNet

In [83]:
NLP_WORDNET_PATH = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/modified_filwordnet.pkl"

In [84]:
nlp_wordnet = pd.read_pickle(NLP_WORDNET_PATH)

In [85]:
nlp_wordnet

,word,sense_id,sense_embedding,example_sentences,contextual_info,pos
0,abala,abala_0,"[0.011410227, 0.005817835, -0.008558039, 0.030...","[ng gabi, habang abala umano sa pagtitinda ang...","{'news_sites': {'balita': {'2016': 2, '2020': ...",NN
1,abala,abala_1,"[0.035149045, 0.062080346, 0.018494673, -0.062...","[pasensya na sa abala!, sa abala., po, pasensy...","{'social_media': {'twitter': {'2021': 8}}, 'ne...",NN
2,abala,abala_2,"[0.018175527, 0.015186829, 0.019982383, 0.0261...",[sa piitan nitong Miyerkules habang abala ang ...,"{'news_sites': {'gma': {'2014': 1, '2017': 1},...",NN
3,abala,abala_3,"[0.0139153, 0.017601732, 0.018305968, -0.04806...","[ito sa abala niyang schedule., noon ay naging...","{'news_sites': {'balita': {'2016': 1, '2014': ...",JJ
4,abalahin,abalahin_0,"[-0.0037691495, 0.033807106, 0.021705411, -0.0...","[Huwag mo na siyang abalahin., Huwag mong abal...","{'social_media': {'twitter': {'2021': 3}}, 'ne...",VB
...,...,...,...,...,...,...
7172,zombie,zombie_1,"[0.023807092, 0.043104503, 0.043869168, -0.041...",[: Hala magiging zombie kanaKuya ko : okay lan...,{'social_media': {'twitter': {'2021': 6}}},NN
7173,zombie,zombie_2,"[-0.026886176, -0.020745393, 0.047452476, -0.0...","[sa mga silibgan nga maging zombie daw., nalan...",{'social_media': {'twitter': {'2021': 10}}},NN
7174,zombie,zombie_3,"[0.013196042, 0.013754795, 0.038955215, -0.020...","[at hindi dahil sa zombie hahahahaha, kala mo ...",{'social_media': {'twitter': {'2021': 10}}},NN
7175,zoology,zoology_0,"[0.008698043, 0.00089879415, 0.058598656, -0.0...","[ako gumawa ng assignment sa zoology huhu, nab...",{'social_media': {'twitter': {'2021': 10}}},NN
7176,zoology,zoology_1,"[0.024566494, 0.011660036, 0.046377443, -0.012...",[ilagay yung phenotypic ratio sa zoology haaha...,{'social_media': {'twitter': {'2021': 4}}},CD

## Convert NetSci WordNet to NLP WordNet format

In [28]:
!pip install sentence_transformers -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 10.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 104.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 78.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 111.7 MB/s eta 0:00:00
  Building wheel for sentence_transformers (setup.py) ... done

In [29]:
from sentence_transformers import SentenceTransformer

MODEL_DIR = "/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/models"

model = SentenceTransformer(f'{MODEL_DIR}/sroberta-nli-1epoch')
model

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: RobertaModel
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)

In [ ]:
ns_wordnet.head()

,sense_id,word,synset_id,community,example_sentences,contextual_info
0,ns_tanggalin_2,tanggalin,8771,"[mahirap, buhay, kailangan, kasama, tao, natin...",[Dahil sa Kanyang paghatol at pagkastigo tayo ...,"{'books': {'100year': {'1986': 1, '2003': 1}, ..."
1,ns_tanggalin_3,tanggalin,8772,"[pork, batas, pwesto, plano, sakaling, tax, go...",[Hiniling ni Senator Miriam Defensor-Santiago ...,"{'news_sites': {'abante': {'2020': 11, '2021':..."
2,ns_tanggapan_0,tanggapan,8773,"[kailangan, kasama, pera, tao, natin, bayan, p...",[Inihayag ng Palasyo na suspendido ang pasok s...,"{'books': {'100year': {'1902': 2, '1908': 3, '..."
3,ns_tanggapan_1,tanggapan,144,"[regional, community, bir, sss, office, group,...",[Lumutang na sa tanggapan ng National Bureau o...,"{'news_sites': {'abante': {'2020': 32, '2021':..."
4,ns_tanggapan_2,tanggapan,525,"[kongreso, aquino, senator, bumisita, kasaluku...",[Sinabi ng tanggapan ni Vice President Leni Ro...,"{'books': {'100year': {'1937': 1, '1956': 1, '..."

In [ ]:
nlp_wordnet.head()

In [39]:
import torch

def text_to_embs(sentence_list_texts):
    sentence_embeddings = model.encode(sentence_list_texts, show_progress_bar=False, normalize_embeddings=True)

    return torch.tensor(sentence_embeddings)

def mean_embs(sentence_embs):
    sense_embeddings = torch.mean(sentence_embs, dim=0)

    return sense_embeddings

def get_sentence_embs_df(df):
    df['sense_embedding'] = None

    for idx, row in df.iterrows():
        # get example sentences
        sentence_list_texts = row['example_sentences']

        # encode to sentence embeddings
        sentence_embeddings = text_to_embs(sentence_list_texts)

        # mean sentence embeddings
        sense_embeddings = mean_embs(sentence_embeddings)

        # append sense embeddings to dataframe row
        row['sense_embedding'] = sense_embeddings

    return df

In [ ]:
ns_wordnet = get_sentence_embs_df(ns_wordnet)
ns_wordnet

In [ ]:
nlp_wordnet = get_sentence_embs_df(nlp_wordnet)
nlp_wordnet

## Merge senses

In [87]:
import torch
import torch.nn.functional as F

def merge_wn(nlp_wn, ns_wn, thres):
    new_wn = pd.DataFrame()
    new_wn['merge_label'] = None

    # Initialize 
    cos = torch.nn.CosineSimilarity(dim=1, eps=1e-08)

    # Get vocab intersection
    nlp_vocab = set(nlp_wn['word'].tolist())
    ns_vocab = set(ns_wn['word'].tolist())
    vocab_combined = nlp_vocab.intersection(ns_vocab)  

    for w in vocab_combined:
        ns_rows = ns_wn.loc[ns_wn['word'] == w]
        nlp_rows = nlp_wn.loc[nlp_wn['word'] == w]

        ns_se = torch.stack(ns_rows['sense_embedding'].tolist())
        nlp_se = torch.stack(nlp_rows['sense_embedding'].tolist())
        
        # cosine similarity = normalize the vectors & multiply
        similarity_matrix = F.normalize(nlp_se) @ F.normalize(ns_se).t()
        max_values, indices = torch.max(similarity_matrix, dim=1)

        # apply threshold
        for idx, mv in enumerate(max_values):
            if mv < thres: # below threshold, append row
                indices[idx] = -1 # sentinel value, marks the rows that will be ignored later

        for idx_nlp, idx_ns in enumerate(indices):
            idx_ns_scalar = idx_ns.item()
            
            if idx_ns_scalar != -1:
                row_nlp = nlp_rows.iloc[idx_nlp].append(pd.Series({'merge_label': idx_ns_scalar}))
                new_wn = new_wn.append(row_nlp, ignore_index=True)
                row_ns = ns_rows.iloc[idx_ns_scalar].append(pd.Series({'merge_label': idx_ns_scalar}))
                new_wn = new_wn.append(row_ns, ignore_index=True)
            else:
                row_nlp = nlp_rows.iloc[idx_nlp].append(pd.Series({'merge_label': -1})) # -1 means no group
                new_wn = new_wn.append(row_nlp, ignore_index=True)
        
        sense_ids = new_wn['sense_id'].tolist()
        ns_sense_ids = [id for id in sense_ids if "ns" in id]

        for idx, row_ns in ns_rows.iterrows():
            if row_ns['sense_id'] not in ns_sense_ids:
                row_ns = row_ns.append(pd.Series({'merge_label': -1})) # -1 means no group
                new_wn = new_wn.append(row_ns, ignore_index=True)


    # drop duplicates
    new_wn = new_wn.drop_duplicates(subset=['sense_id']).reset_index(drop=True)

    return new_wn

In [88]:
new_wn = merge_wn(nlp_wordnet, ns_wordnet, 0.4)
new_wn

,merge_label,contextual_info,example_sentences,pos,sense_embedding,sense_id,word,community,synset_id
0,3,{'social_media': {'twitter': {'2021': 10}}},"[sa all caps na may tuldok, bakit may tuldok l...",NN,"[tensor(0.0062), tensor(0.0249), tensor(0.0634...",tuldok_0,tuldok,NaN,NaN
1,3,"{'news_sites': {'abante': {'2020': 1, '2021': ...","[parang hindi siya yon , nanay niya ata yung s...",NaN,"[tensor(0.0024), tensor(0.0395), tensor(0.0534...",ns_tuldok_3,tuldok,"[parang, ata, sobrang, cute, bat, bula, pogi, ...",9125
2,-1,"{'books': {'100year': {'1938': 1, '1980': 1, '...",[18 Sapagka't katotohanang sinasabi ko sa inyo...,NaN,"[tensor(0.0090), tensor(0.0301), tensor(0.0240...",ns_tuldok_0,tuldok,"[tao, lupa, lalo, ginawa, maliliit, galit, tal...",9122
3,-1,"{'news_sites': {'balita': {'2017': 1}, 'bander...",[XX_USERNAME nakakatakot naman 'yung tuldok sa...,NaN,"[tensor(0.0166), tensor(0.0262), tensor(0.0646...",ns_tuldok_1,tuldok,"[lagyan, tapos, pala, akala, dulo, napansin, p...",9123
4,-1,"{'news_sites': {'abante': {'2021': 1}, 'balita...",[XX_USERNAME basta tuldok pa lang ni ate Keia ...,NaN,"[tensor(-0.0070), tensor(0.0434), tensor(0.050...",ns_tuldok_2,tuldok,"[natin, sana, alam, baka, point, basta, usapan...",9124
...,...,...,...,...,...,...,...,...,...
74,0,{'social_media': {'twitter': {'2021': 10}}},"[Ganitong wala pa kong tulog, sobra pa sa 8 ho...",NN,"[tensor(-0.0059), tensor(0.0446), tensor(0.011...",tulog_0,tulog,NaN,NaN
75,0,"{'books': {'100year': {'1902': 2, '1905': 1, '...",[Ang sarap nang tulog ko kanina kasi napanagin...,NaN,"[tensor(0.0026), tensor(0.0399), tensor(0.0425...",ns_tulog_0,tulog,"[ung, tapos, hirap, daming, class, parin, para...",45
76,-1,"{'books': {'100year': {'1936': 1, '1980': 1, '...",[After bantay kay papa alawads na araw lang tu...,NaN,"[tensor(0.0041), tensor(0.0709), tensor(0.0370...",ns_tulog_1,tulog,"[pre, pera, fb, pwede, sana, gagawa, aalis, ma...",295
77,-1,"{'books': {'100year': {'1901': 1, '1902': 2, '...",[Sa isang pag-aaral ng University of Pennysylv...,NaN,"[tensor(0.0095), tensor(0.0298), tensor(0.0292...",ns_tulog_2,tulog,"[boss, kasama, pasko, namatay, nagkaroon, buwa...",9131
78,-1,"{'books': {'100year': {'1901': 1, '1905': 1, '...",[Maaring lagi syang tulog pero siya yung taong...,NaN,"[tensor(0.0029), tensor(0.0498), tensor(0.0076...",ns_tulog_3,tulog,"[mahirap, buhay, kailangan, lagi, tao, natin, ...",96

## Merge senses metadata

In [195]:
def aggregate_example_sentences(example_sentences_lst):
    res = []
    for lst in example_sentences_lst:
        res += lst
    
    return res
    
def aggregate_contextual_info(contextual_info_lst):
    res = {}
    for i in contextual_info_lst:
        for k_sourcetype in i:
            v_sourcetype = i[k_sourcetype]
            # print(k_sourcetype)
            # print(f"    {v_sourcetype}")

            if k_sourcetype not in res: # first time
                res[k_sourcetype] = {}

            for k_source in v_sourcetype:
                v_source = v_sourcetype[k_source]
                # print(f"        {k_source}")
                # print(f"        {v_source}")

                if k_source not in res[k_sourcetype]: # first time
                    res[k_sourcetype][k_source] = {}

                for k_year in v_source:
                    v_year = v_source[k_year]
                    # print(f"            {k_year}")
                    # print(f"            {v_year}")

                    if k_year not in res[k_sourcetype][k_source]: # first time
                        res[k_sourcetype][k_source][k_year] = v_year
                    else:
                        res[k_sourcetype][k_source][k_year] += v_year
                        
    return res

def aggregate_pos(pos_lst):
    return pos_lst

def aggregate_community(community_lst):
    return community_lst

def aggregate_sense_embeddings(sense_embeddings_lst):
    tensors = [t for t in sense_embeddings_lst]
    tensors = torch.stack(tensors)
    mean = torch.mean(tensors, dim=0, keepdim=True)

    return mean

# NOT YET SURE HOW TO HANDLE COMMUNITY AND POS
def aggregate_metadata(wn):
    vocab = list(set(new_wn['word'].values))
    cols = ['word', 'sense_id', 'example_sentences', 'contextual_info']
    df_res = pd.DataFrame(columns=cols)

    for w in vocab[:5]:
        df_w = wn[wn['word'] == w]
        group_labels = list(set(df_w['merge_label'].values.tolist()))
        print(w)

        for idx, group in enumerate(group_labels):
            df_group = df_w[df_w['merge_label'] == group]

            if group == -1:
                df_res = df_res.append(df_group[cols])
            else:
                row = {}
                contextual_info = df_group['contextual_info'].values
                example_sentences = df_group['example_sentences'].values
                pos = df_group['pos'].dropna().values
                community = df_group['community'].dropna().values
                sense_embedding = df_group['sense_embedding'].values

                combined_pos =  aggregate_pos(pos) # TEMPORARY: drop nan, aggregate all pos
                combined_communities =  aggregate_community(community) # TEMPORARY: drop nan, aggregate all pos
                combined_contextual_info = aggregate_contextual_info(contextual_info)
                combined_example_sentences = aggregate_example_sentences(example_sentences)
                combined_sense_embedding = aggregate_sense_embeddings(sense_embedding)
                
                row['word'] = w
                row['sense_id'] = f"new_{w}_{idx}"
                row['pos'] = combined_pos
                row['community'] = combined_communities
                row['example_sentences'] = combined_example_sentences
                row['contextual_info'] = combined_contextual_info
                row['sense_embedding'] = combined_sense_embedding

                df_res = df_res.append(row, ignore_index=True)
    
    df_res = df_res.reset_index(drop=True)

    return df_res

In [196]:
final_wn = aggregate_metadata(new_wn)
final_wn

tuldok
torch.Size([1, 768])
tumanggap
torch.Size([1, 768])
torch.Size([1, 768])
tulin
torch.Size([1, 768])
torch.Size([1, 768])
tulisan
torch.Size([1, 768])
torch.Size([1, 768])
tumaas
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

,word,sense_id,example_sentences,contextual_info,community,pos,sense_embedding
0,tuldok,new_tuldok_0,"[sa all caps na may tuldok, bakit may tuldok l...","{'social_media': {'twitter': {'2021': 27}}, 'n...","[[parang, ata, sobrang, cute, bat, bula, pogi,...",[NN],"[[tensor(0.0043), tensor(0.0322), tensor(0.058..."
1,tuldok,ns_tuldok_0,[18 Sapagka't katotohanang sinasabi ko sa inyo...,"{'books': {'100year': {'1938': 1, '1980': 1, '...",NaN,NaN,NaN
2,tuldok,ns_tuldok_1,[XX_USERNAME nakakatakot naman 'yung tuldok sa...,"{'news_sites': {'balita': {'2017': 1}, 'bander...",NaN,NaN,NaN
3,tuldok,ns_tuldok_2,[XX_USERNAME basta tuldok pa lang ni ate Keia ...,"{'news_sites': {'abante': {'2021': 1}, 'balita...",NaN,NaN,NaN
4,tumanggap,new_tumanggap_0,"[tayong tumanggap ng acceptance., sa lahat ng ...","{'social_media': {'twitter': {'2021': 500}}, '...","[[mahirap, kailangan, tapos, pera, natin, hira...",[VB],"[[tensor(0.0024), tensor(0.0250), tensor(0.037..."
5,tumanggap,new_tumanggap_1,"[kahapon ng madaling araw, tumanggap ng P10, 0...","{'news_sites': {'balita': {'2017': 35, '2016':...","[[mataas, empleyado, sahod, karapatang, karagd...",[VB],"[[tensor(0.0047), tensor(0.0064), tensor(0.004..."
6,tumanggap,ns_tumanggap_1,[Ang Gawain sa Kapanahunan ng Kautusan Ang Tun...,"{'books': {'100year': {'1902': 1, '1907': 1, '...",NaN,NaN,NaN
7,tumanggap,ns_tumanggap_2,[Binanggit ni PAO forensics chief Dr Erwin Erf...,"{'books': {'100year': {'1902': 1, '1908': 1, '...",NaN,NaN,NaN
8,tumanggap,ns_tumanggap_4,[Nasabat ng mga operatiba ng Bureau of Customs...,"{'books': {'100year': {'1910': 1, '1936': 2, '...",NaN,NaN,NaN
9,tulin,new_tulin_0,[pa ang tulin ng Aking gawain ay hindi humihin...,"{'books': {'google_books': {'2019': 13}, '100y...","[[hayop, taong, simbahan, gawain, kasabay, til...",[NN],"[[tensor(0.0022), tensor(0.0159), tensor(0.008..."
10,tulin,new_tulin_1,[ni Best Regards ang tulin nito sa largahan up...,"{'news_sites': {'abante': {'2021': 7, '2020': ...","[[sobrang, lakas, umubra]]",[NN],"[[tensor(0.0079), tensor(-0.0149), tensor(-0.0..."
11,tulin,tulin_1,"[ako ani murag wala ni tulin ba., sabagay mas ...",{'social_media': {'twitter': {'2021': 4}}},NaN,NaN,NaN
12,tulin,ns_tulin_1,"[Sa tulin ng takbo , tumilapon ang mag-asawa m...","{'books': {'100year': {'1914': 1, '1921': 1}, ...",NaN,NaN,NaN
13,tulisan,new_tulisan_0,"[Lamanita at sa mga tulisan ni Gadianton, hang...","{'books': {'google_books': {'1998': 45, '2018'...","[[tao, natin, puso, parang, baka, gawa, ginawa...",[NN],"[[tensor(-0.0516), tensor(0.0347), tensor(-0.0..."
14,tulisan,new_tulisan_1,[tulisan sa senado bat tung c NANCY BITAY nka ...,"{'social_media': {'twitter': {'2021': 15}}, 'b...","[[bayan, pangulo, bundok, magnanakaw, civil, a...",[NN],"[[tensor(-0.0420), tensor(0.0274), tensor(0.03..."
15,tulisan,ns_tulisan_2,[Ang pangalang sinambít ay naging wari isang t...,"{'books': {'100year': {'1902': 2, '1907': 2, '...",NaN,NaN,NaN
16,tumaas,new_tumaas_0,"[Taena, tumaas na nga yung standard ko sa, tum...","{'social_media': {'twitter': {'2021': 804}}, '...","[[mahirap, kailangan, kasama, ung, tapos, pera...",[VB],"[[tensor(-0.0056), tensor(0.0157), tensor(0.03..."
17,tumaas,new_tumaas_1,"[Bigla lang tumaas ng kaunti yung bilang ng, n...","{'news_sites': {'mb': {'2021': 20, '2020': 15}...","[[filipino, bayan, mindanao, mataas, cash, lug...",[VB],"[[tensor(0.0129), tensor(0.0128), tensor(-0.02..."
18,tumaas,new_tumaas_2,"[Mabilis kasing tumaas ang lebel ng tubig sa, ...","{'news_sites': {'radyoinquirer': {'2021': 27, ...","[[namatay, buwan, beses, martes, araw, taon, b...",[VB],"[[tensor(0.0266), tensor(-0.0171), tensor(-0.0..."
19,tumaas,new_tumaas_3,[kaya yung mga bilihin tumaas at sa consumer i...,"{'social_media': {'twitter': {'2021': 152}}, '...","[[kada, meralco, spot, prices, manok, gumagami...",[VB],"[[tensor(0.0018), tensor(0.0119), tensor(0.004..."

## Save merged outputs

In [197]:
final_wn.to_pickle("/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/merged_wordnet.pkl", protocol=3)
final_wn.to_csv("/content/drive/Shareddrives/DOST FilWordNet x WordSense/Thesis/NLP Team/merged_wordnet.csv", index=False)